begin;
select plan(16);
select has_table('public','company_profiles','canonical company profiles exists');
select col_is_pk('public','company_profiles','business_id','one profile per workspace');
select has_column('public','company_profiles','legal_name','legal name exists');
select has_column('public','company_profiles','display_name','display name exists');
select has_column('public','company_profiles','entity_type','entity type exists');
select has_column('public','company_profiles','tax_id','tax id exists');
select has_column('public','company_profiles','iban','iban exists');
select has_column('public','company_profiles','swift_bic','swift bic exists');
select has_column('public','company_profiles','default_currency','currency exists');
select has_column('public','company_profiles','timezone','timezone exists');
select col_not_null('public','company_profiles','business_id','workspace required');
select col_not_null('public','company_profiles','legal_name','legal name cannot be null');
select col_not_null('public','company_profiles','updated_at','updated timestamp required');
select has_function('public','get_public_legal_page',array['uuid','text','text'],'legal renderer remains available');
select ok(exists(select 1 from public.company_profiles where business_id='00000000-0000-4000-8000-000000000001'),'demo workspace has company profile');
select is((select count(*)::integer from public.company_profiles where business_id='00000000-0000-4000-8000-000000000001'),1,'workspace has exactly one company profile');
select * from finish();
rollback;
