import type { GuideArticle } from "../../types";

/** Canonical English content. Future translations belong in separate locale files. */
export const EN_GUIDE_ARTICLES = [
  {
    slug: "how-online-booking-works-for-service-businesses", path: "/guides/how-online-booking-works-for-service-businesses",
    title: "How Online Booking Works on a Service Business Website",
    h1: "How online booking works on a service business website",
    description: "A practical guide to the website appointment booking workflow, from choosing a service and time to the client record and follow-up.",
    publishedAt: "2026-09-08", category: "Guide", primaryCategory: "Booking", topics: ["Booking", "Business"], excerpt: "Understand the complete online booking workflow before choosing a system for your service business website.", searchIntent: "how online booking works",
    sections: [
      { title: "What happens before a booking", paragraphs: ["A useful booking journey starts with a clear service menu. Each service should explain what the customer is booking, how long it takes, and any price or availability information that has been configured. The website gives the visitor enough context to choose without starting a separate conversation.", "The business also needs working availability. A booking system connects services to the schedule that the business maintains, so the times shown to a visitor reflect the configuration rather than an empty form."], checklist: ["Services have clear names and descriptions", "Availability is configured for the people or resources being booked", "The booking path is easy to find on mobile"] },
      { title: "How a customer selects a time", paragraphs: ["The customer chooses a service, reviews available times, and selects the option that fits. A good flow keeps the decision focused: service first, then time, then contact details. It should make the selected service and time visible before submission so the customer can catch a mistake." ] },
      { title: "Contact details and submission", paragraphs: ["The customer supplies the contact details required by the business. After submission, the system records the booking instead of leaving it in an inbox or a social message. Confirmation and reminder behavior depends on what the business has enabled and configured." ] },
      { title: "What happens after submission", paragraphs: ["The booking becomes part of the operational record. The client record can retain the relationship and booking history, while the schedule reflects the appointment. Where payments are configured, payment status or history can remain connected to that client activity. Google Calendar connection is available where configured, so the business can keep its working calendar aligned with the booking workflow." ] },
      { title: "What to check before choosing a booking system", paragraphs: ["Ask whether the system connects the public website, services, availability, client records, payments, notifications, and calendar in a way your team can actually use. A booking form alone may collect a request, but it does not necessarily create a useful operational history.", "For a closer look at the platform capability, see [[online booking|/features/online-booking]] and [[CRM|/features/crm]]. You can also compare the broader [[service business solutions|/solutions]] or [[pricing|/pricing]]. Beauty salons, pet groomers, and Pilates studios can review their relevant [[salon solution|/solutions/beauty-salon-website]], [[pet grooming solution|/solutions/pet-grooming-website]], and [[Pilates solution|/solutions/pilates-studio-website]]."] },
    ], relatedLinks: [{label:"Online Booking",href:"/features/online-booking"},{label:"CRM",href:"/features/crm"},{label:"Solutions",href:"/solutions"}],
    faq: [{question:"Can online booking work without taking payment?",answer:"Yes. Payment support is a configuration choice, so a business can use the booking workflow with payment enabled where appropriate or without it."},{question:"Does every booking system connect to Google Calendar?",answer:"No. Check whether the specific system supports and has configured that connection before relying on it."}],
  },
  {
    slug: "website-builder-with-crm-guide", path: "/guides/website-builder-with-crm-guide", title: "Website Builder with CRM: What Service Businesses Actually Need", h1: "Website builder with CRM: what service businesses actually need", description: "Learn what a website with CRM should mean for a service business, including contact continuity, booking history, notes, tags, and payment records.", publishedAt: "2026-09-08", category: "Guide", primaryCategory: "CRM", topics: ["CRM", "Websites"], excerpt: "A grounded checklist for evaluating a website builder with CRM when your work begins with a customer-facing website.", searchIntent: "website builder with CRM",
    sections: [
      {title:"What a website with CRM should mean", paragraphs:["A website with CRM should connect what a visitor does publicly with the customer information the business uses privately. The important question is not whether a product has a CRM label. It is whether a person can move from website activity to a useful, understandable client record without manual copying.","For a service business, that continuity often begins with a booking or request. The record should remain useful after the first interaction, not disappear when the form is submitted."]},
      {title:"The records worth checking", paragraphs:["Look for customer and contact records that preserve booking history, notes, and tags. Where payments are enabled, payment status and history should be available in the appropriate context. These details help a team recognize the customer and understand the relationship before the next appointment.","Also check how easy it is to correct a record, find a returning client, and see the relationship between a public website action and the operational work that follows."] , checklist:["Customer records connect to bookings", "Notes and tags are available where the workflow needs them", "Payment status is visible when payments are enabled", "The team can find history without exporting data"], table:{caption:"Core records in a connected service workflow",headers:["Record","Useful context"],rows:[["Client","Contact details, notes and tags"],["Booking","Service, time and appointment history"],["Payment","Status and history when payments are enabled"]]}},
      {title:"Service-business CRM is not a sales pipeline", paragraphs:["A salon, studio, or groomer usually needs continuity around appointments and relationships. That is different from a lead-scoring and outbound-sales CRM built around prospect stages, campaigns, and pipeline forecasting. OneStudio is positioned around the service-business workflow, not as a lead-scoring or outbound sales CRM.","A separate sales tool may still make sense for a business with a complex sales team. The right choice depends on whether the core problem is appointment operations or a dedicated sales process."], subsections:[{title:"When a service-business model fits",paragraphs:["Choose this model when appointments, returning customers, notes, and operational history are the center of the work."]},{title:"When a sales CRM may fit better",paragraphs:["Consider a dedicated sales platform when a team primarily manages prospect stages, outbound activity, and long sales cycles."]}]},
      {title:"How the public website connects to operations", paragraphs:["Evaluate the complete path: a visitor reaches the website, chooses an action, creates or updates a client record, and leaves the team with a clear next step. [[OneStudio CRM|/features/crm]] is designed around that connected context. Pair it with [[online booking|/features/online-booking]] when appointments are central, then review the relevant [[solutions|/solutions]] and [[pricing|/pricing]]."]},
      {title:"A practical evaluation checklist", paragraphs:["Before choosing a system, test it with a realistic customer journey rather than a feature list. Create a booking, find the client record, add a note, review the history, and check what happens when a payment is enabled. If the workflow feels fragmented in the test, it will probably feel fragmented on a busy day."], numberedList:["Create a realistic test booking from the public website.","Find the resulting client record and add a useful note.","Review booking history and payment context where enabled.","Repeat the flow as a returning customer."]}
    ], relatedLinks:[{label:"CRM",href:"/features/crm"},{label:"Online Booking",href:"/features/online-booking"},{label:"Solutions",href:"/solutions"}],
  },
  {
    slug:"beauty-salon-website-booking-guide", path:"/guides/beauty-salon-website-booking-guide", title:"What a Beauty Salon Website Needs to Turn Visits into Bookings", h1:"What a beauty salon website needs to turn visits into bookings", description:"A salon-specific guide to service menus, specialists, visual proof, online booking, client history, mobile experience, and custom domains.", publishedAt:"2026-09-08", category:"Guide", primaryCategory:"Marketing", topics:["Marketing", "SEO", "Websites"], excerpt:"Build a beauty salon website that answers practical questions and gives visitors a clear path to book.", searchIntent:"beauty salon website with online booking",
    sections:[
      {title:"Start with a clear service menu", paragraphs:["A salon visitor should quickly understand what is available. Show services in a structure that matches how people think, with pricing and duration where configured. If a service depends on a specialist, make that relationship clear rather than asking the visitor to discover it in a direct message."]},
      {title:"Show the people and the work", paragraphs:["Specialist information builds context, while a portfolio gives visual proof of the salon's direction. LUMEA Beauty is a real OneStudio example of a visual salon direction. GLOSS is another useful reference when a more editorial nail-studio mood is helpful. These examples are directions to inspect, not claims about customer results."]},
      {title:"Make availability and booking obvious", paragraphs:["The booking path should be visible in the first meaningful scroll and remain easy to use on a phone. A visitor should be able to choose a service and available time without being forced into DMs. [[Beauty salon solution|/solutions/beauty-salon-website]] shows the industry context, while [[online booking|/features/online-booking]] explains the connected booking capability."]},
      {title:"Keep the relationship after the visit", paragraphs:["A useful salon workflow keeps client records and history available for future appointments. Reminders and payment support can help where enabled and configured. [[CRM|/features/crm]] is relevant when the salon needs that continuity beyond the public page."]},
      {title:"Do not overlook the basics", paragraphs:["Use a custom domain when the salon is ready to publish, check every key action on mobile, and make the next step unambiguous. Review the [[LUMEA demo|/demos/lumea-beauty]], browse other [[demos|/demos]], and check [[pricing|/pricing]] before deciding what the site needs now."], template:{label:"Mobile launch review",content:"Open the published page on a phone. Check the service menu, specialist information, portfolio, booking action, confirmation state, and contact details before sharing the domain."}}
    ], relatedLinks:[{label:"Beauty salon solution",href:"/solutions/beauty-salon-website"},{label:"Online Booking",href:"/features/online-booking"},{label:"CRM",href:"/features/crm"},{label:"LUMEA demo",href:"/demos/lumea-beauty"}],
  },
  {
    slug: "client-notes-examples-service-business", path: "/guides/client-notes-examples-service-business",
    title: "Client Notes Examples: What to Write in a Service-Business CRM", h1: "Client Notes Examples for Service Businesses",
    description: "See practical client notes examples for service businesses, a concise note formula, and clear boundaries for sensitive information.",
    publishedAt: "2026-09-11", category: "Guide", primaryCategory: "CRM", topics: ["CRM", "Business"], excerpt: "Use factual, useful client notes without turning a CRM record into a private diary.", searchIntent: "client notes examples",
    sections: [
      { title: "The client note formula", paragraphs: ["A client note should save future work. Use context → service detail → preference → next useful action; include only the parts that matter.", "For example: Brand consultation completed. Client chose the minimal landing-page direction. Prefers morning review calls. Next action: send revised homepage outline Friday."] },
      { title: "Note, tag or status?", paragraphs: ["A note is narrative context about an interaction. A tag is a reusable label for filtering, such as Returning, Corporate or Referral. A status describes a broad operational state, such as New, Active, Inactive or Archived."], checklist: ["Write factual service context, not personality judgments", "Record a useful preference only when it affects delivery", "Add a next action when one exists", "Use a tag or status when that is the proper field"] },
      { title: "Examples that help the next interaction", paragraphs: ["A useful salon note can say: Haircut: prefers a softer shape around the face and minimal styling product. Next time: ask whether to keep the same length.", "For a photographer: Brand session: priority images are team portraits, product close-ups and three horizontal website banners. Client prefers clean, minimal styling.", "For a consultant: Client wants two clear options with trade-offs rather than a long list. Next review should focus on recommendation and rationale."], subsections: [{ title: "Issue resolution", paragraphs: ["Record the fact, action and outcome: Client reported that the delivered file link had expired. New link sent Sep 11. Confirmed access at 14:20. No further action."] }, { title: "Reschedules and cancellations", paragraphs: ["Keep it short: Sep 11 appointment moved to Sep 14 at 15:00 at the client’s request. Original slot released. New confirmation sent."] }] },
      { title: "What not to store casually", paragraphs: ["Avoid ordinary CRM notes for passwords, card numbers or security codes, government IDs without a compliant need, unnecessary medical or highly sensitive information, gossip, speculation, private conversations that do not affect delivery, or insulting labels. Minimize first and secure what remains.", "Do not store door codes, alarm codes, safe combinations or other high-risk credentials in a general client note unless a system is specifically designed and secured for that purpose."] },
      { title: "How OneStudio fits", paragraphs: ["OneStudio’s public pages describe client records with contact details, interaction and booking history, notes, tags and archive or status context. Notes add concise operational context around that history; they are not a substitute for specialist medical, clinical or credential-storage systems."], links: [{ label: "Explore CRM", href: "/features/crm" }, { label: "Read the privacy policy", href: "/privacy" }] },
    ], relatedLinks: [{ label: "Client database template", href: "/guides/client-database-template-service-business" }, { label: "Client reactivation templates", href: "/guides/client-reactivation-message-templates" }, { label: "CRM", href: "/features/crm" }],
    faq: [{ question: "What should I write in client notes?", answer: "Write context that helps future service: what happened, an important service detail, a useful preference and the next action." }, { question: "What is the difference between a note and a tag?", answer: "A tag is a reusable category for filtering. A note is specific context about an interaction or client." }],
  },
  {
    slug: "appointment-booking-form-template", path: "/guides/appointment-booking-form-template",
    title: "Appointment Booking Form Template: Fields, Examples and Checklist", h1: "Appointment Booking Form Template: What to Include and What to Leave Out",
    description: "Build a shorter appointment booking form with essential fields, clear live-booking and request-form examples, and a mobile checklist.",
    publishedAt: "2026-09-11", category: "Guide", primaryCategory: "Booking", topics: ["Booking", "Websites", "Business"], excerpt: "Ask only for information needed to reserve or request an appointment.", searchIntent: "appointment booking form template",
    sections: [
      { title: "First choose the type of form", paragraphs: ["A live-slot booking lets a client choose a service and an actually available time; an instant-confirmation workflow can then confirm the appointment. A booking request collects preferences, but the time is not guaranteed until the business reviews and confirms it.", "Do not label a request form ‘Book now’ when the client is really asking the business to confirm later."], table: { caption: "Two different booking experiences", headers: ["Live-slot booking", "Booking request"], rows: [["Service → available time → contact details → confirm", "Service → preferred date/time → contact details → request → staff confirmation"], ["Confirmed only when the workflow confirms it", "Clearly state that the request is not confirmed yet"]] } },
      { title: "Minimal live booking form template", paragraphs: ["For many service businesses, service, relevant staff or resource preference, available date and time, name, an email or phone contact, an optional note and any genuinely needed policy acknowledgement are enough."], numberedList: ["Choose a service", "Choose an available date and time", "Enter name and the contact method used for confirmation", "Add a short optional note", "Confirm the appointment"], template: { label: "Copyable live-booking structure", content: "What would you like to book?\n[Service selector]\n\nChoose a date and available time\n[Available dates] [Available slots]\n\nYour name\n[Name]\n\nEmail\n[Email]\n\nAnything we should know? (optional)\n[Short note]\n\n[Confirm appointment]" } },
      { title: "Minimal booking request form template", paragraphs: ["Make uncertainty explicit. The confirmation state should say: Thanks. Your request has been received. This is not a confirmed appointment yet. We will confirm the time using the stated channel."], template: { label: "Copyable request-form structure", content: "Service needed\n[Service selector]\n\nPreferred date and time window\n[Date] [Morning / Afternoon / Evening]\n\nAlternative date/time (optional)\n[Date / time]\n\nName and contact\n[Name] [Email] [Phone]\n\nShort request note\n[Text]\n\n[Request appointment]" } },
      { title: "What belongs before booking", paragraphs: ["Ask for service, date or time, name, at least one contact method and a short operational note. Ask for staff, location, policy or payment information only if it changes the booking. Payments belong in the flow only where enabled, with the amount, timing and cancellation or refund terms made clear.", "Do not collect long intake history, unnecessary demographic questions, broad marketing preferences, sensitive health or identity information, passwords, payment-card details or security credentials in an ordinary booking form."], checklist: ["Required fields are truly required", "Optional fields are visibly optional", "The final state says confirmed, pending approval or awaiting payment accurately", "The policy is linked and readable"] },
      { title: "How OneStudio fits", paragraphs: ["OneStudio’s public pages verify services and duration, working hours and availability, staff or resources, free appointment times, online booking, client history, payments where enabled, and confirmations or reminders. They do not verify a general-purpose arbitrary custom-form-field builder or universal staff/resource-combination logic."], links: [{ label: "Online Booking", href: "/features/online-booking" }, { label: "Privacy", href: "/privacy" }] },
    ], relatedLinks: [{ label: "How online booking works", href: "/guides/how-online-booking-works-for-service-businesses" }, { label: "Online Booking", href: "/features/online-booking" }, { label: "Features", href: "/features" }],
    faq: [{ question: "What fields should an appointment booking form include?", answer: "Usually service, available date and time, client name, at least one contact method and a short optional note." }, { question: "What is the difference between a booking form and a request form?", answer: "A booking form can confirm an actual slot. A request form collects preferences and still requires business approval." }],
  },
  {
    slug: "client-database-template-service-business", path: "/guides/client-database-template-service-business",
    title: "Client Database Template for Service Businesses: Fields + Examples", h1: "Client Database Template for Service Businesses",
    description: "Build a practical client database for a service business with client and appointment tables, privacy boundaries, and a migration checklist.",
    publishedAt: "2026-09-11", category: "Guide", primaryCategory: "CRM", topics: ["CRM", "Business"], excerpt: "Start with a client table and an appointments table instead of one overloaded spreadsheet.", searchIntent: "client database template",
    sections: [
      { title: "Start with two connected tables", paragraphs: ["A useful service-business database separates the client record from appointments. One client can have many appointments; each appointment belongs to one client. This avoids repeating contact details in every row and preserves a useful history."], table: { caption: "Practical starting schema", headers: ["Clients table", "Appointments table"], rows: [["Client ID, name, email, phone, preferred contact", "Appointment ID, client ID, service, date/time, status"], ["Useful notes, tags and consent or preference context where appropriate", "Provider or location where relevant, operational note, payment status where enabled"]] } },
      { title: "Fields worth keeping", paragraphs: ["Keep fields that change service delivery or help an authorized teammate continue the relationship: contact details, service preferences, booking history, factual notes and next actions. A service-business CRM is not a universal enterprise sales CRM; it should support appointments and relationships rather than pretend every business needs a sales pipeline."], checklist: ["Use a stable client ID", "Keep booking records separate from client details", "Use tags for repeatable labels", "Record notes neutrally and only when useful"] },
      { title: "Privacy and retention", paragraphs: ["Do not put card numbers, security codes, passwords or payment secrets into a client database. Collect only what is needed, restrict access to authorized people, and define retention or deletion practices that match your obligations. Stored email or phone information is not automatic permission for marketing." ] },
      { title: "Move from a spreadsheet to CRM", paragraphs: ["A spreadsheet can be a good starting point, but manual copying becomes fragile as bookings grow."], numberedList: ["Remove duplicate clients and choose a stable identifier", "Separate client details from appointment rows", "Move only useful, permitted information", "Define note, tag and status conventions", "Test a new booking and a returning client workflow", "Set access and retention rules before importing more data"] },
      { title: "How OneStudio fits", paragraphs: ["OneStudio is positioned around service-business client continuity: contacts, booking history, notes, tags and payments where enabled. It is not presented as a universal enterprise sales CRM."], links: [{ label: "CRM", href: "/features/crm" }, { label: "Online Booking", href: "/features/online-booking" }] },
    ], relatedLinks: [{ label: "Client notes examples", href: "/guides/client-notes-examples-service-business" }, { label: "Website builder with CRM", href: "/guides/website-builder-with-crm-guide" }, { label: "CRM", href: "/features/crm" }],
    faq: [{ question: "What should a client database include?", answer: "Start with client contact details and a separate appointment table linked by a client ID." }, { question: "Should I store payment details in a client database?", answer: "Do not store card numbers, security codes or payment secrets in ordinary client records." }],
  },
  {
    slug: "appointment-reschedule-message-templates", path: "/guides/appointment-reschedule-message-templates",
    title: "Appointment Reschedule Message Templates: 14 Examples", h1: "Appointment Reschedule Message Templates for Clients and Businesses",
    description: "Use clear, considerate appointment reschedule message templates that distinguish a proposed new time from a confirmed replacement.",
    publishedAt: "2026-09-11", category: "Guide", primaryCategory: "Booking", topics: ["Booking", "Business"], excerpt: "Keep the original appointment, proposed replacement and confirmation state clear.", searchIntent: "appointment reschedule message template",
    sections: [
      { title: "What a reschedule message must say", paragraphs: ["A clear message identifies the original appointment, says why a change is needed when appropriate, offers a replacement time or asks for availability, and explains whether the replacement is proposed or confirmed. A proposed time is not confirmed until the client accepts."] },
      { title: "Templates for a business-initiated change", paragraphs: ["Use a concise, factual tone and give the client a simple next step."], subsections: [{ title: "Proposed replacement", paragraphs: ["Hi [Name], we need to move your [Service] appointment on [Old date/time]. We can offer [New date/time]. Please reply to confirm it works, or send another time that suits you. The new time is not confirmed until we hear from you."] }, { title: "Confirmed replacement", paragraphs: ["Hi [Name], your [Service] appointment has been moved from [Old date/time] to [New date/time]. This new time is confirmed. Please reply if anything has changed."] }, { title: "Short-notice change", paragraphs: ["Hi [Name], we are sorry for the short notice. We need to reschedule today’s [Service] appointment at [Old time]. We can offer [Option 1] or [Option 2]. Please tell us which works for you."] }] },
      { title: "Templates for a client request", paragraphs: ["Acknowledge the request without silently assuming a replacement slot is available."], subsections: [{ title: "Availability request", paragraphs: ["Hi [Name], thanks for letting us know. We can help you move your [Service] appointment from [Old date/time]. What days or time windows work best for you?"] }, { title: "Requested time available", paragraphs: ["Hi [Name], [Requested date/time] is available. Reply YES to confirm the change; we will release the original appointment after confirmation."] }, { title: "Requested time unavailable", paragraphs: ["Hi [Name], [Requested date/time] is no longer available. We can offer [Option 1] or [Option 2]. Let us know which you prefer."] }] },
      { title: "Before you send", paragraphs: ["Check the service, old appointment, replacement time, time zone if relevant, location or booking link, and whether the new time is only proposed. Avoid implying a confirmed appointment when the client still needs to accept."], checklist: ["State the old appointment", "State the new proposal or confirmed replacement", "Give a clear response path", "Update the booking record after confirmation"] },
      { title: "How OneStudio fits", paragraphs: ["OneStudio can be described through its current booking, calendar and notification behavior where configured. Its public pages do not verify a dedicated automatic reschedule-message trigger, so use these templates as an operational communication standard rather than a claim of automatic sending."], links: [{ label: "Online Booking", href: "/features/online-booking" }, { label: "How online booking works", href: "/guides/how-online-booking-works-for-service-businesses" }] },
    ], relatedLinks: [{ label: "Online Booking", href: "/features/online-booking" }, { label: "Appointment booking form template", href: "/guides/appointment-booking-form-template" }, { label: "Pricing", href: "/pricing" }],
    faq: [{ question: "Should a proposed replacement time be called confirmed?", answer: "No. Call it proposed until the client accepts and the booking is updated." }, { question: "What should a reschedule message include?", answer: "The original appointment, the proposed or confirmed replacement, and a clear next step." }],
  },
  {
    slug: "client-reactivation-message-templates", path: "/guides/client-reactivation-message-templates",
    title: "Client Reactivation Message Templates: 12 Win-Back Examples", h1: "Client Reactivation Message Templates for Lapsed Clients",
    description: "Use permission-aware client reactivation templates with a practical expected-return window, clear value, and opt-out language.",
    publishedAt: "2026-09-11", category: "Guide", primaryCategory: "Marketing", topics: ["Marketing", "CRM", "Booking", "Business"], excerpt: "Reconnect with lapsed clients only where contact is permitted and useful.", searchIntent: "client reactivation email template",
    sections: [
      { title: "Start with permission, not a campaign", paragraphs: ["A stored email address or phone number is not automatic permission to send marketing. Contact only people you are permitted to contact, follow applicable rules, make opt-out easy and honor it. Choose a lapsed-client window based on the normal return cycle for the service rather than a universal number."] },
      { title: "Simple reactivation templates", paragraphs: ["Keep the message specific, helpful and easy to decline."], subsections: [{ title: "Gentle check-in", paragraphs: ["Hi [Name], it has been a little while since your last [Service]. If you would like to book again, you can choose a time here: [Booking link]. If you do not want these reminders, reply STOP or use [opt-out]."] }, { title: "Seasonal reminder", paragraphs: ["Hi [Name], [Season or milestone] is a useful time to plan your next [Service]. If it is relevant, you can see available times here: [Booking link]. Prefer not to receive these messages? Use [opt-out]."] }, { title: "Preference reminder", paragraphs: ["Hi [Name], we want to make sure our updates still suit you. You can update preferences or opt out here: [Preference / opt-out link]. We will not treat silence as new consent."] }] },
      { title: "Make the offer and timing honest", paragraphs: ["Do not invent urgency, discounts or a client need. If you make an offer, state its terms, duration and eligibility clearly. A reactivation message should be relevant to the expected return window and should not pressure someone who has not chosen to hear from you."], checklist: ["Confirm permitted-contact status", "Use a realistic expected-return window", "State value or next step clearly", "Include an opt-out or preference route", "Stop when the person opts out or rebooks"] },
      { title: "What OneStudio claims can support", paragraphs: ["OneStudio’s public pages support client records, booking history, online booking and notifications where configured. They do not verify an automatic lapsed-client trigger or an automated win-back sequence. Treat these templates as copy a business may use in a compliant workflow, not proof of a built-in campaign automation."], links: [{ label: "CRM", href: "/features/crm" }, { label: "Online Booking", href: "/features/online-booking" }, { label: "Privacy", href: "/privacy" }] },
    ], relatedLinks: [{ label: "Client notes examples", href: "/guides/client-notes-examples-service-business" }, { label: "Client database template", href: "/guides/client-database-template-service-business" }, { label: "CRM", href: "/features/crm" }],
    faq: [{ question: "When is a client considered lapsed?", answer: "Use the normal return cycle for your service; there is no universal lapsed-client interval." }, { question: "Can I use a stored email for reactivation marketing?", answer: "Only where contact is permitted. A stored address alone is not automatic marketing permission." }],
  },
] as const satisfies readonly GuideArticle[];
