import Link from "next/link";
import PublicCustomBlock from "@/components/public/PublicCustomBlock";
import PublicRichHeading from "@/components/public/PublicRichHeading";
import PublicRichText from "@/components/public/PublicRichText";
import type { PublicSiteData, PublicSitePage } from "@/lib/public-site/types";

export default function CashPathCustomPage({ site, page, basePath }: { site: PublicSiteData; page: PublicSitePage; basePath: string }) {
  const pageHref = (slug: string) => `${basePath === "/" ? "" : basePath}/p/${slug}`;
  return <main lang="en" className="min-h-screen bg-[#f7f5ef] text-[#182b29]"><header className="border-b border-[#182b29]/10 bg-[#f7f5ef]"><div className="mx-auto flex min-h-20 w-[calc(100%_-_40px)] max-w-7xl flex-wrap items-center justify-between gap-4 py-4"><Link href={basePath} className="text-2xl font-semibold tracking-tight">Cash<span className="text-[#167a6a]">Path</span></Link><nav className="flex flex-wrap items-center gap-5 text-sm font-semibold"><Link href={basePath}>Home</Link><Link href={`${basePath}#how`}>How It Works</Link><Link href={pageHref("faq")}>FAQ</Link><Link href={pageHref("about")}>About</Link><Link href={`${basePath}#request`} className="rounded-lg bg-[#182b29] px-4 py-2 text-[#f7f5ef]">Start Your Request</Link></nav></div></header><section className="border-b border-[#182b29]/10 px-5 py-20 sm:py-28"><div className="mx-auto max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[.22em] text-[#6b8f35]">{page.eyebrow}</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-tight sm:text-7xl"><PublicRichHeading value={page.title} /></h1><PublicRichText value={page.intro} className="mt-6 max-w-3xl text-lg leading-8 text-[#182b29]/75" /></div></section><section className="mx-auto max-w-5xl px-5 py-16">{(page.blocks ?? []).filter((block) => block.is_visible !== false).map((block) => <PublicCustomBlock key={block.id} block={block} />)}</section><footer className="bg-[#182b29] px-5 py-12 text-[#f7f5ef]"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-3"><div><Link href={basePath} className="text-2xl font-semibold">Cash<span className="text-[#c8ef22]">Path</span></Link><p className="mt-4 text-sm leading-6 text-white/70">CashPath is not a lender and does not make credit decisions.</p></div><div><b>Explore</b><div className="mt-4 grid gap-2 text-sm text-white/75">{[["About", "about"], ["Contact", "contact"], ["FAQ", "faq"], ["Rates & Fees", "rates-fees"], ["Responsible Lending", "responsible-lending"]].map(([label, slug]) => <Link key={slug} href={pageHref(slug)}>{label}</Link>)}</div></div><div><b>Information</b><div className="mt-4 grid gap-2 text-sm text-white/75">{[["Privacy Policy", "privacy-policy"], ["Terms of Use", "terms-of-use"], ["E-Consent", "e-consent"], ["Advertiser Disclosure", "advertiser-disclosure"], ["Do Not Sell or Share My Personal Information", "do-not-sell-share"], ["Disclaimer", "disclaimer"]].map(([label, slug]) => <Link key={slug} href={pageHref(slug)}>{label}</Link>)}</div></div></div><p className="mx-auto mt-10 max-w-7xl text-xs text-white/55">© {new Date().getFullYear()} CashPath</p></footer></main>;
}
