"use client";
import { Children, isValidElement, type ReactNode, useState } from "react";
import Link from "next/link";
import PublicCustomBlock from "@/components/public/PublicCustomBlock";
import type { PremiumTemplatePublicHomeRendererProps } from "@/lib/public-site/premium-template-runtime-adapter";
import { resolvePawhausGroomingStudioContent } from "@/lib/public-site/pawhaus-grooming-studio-premium-template-content";
import { createPawhausGroomingStudioRenderPlan } from "@/lib/public-site/pawhaus-grooming-studio-render-plan";
import styles from "./PawhausGroomingStudioSite.module.css";
function Media({ src, label }: { src?: string; label: string }) { return <div className={styles.media} style={{ backgroundImage: src ? `url(${src})` : undefined }} aria-label={label} />; }
function Composition({ site, children }: Pick<PremiumTemplatePublicHomeRendererProps, "site"> & { children: ReactNode }) { const native = new Map<string, ReactNode>(); for (const child of Children.toArray(children)) if (isValidElement<{ "data-editor-anchor"?: string }>(child)) { const id = child.props["data-editor-anchor"]; if (id) native.set(String(id), child); } return <>{createPawhausGroomingStudioRenderPlan(site.content).map((item) => item.kind === "native" ? <div key={item.key}>{native.get(item.sectionId)}</div> : <PublicCustomBlock key={item.key} block={item.block} services={site.services} bookingHref="#booking" />)}</>; }
export default function PawhausGroomingStudioSite({ site, basePath }: PremiumTemplatePublicHomeRendererProps) { const c = resolvePawhausGroomingStudioContent(site.content); const en = site.business.locale === "en"; const [open, setOpen] = useState(false); const [sent, setSent] = useState(false); return <main className={styles.page} lang={en ? "en" : "ru"}>
  <header className={styles.header}><a className={styles.logo} href="#top"><b>{c.brand}</b><small>{c.brandNote}</small></a><button className={styles.menu} onClick={() => setOpen(!open)} aria-expanded={open}>{c.menuLabel} <span>☰</span></button><nav className={open ? styles.navOpen : ""}>{c.navigation.map((item) => <a key={item.text} href={item.text} onClick={() => setOpen(false)}>{item.title}</a>)}</nav><div className={styles.tools}><span><Link href={basePath.replace(/\/en$/, "")}>RU</Link> / <Link href={`${basePath.replace(/\/en$/, "")}/en`}>EN</Link></span><a className={styles.button} href="#booking">{c.headerCta.title}</a></div></header>
  <Composition site={site}>
    <section id="top" data-editor-anchor="hero" className={styles.hero}><div className={styles.heroCopy}><p className={styles.kicker}>{c.hero.eyebrow}</p><h1>{c.hero.title}</h1><p className={styles.lead}>{c.hero.text}</p><div className={styles.actions}><a className={styles.button} href="#booking">{c.hero.primaryLabel} ↗</a><a className={styles.textButton} href="#services">{c.hero.secondaryLabel} ↓</a></div><div className={styles.stats}><span>{c.hero.statOne}</span><span>{c.hero.statTwo}</span><span>{c.hero.statThree}</span></div></div><div className={styles.heroMedia}><Media src={c.hero.image} label="PAWHAUS hero photography" /><i>GOOD<br/>DOGS<br/>GOOD<br/>DAYS</i></div></section>
    <section id="services" data-editor-anchor="services" className={styles.section}><div className={styles.sectionHead}><p className={styles.kicker}>01 / SERVICES</p><h2>{en ? <>Care that<br/><em>you can feel.</em></> : <>Уход, который<br/><em>чувствуется.</em></>}</h2></div><div className={styles.serviceGrid}>{c.services.map((x, i) => <article className={styles.service} key={x.title}><Media src={x.image} label={`Service ${i + 1} photography`} /><span>0{i + 1}</span><h3>{x.title}</h3><p>{x.text}</p><footer><small>{x.meta}</small><b>{x.price}</b></footer></article>)}</div></section>
    <section id="before-after" data-editor-anchor="before-after" className={`${styles.section} ${styles.dark}`}><div className={styles.feature}><div className={styles.beforeAfterMedia}><Media src={c.beforeAfter.beforeImage} label="Editable before photography"/><Media src={c.beforeAfter.afterImage} label="Editable after photography"/></div><div><p className={styles.kicker}>02 / BEFORE · AFTER</p><h2>{c.beforeAfter.title}</h2><p>{c.beforeAfter.text}</p><span className={styles.pill}>{c.beforeAfter.meta}</span></div></div></section>
    <section id="groomers" data-editor-anchor="groomers" className={styles.section}><div className={styles.sectionHead}><p className={styles.kicker}>03 / THE HOUSE</p><h2>{en ? <>People pets<br/><em>trust with their paws.</em></> : <>Люди, которым<br/><em>доверяют лапки.</em></>}</h2></div><div className={styles.people}>{c.groomers.map((x) => <article key={x.title}><Media src={x.image} label={`${x.title} photography`} /><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
    <section id="process" data-editor-anchor="process" className={styles.section}><p className={styles.kicker}>04 / PROCESS</p><h2>{en ? <>No rush.<br/><em>Just four simple steps.</em></> : <>Никакой суеты.<br/><em>Только четыре шага.</em></>}</h2><div className={styles.steps}>{c.process.map((x, i) => <article key={x.title}><b>0{i + 1}</b><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
    <section id="packages" data-editor-anchor="packages" className={`${styles.section} ${styles.lime}`}><p className={styles.kicker}>05 / PACKAGES</p><h2>{en ? <>Build your<br/>care ritual.</> : <>Соберите свой<br/>ритуал ухода.</>}</h2><div className={styles.packages}>{c.packages.map((x) => <article key={x.title}><Media src={x.image} label={`${x.title} photography`} /><h3>{x.title}</h3><p>{x.text}</p><strong>{x.price}</strong><a href="#booking">{en ? "Choose" : "Выбрать"} ↗</a></article>)}</div></section>
    <section id="gallery" data-editor-anchor="gallery" className={styles.section}><div className={styles.sectionHead}><p className={styles.kicker}>06 / GALLERY</p><h2>{c.gallery.title}</h2><p>{c.gallery.text}</p></div><div className={styles.gallery}>{c.gallery.images.map((image, i) => <Media key={`${image}-${i}`} src={image} label={`PAWHAUS gallery photography ${i + 1}`} />)}</div></section>
    <section id="testimonials" data-editor-anchor="testimonials" className={`${styles.section} ${styles.testimonials}`}><p className={styles.kicker}>07 / KIND WORDS</p><h2>{en ? <>Happy<br/><em>tails tell the story.</em></> : <>Счастливые<br/><em>хвосты говорят.</em></>}</h2><div className={styles.quoteGrid}>{c.testimonials.map((x) => <blockquote key={x.title}><span>“</span><p>{x.text}</p><footer><b>{x.title}</b><small>{x.meta}</small></footer></blockquote>)}</div></section>
    <section id="booking" data-editor-anchor="booking" className={`${styles.section} ${styles.booking}`}><div><p className={styles.kicker}>08 / BOOKING</p><h2>{c.booking.title}</h2><p>{c.booking.text}</p></div><form onSubmit={(e) => { e.preventDefault(); setSent(true); }}>{sent ? <div className={styles.success}>{en ? "Request received ✦" : "Заявка принята ✦"}<small>{en ? "We’ll be in touch soon." : "Мы скоро свяжемся с вами."}</small></div> : <>{c.booking.fields.map((field) => <input key={field} placeholder={field} required />)}<button className={styles.button}>{en ? "Send request" : "Отправить заявку"} ↗</button></>}</form></section>
    <section id="faq" data-editor-anchor="faq" className={styles.section}><p className={styles.kicker}>09 / FAQ</p><h2>{en ? "Frequently asked questions." : "Частые вопросы."}</h2><div className={styles.faq}>{c.faq.map((x) => <details key={x.title}><summary>{x.title}<span>+</span></summary><p>{x.text}</p></details>)}</div></section>
    <section id="contact" data-editor-anchor="contact" className={`${styles.contact} ${styles.section}`}><div><p className={styles.kicker}>10 / FIND US</p><h2>{c.contact.title}</h2><p>{c.contact.text}</p></div><a className={styles.button} href="#top">{c.contact.meta} ↗</a></section>
    <footer data-editor-anchor="footer" className={styles.footer}><div className={styles.footerTop}><div className={styles.footerBrand}><a className={styles.logo} href="#top"><b>{c.footer.title}</b><small>{c.brandNote}</small></a><p>{c.footer.text}</p><a className={`${styles.button} ${styles.footerCta}`} href={c.footer.cta.text}>{c.footer.cta.title} ↗</a></div><nav className={styles.footerNav} aria-label={en ? "Footer navigation" : "Навигация в подвале"}>{c.footer.navigation.map((item) => <a key={item.text} href={item.text}>{item.title}</a>)}</nav><div className={styles.footerContact}><p className={styles.footerLabel}>{en ? "Visit us" : "Ждём вас"}</p><strong>{c.footer.contact.title}</strong><span>{c.footer.contact.text}</span></div></div><div className={styles.footerBottom}><small>{c.footer.copyright}</small><small>{c.footer.credit}</small></div></footer>
  </Composition></main>; }
