import { pricing as englishPricing } from "../en/pricing";

export const pricing = {
  ...englishPricing,
  hero: { eyebrow: "PRECIOS", title: ["Elige un plan", "para tus necesidades"], lead: "Planes para distintas necesidades y presupuestos." }, plansHeading: "Planes de OneStudio", plansSupporting: "14 días gratis en los planes de OneStudio.", planLabels: { included: "Incluido en este plan", storage: "Media" },
  plans: {
    site: { ...englishPricing.plans.site, description: "Para un sitio web, un portafolio y una presencia empresarial sencilla en internet.", features: ["Tu propio sitio web", "Editor visual", "Formularios de contacto y consultas", "Portafolio / galerías", "Analítica básica", "10 GB de tráfico mensual"], cta: "Crear un sitio" },
    business: { ...englishPricing.plans.business, description: "Todo lo de Site más reservas, clientes, pagos y procesos de trabajo.", features: ["Todo lo de Site", "Reservas online", "Agenda", "Servicios y precios", "Personal / recursos", "CRM / base de clientes", "Pagos online / depósitos", "Notificaciones / recordatorios", "100 GB de tráfico mensual"], cta: "Empezar", badge: "Más popular" },
    pro: { ...englishPricing.plans.pro, description: "Todo lo de Business más personal / recursos, media y tráfico adicionales.", features: ["Todo lo de Business", "Más personal / recursos", "Hasta 3 sitios web", "100 GB de media", "500 GB de tráfico mensual"], cta: "Elegir Pro" },
  },
  comparison: { ...englishPricing.comparison, title: "Especificaciones técnicas", sectionTitles: { websiteDesign: "SITIO WEB Y DISEÑO", storageTraffic: "ALMACENAMIENTO Y TRÁFICO", clientWork: "TRABAJO CON CLIENTES", teamResources: "EQUIPO Y RECURSOS" }, rowLabels: { websiteCount: "Número de sitios web", ssl: "SSL / conexión segura", hosting: "Alojamiento web", mobile: "Diseño adaptado a móviles", visualEditor: "Editor visual", basicTemplates: "Plantillas básicas", basicBlocks: "Bloques básicos", imageOptimization: "Optimización de imágenes", media: "Media", monthlyTraffic: "Tráfico mensual", contactForms: "Formularios de contacto y consultas", onlineBooking: "Reservas online", schedule: "Agenda", services: "Servicios y precios", crm: "CRM / base de clientes", payments: "Pagos online / depósitos", notifications: "Notificaciones / recordatorios", staffResources: "Personal / recursos" }, valueLabels: { standard: "Nivel estándar", more: "Más personal / recursos" }, yesLabel: "Incluido en el plan", noLabel: "No incluido en el plan", priceUnitLabel: "/ mes", annualPriceLabel: "/ mes con facturación anual" },
  billing: { monthly: "Mes", annual: "Año", priceUnit: "/ mes", annualNote: "hasta un 68 % menos", annualTotal: "al año", ariaLabel: "Periodo de facturación" },
  design: { eyebrow: "PREMIUM DESIGN LIBRARY", title: "Premium Design Library", body: "Desbloquea la biblioteca completa de bloques premium, efectos interactivos y animaciones de OneStudio.", priceSuffix: "pago único", tagline: "Una compra. Toda la biblioteca.", note: "Premium Design Library se compra por separado y no está incluida en los planes ni en el periodo gratuito de 14 días.", cta: "Abrir la biblioteca", items: [{ label: "Premium Blocks", description: "Bloques premium para construir páginas y secciones expresivas." }, { label: "Premium Effects", description: "Efectos interactivos para el acento visual adecuado." }, { label: "Premium animations", description: "Animaciones y componentes visuales interactivos de OneStudio." }] },
  faq: { eyebrow: "FAQ DE PLANES", title: "Algunas respuestas rápidas sobre los planes.", more: "Más respuestas →", compactAriaLabel: "Preguntas sobre los planes", items: [{ question: "¿Hay un periodo de prueba gratuito?", answer: "Sí. Puedes probar gratis los planes de OneStudio durante 14 días." }, { question: "¿Puedo conectar mi propio dominio?", answer: "Sí. Tu propio dominio está disponible en los planes de pago de OneStudio." }, { question: "¿Qué ocurre si el sitio supera su límite de tráfico?", answer: "OneStudio no apaga el sitio inmediatamente por un exceso puntual. Si el tráfico alto se vuelve habitual, puedes cambiar de plan o añadir más tráfico." }, { question: "¿Puedo cambiar de plan más adelante?", answer: "Sí. Puedes cambiar de plan cuando cambien las necesidades de tu negocio." }] },
} as const;
