import { website as englishWebsite } from "../en/website";

export const website = {
  ...englishWebsite,
  hero: { eyebrow: "SITIO WEB LLAVE EN MANO", title: "Sitio web llave en mano", priceLabel: "desde €249", projectUnit: "proyecto", lead: "¿No quieres crear el sitio por tu cuenta? Lo crearemos, configuraremos y lanzaremos en OneStudio por ti.", priceNote: "El precio depende de la estructura, el diseño y las funciones que necesites. Antes de empezar recibirás un precio fijo para el proyecto.", cta: "Hablar del proyecto", ctaNote: "Te propondremos el siguiente paso" },
  included: { eyebrow: "QUÉ INCLUYE", title: "Todo lo necesario para lanzar", lead: "Nos ocupamos de crear el sitio y de la parte técnica de publicarlo en OneStudio.", items: [{ title: "Diseño", description: "Creamos una dirección visual alrededor de tu objetivo." }, { title: "Montaje de páginas", description: "Construimos la estructura y los bloques necesarios." }, { title: "Textos y fotografías", description: "Colocamos el contenido que nos proporciones en las páginas." }, { title: "Adaptación móvil", description: "Comprobamos el sitio en pantallas pequeñas." }, { title: "Conexión del dominio", description: "Conectamos tu dominio antes del lanzamiento." }, { title: "SEO básico", description: "Configuramos los metadatos principales de las páginas." }, { title: "Publicación", description: "Lanzamos el sitio terminado en OneStudio." }] },
  scope: { eyebrow: "QUÉ AFECTA AL PRECIO", title: "Un precio fijo para el alcance del proyecto", lead: "El precio depende de la estructura, el diseño y las funciones que necesites. Antes de empezar recibirás un precio fijo para el proyecto.", items: ["Número y estructura de páginas", "Diseño personalizado", "Premium Effects", "Reservas / funciones de negocio", "CRM / pagos / integraciones", "Varios idiomas", "Funciones no estándar", "Preparación del contenido"] },
  process: { eyebrow: "PROCESO", title: "De la conversación al lanzamiento", steps: [{ number: "01", title: "Hablamos", description: "Definimos el objetivo, la estructura y las funciones." }, { number: "02", title: "Fijamos el precio", description: "Acordamos un precio de proyecto antes de empezar." }, { number: "03", title: "Creamos", description: "Construimos las páginas, el diseño y las funciones necesarias." }, { number: "04", title: "Lanzamos", description: "Conectamos el dominio y publicamos el sitio." }] },
  showcase: { eyebrow: "PORTAFOLIO", title: "Nuestro trabajo", lead: "Sitios web creados y lanzados con OneStudio." },
  portfolio: { "sisters-studio": { projectType: "Proyecto de cliente", cta: "Abrir sitio", description: null, alt: null }, bembi: { projectType: "Proyecto de cliente", cta: "Abrir sitio", description: null, alt: null }, "noir-frame": { projectType: "OneStudio Original", cta: "Abrir sitio", description: "Un estudio fotográfico premium con visor de portafolio, recorrido 3D y before/after.", alt: "Estudio fotográfico NOIR FRAME luminoso" }, "velora-house": { projectType: "OneStudio Original", cta: "Abrir sitio", description: "Bodas, cenas privadas y eventos corporativos en tres salones únicos.", alt: "Salón de eventos VELORA HOUSE de noche" }, cashpath: { projectType: "Proyecto de cliente", cta: "Abrir sitio", description: "Un sitio claro y orientado al consumidor para explorar opciones de préstamos personales.", alt: "Sitio CashPath con opciones de préstamos personales" } },
} as const;
