import { contactTopicValues, type ContactTopicValue } from "../../config";

const topics = { platform: "Питання про OneStudio", website: "Сайт під ключ", pricing: "Тарифи та оплата", technical: "Технічне питання", other: "Інше" };
export const contact = {
  hero: { eyebrow: "КОНТАКТИ", title: "Зв’язатися з OneStudio", lead: "Розкажіть, що ви хочете створити, налаштувати або зрозуміти. Ми допоможемо обрати правильний напрям.", secondary: "Питання про OneStudio, сайт під ключ або допомога з вибором тарифу." },
  questionsTitle: "Про що можна написати", questions: ["OneStudio та можливості платформи", "Сайт під ключ", "Тарифи й оплата", "Технічні питання"], directContactLabel: "ЕЛЕКТРОННА ПОШТА",
  form: { title: "Розкажіть про задачу", description: "Заповніть форму, щоб ми зрозуміли контекст і запропонували наступний крок.", nameLabel: "Ім’я", namePlaceholder: "Як до вас звертатися?", emailLabel: "Email", emailPlaceholder: "you@example.com", phoneLabel: "Телефон", phoneOptional: "необов’язково", phonePlaceholder: "+...", topicLabel: "Тема", topicPlaceholder: "Оберіть тему", messageLabel: "Повідомлення", messagePlaceholder: "Розкажіть, що ви хочете створити або дізнатися", consentBefore: "Я погоджуюся на обробку моїх даних відповідно до ", consentLink: "Політики конфіденційності", consentAfter: ".", submit: "Надіслати повідомлення", submitting: "Надсилаємо…", successTitle: "Повідомлення надіслано", successDescription: "Дякуємо. Ми отримали ваше повідомлення і зв’яжемося з вами.", unavailable: "Форма тимчасово недоступна. Напишіть нам напряму:", devUnavailable: "Надсилання форми ще не підключене в цьому середовищі. Дані не було надіслано.", errors: { nameRequired: "Введіть ім’я.", nameInvalid: "Ім’я надто довге.", emailRequired: "Введіть email.", emailInvalid: "Введіть коректний email.", topicRequired: "Оберіть тему.", topicInvalid: "Оберіть тему зі списку.", messageRequired: "Напишіть повідомлення.", messageInvalid: "Повідомлення надто довге.", consentRequired: "Підтвердьте згоду на обробку даних." } },
  topics: contactTopicValues.map((value): { value: ContactTopicValue; label: string } => ({ value, label: topics[value] })),
} as const;
