import assert from "node:assert/strict";
import test from "node:test";
import { CASH_PATH_GUIDES } from "../lib/public-site/cashpath-guides.generated.ts";
import { installMissingCashPathGuides, missingCashPathGuides } from "../lib/public-site/cashpath-guides.ts";
import { decodeRichText } from "../lib/public-site/rich-text.ts";
import type { PublicSiteContent } from "../lib/public-site/types.ts";
const slugs=["what-is-apr-on-a-personal-loan","apr-vs-interest-rate","how-to-compare-personal-loan-offers","what-fees-can-personal-loans-include"];
test("Guide #4 is a complete, safe, rich-text fee guide",()=>{assert.deepEqual(CASH_PATH_GUIDES.map(x=>x.slug),slugs);const g=CASH_PATH_GUIDES.at(-1)!;assert.equal(g.title,"What Fees Can Personal Loans Include?");assert.equal(g.seo_title,"Personal Loan Fees: What Can They Include? | CashPath");assert.equal(g.is_visible,true);assert.equal(g.seo_no_index,false);assert.ok(g.plain_text_word_count>=1450&&g.plain_text_word_count<=1700);assert.ok(g.section_count>=14);assert.ok(decodeRichText(g.intro));for(const b of g.blocks??[]){assert.ok(b.text.length<=40000);assert.ok(decodeRichText(b.text));}const s=JSON.stringify(g);for(const value of ["do-personal-installment-loans-have-fees-en-2120","what-is-a-personal-installment-loan-en-2114","what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733","what-know-about-advance-fee-loans","/p/rates-fees","/p/how-to-compare-personal-loan-offers","/p/what-is-apr-on-a-personal-loan","/p/apr-vs-interest-rate","/p/responsible-lending"])assert.match(s,new RegExp(value));assert.match(s,/CashPath is not a lender/);assert.doesNotMatch(s,/APR of \d+%|guaranteed approval|guaranteed funding|fee-free loans/i);});
test("installer preserves existing three guides and appends only Guide #4",()=>{const pages=CASH_PATH_GUIDES.slice(0,3).map(x=>({...x,blocks:x.blocks?.map(b=>({...b}))}));const c={template_id:"cashpath",seo_title:"",seo_description:"",pages,custom_blocks:[{id:"cashpath-request",kind:"leadsgate_form",leadsgate_aid:"4848",leadsgate_template:"wallet-lines"}]} as unknown as PublicSiteContent;assert.deepEqual(missingCashPathGuides(c).map(x=>x.slug),[slugs[3]]);const next=installMissingCashPathGuides(c);assert.deepEqual(next.pages?.map(x=>x.slug),slugs);assert.equal(next.custom_blocks,c.custom_blocks);assert.equal(installMissingCashPathGuides(next),next);});
