"use client";

/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import type { PremiumTemplateEditorMediaTarget } from "../../../lib/public-site/premium-template-editor-adapter.ts";
import type { GlossNativeSectionId } from "../../../lib/public-site/gloss-premium-template-contract.ts";
import type { PublicSiteContent, PublicSiteProject, PublicSiteReview, PublicSiteService } from "../../../lib/public-site/types.ts";
import { glossIndexedMediaTarget, mutateGlossIndexedCards, parseGlossCards, setGlossServiceCardImage, type GlossCardModel as CardModel } from "../../../lib/public-site/gloss-card-editor-model.ts";

export const GLOSS_STRUCTURED_SECTIONS = ["services", "portfolio", "team", "membership", "safety", "reviews", "gift", "faq", "about"] as const;
export const GLOSS_RICH_TEXT_PATHS = ["about_text", "booking_text", "membership_text", "gift_text"] as const;

const models = {
  team: { delimiter: "·", fields: ["name", "role", "description"], defaults: { name: "Новый сотрудник", role: "", description: "" } },
  membership: { delimiter: "·", fields: ["title", "condition", "description", "buttonLabel", "buttonUrl"], defaults: { title: "Новый уровень клуба", condition: "", description: "", buttonLabel: "Вступить", buttonUrl: "#contact" } },
  gift: { delimiter: "·", fields: ["title", "amount", "description", "buttonLabel", "buttonUrl"], defaults: { title: "Новый сертификат", amount: "", description: "", buttonLabel: "Выбрать", buttonUrl: "#contact" } },
  safety: { delimiter: "·", fields: ["icon", "title", "description"], defaults: { icon: "✓", title: "Новая гарантия", description: "" } },
  faq: { delimiter: "|", fields: ["question", "answer"], defaults: { question: "Новый вопрос", answer: "Добавьте ответ" } },
  facts: { delimiter: "·", fields: ["value", "label"], defaults: { value: "10+", label: "Новый факт" } },
  reviewItems: { delimiter: "·", fields: ["text", "author", "caption"], defaults: { text: "Новый отзыв", author: "Клиент", caption: "" } },
} satisfies Record<string, CardModel>;

const inputClass = "w-full rounded-xl border border-black/10 bg-white px-3 py-2 text-sm outline-none focus:border-[#9d3151] disabled:opacity-50";

function MediaField({ label, value, disabled, onChange, onChoose }: { label: string; value: string; disabled: boolean; onChange(value: string): void; onChoose(): void }) {
  return <div className="grid gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#716d65]">{label}</span>{value ? <img src={value} alt="" className="h-28 w-full rounded-xl object-cover" /> : <div className="grid h-24 place-items-center rounded-xl border border-dashed border-black/15 text-xs text-[#817c72]">Изображение не выбрано</div>}<div className="flex gap-2"><button type="button" disabled={disabled} onClick={onChoose} className="rounded-full bg-[#321722] px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Выбрать из медиатеки</button>{value ? <button type="button" disabled={disabled} onClick={() => onChange("")} className="rounded-full border border-black/10 px-3 py-2 text-xs disabled:opacity-40">Убрать</button> : null}</div></div>;
}

function CardsEditor({ value, images, model, labels, imageLabel, disabled, onChange, onChooseImage }: { value: string; images?: readonly string[]; model: CardModel; labels: Record<string, string>; imageLabel?: string; disabled: boolean; onChange(value: string, images?: string[]): void; onChooseImage?(index: number): void }) {
  const cards = parseGlossCards(value, model);
  const run = (action: Parameters<typeof mutateGlossIndexedCards>[0]["action"]) => { const next = mutateGlossIndexedCards({ items: value, images, model, action }); onChange(next.items, next.images); };
  return <div className="grid gap-3">{cards.map((card, index) => <article key={index} className="grid gap-3 rounded-2xl border border-black/8 bg-[#faf9f6] p-4"><div className="flex items-center justify-between"><b className="text-xs">Карточка {index + 1}</b><button type="button" disabled={disabled} onClick={() => run({ type: "remove", index })} className="text-xs font-semibold text-red-600 disabled:opacity-40">Удалить</button></div>{imageLabel && onChooseImage ? <MediaField label={imageLabel} value={images?.[index] ?? ""} disabled={disabled} onChoose={() => onChooseImage(index)} onChange={image => { const nextImages = [...(images ?? [])]; while (nextImages.length <= index) nextImages.push(""); nextImages[index] = image; onChange(value, nextImages); }} /> : null}{model.fields.map(field => <label key={field} className="grid gap-1 text-[10px] font-semibold uppercase tracking-[.12em] text-[#716d65]">{labels[field] ?? field}<textarea rows={field === "description" || field === "answer" || field === "text" ? 3 : 1} className={inputClass} disabled={disabled} value={card[field] ?? ""} onChange={event => run({ type: "update", index, field, value: event.target.value })} /></label>)}<div className="flex justify-end gap-2"><button type="button" aria-label="Поднять карточку" disabled={disabled || index === 0} onClick={() => run({ type: "move", index, to: index - 1 })} className="h-8 w-8 rounded-full border border-black/10 disabled:opacity-25">↑</button><button type="button" aria-label="Опустить карточку" disabled={disabled || index === cards.length - 1} onClick={() => run({ type: "move", index, to: index + 1 })} className="h-8 w-8 rounded-full border border-black/10 disabled:opacity-25">↓</button></div></article>)}<button type="button" disabled={disabled || cards.length >= 12} onClick={() => run({ type: "add" })} className="rounded-xl border border-dashed border-[#9d3151]/45 bg-[#fff8fa] px-4 py-3 text-xs font-semibold text-[#8d2d4a] disabled:opacity-40">+ Добавить карточку</button></div>;
}

function ReviewsEditor({ reviews, disabled, onChange }: { reviews: readonly PublicSiteReview[]; disabled: boolean; onChange(reviews: PublicSiteReview[]): void }) {
  const update = (index: number, patch: Partial<PublicSiteReview>) => onChange(reviews.map((review, itemIndex) => itemIndex === index ? { ...review, ...patch } : review));
  return <div className="grid gap-3">{reviews.map((review, index) => <article key={review.id} className="grid gap-3 rounded-2xl border border-black/8 bg-[#faf9f6] p-4"><div className="flex justify-between"><b className="text-xs">Отзыв {index + 1}</b><button type="button" disabled={disabled} onClick={() => onChange(reviews.filter((_, i) => i !== index))} className="text-xs text-red-600">Удалить</button></div><input className={inputClass} value={review.author} disabled={disabled} onChange={e => update(index, { author: e.target.value })} placeholder="Имя клиента"/><textarea className={inputClass} rows={3} value={review.text} disabled={disabled} onChange={e => update(index, { text: e.target.value })}/><select className={inputClass} value={review.rating} disabled={disabled} onChange={e => update(index, { rating: Number(e.target.value) })}>{[5,4,3,2,1].map(value => <option key={value}>{value}</option>)}</select><input className={inputClass} value={review.source ?? ""} disabled={disabled} onChange={e => update(index, { source: e.target.value })} placeholder="Источник"/><input className={inputClass} value={review.source_url ?? ""} disabled={disabled} onChange={e => update(index, { source_url: e.target.value })} placeholder="Ссылка на источник"/><div className="flex justify-end gap-2"><button disabled={disabled || index === 0} onClick={() => { const next=[...reviews]; [next[index-1],next[index]]=[next[index],next[index-1]]; onChange(next); }} className="h-8 w-8 rounded-full border">↑</button><button disabled={disabled || index === reviews.length-1} onClick={() => { const next=[...reviews]; [next[index+1],next[index]]=[next[index],next[index+1]]; onChange(next); }} className="h-8 w-8 rounded-full border">↓</button></div></article>)}<button type="button" disabled={disabled} onClick={() => onChange([...reviews, { id: `review-${Date.now()}`, author: "Новый клиент", text: "", rating: 5, source: "", source_url: "" }])} className="rounded-xl border border-dashed border-[#9d3151]/45 px-4 py-3 text-xs font-semibold">+ Добавить отзыв</button></div>;
}

export type GlossControlProps = { sectionId: GlossNativeSectionId; content: PublicSiteContent; disabled: boolean; services: readonly PublicSiteService[]; portfolio: readonly PublicSiteProject[]; onChange(content: PublicSiteContent, historyGroup: string): void; onChooseMedia(target: PremiumTemplateEditorMediaTarget): void };

export default function GlossNativeSectionControls(props: GlossControlProps) {
  const { sectionId, content, disabled, onChooseMedia } = props;
  const set = (patch: Partial<PublicSiteContent>, group = `gloss:${sectionId}:structured`) => props.onChange({ ...content, ...patch }, group);
  const chooseBackground = () => onChooseMedia({ kind: "section-background", section: sectionId, label: "Фоновое изображение раздела" });
  const background = content.system_section_settings?.[sectionId]?.background_image_url ?? "";
  const commonMedia = <MediaField label="Фоновое изображение раздела" value={background} disabled={disabled} onChoose={chooseBackground} onChange={value => props.onChange({ ...content, system_section_settings: { ...content.system_section_settings, [sectionId]: { ...content.system_section_settings?.[sectionId], background_mode: value ? "image" : "theme", background_image_url: value } } }, `gloss:${sectionId}:background`)} />;
  if (sectionId === "services") return <div className="grid gap-4"><div className="rounded-2xl bg-[#fbf7ee] p-4 text-xs leading-5"><b>Данные услуг берутся из единого каталога.</b><br/>Название, цена, длительность и порядок редактируются там.<br/><Link href="/admin/catalog" className="mt-2 inline-flex rounded-full bg-[#17191f] px-4 py-2 font-semibold text-white">Открыть каталог услуг</Link></div>{props.services.map((service, index) => <article key={service.id} className="grid gap-2 rounded-2xl border border-black/8 p-4"><b className="text-sm">{service.title}</b><MediaField label="Изображение услуги" value={content.service_card_images?.[service.slug] ?? content.service_image_urls?.[index] ?? ""} disabled={disabled} onChoose={() => onChooseMedia({ kind: "service-card", slug: service.slug, label: `Изображение услуги: ${service.title}` })} onChange={value => props.onChange(setGlossServiceCardImage(content, service.slug, value), `gloss:services:image:${service.slug}`)} /></article>)}{commonMedia}</div>;
  if (sectionId === "portfolio") return <div className="grid gap-3"><div className="rounded-2xl bg-[#fbf7ee] p-4 text-xs"><div className="flex gap-2"><Link href="/admin/portfolio" className="rounded-full bg-[#17191f] px-4 py-2 text-white">Управлять работами</Link><Link href="/admin/media" className="rounded-full border px-4 py-2">Медиатека</Link></div><p className="mt-2">{props.portfolio.length} работ · {new Set(props.portfolio.map(item => item.category).filter(Boolean)).size} категорий</p></div><div className="grid grid-cols-3 gap-2">{props.portfolio.slice(0,6).map(project => project.image_url ? <img key={project.id} src={project.image_url} alt="" className="aspect-square rounded-xl object-cover"/> : null)}</div>{commonMedia}</div>;
  if (sectionId === "team") return <><CardsEditor value={content.team_items ?? ""} images={content.team_image_urls ?? []} model={models.team} labels={{name:"Имя",role:"Роль",description:"Описание"}} imageLabel="Фотография" disabled={disabled} onChange={(items,images) => set({team_items:items,team_image_urls:images})} onChooseImage={index => onChooseMedia(glossIndexedMediaTarget("team_image_urls", index, `Фотография сотрудника ${index+1}`))}/>{commonMedia}</>;
  if (sectionId === "membership") return <div className="grid gap-4"><CardsEditor value={content.membership_items ?? ""} images={content.membership_image_urls ?? [content.membership_image_url ?? ""]} model={models.membership} labels={{title:"Название",condition:"Условие",description:"Описание",buttonLabel:"Текст кнопки",buttonUrl:"Ссылка"}} imageLabel="Изображение уровня" disabled={disabled} onChange={(items,images)=>set({membership_items:items,membership_image_urls:images})} onChooseImage={index=>onChooseMedia({kind:"list",key:"membership_image_urls",index,label:`Изображение уровня ${index+1}`})}/>{commonMedia}</div>;
  if (sectionId === "gift") return <div className="grid gap-4"><CardsEditor value={content.gift_items ?? ""} images={content.gift_image_urls ?? [content.gift_image_url ?? ""]} model={models.gift} labels={{title:"Название",amount:"Номинал",description:"Описание",buttonLabel:"Текст кнопки",buttonUrl:"Ссылка"}} imageLabel="Изображение сертификата" disabled={disabled} onChange={(items,images)=>set({gift_items:items,gift_image_urls:images})} onChooseImage={index=>onChooseMedia({kind:"list",key:"gift_image_urls",index,label:`Изображение сертификата ${index+1}`})}/>{commonMedia}</div>;
  if (sectionId === "safety") return <><CardsEditor value={(content.safety_items ?? "").split("\n").map(line => line.split("·").length < 3 ? ` · ${line}` : line).join("\n")} model={models.safety} labels={{icon:"Значок",title:"Название",description:"Описание"}} disabled={disabled} onChange={items=>set({safety_items:items})}/>{commonMedia}</>;
  if (sectionId === "faq") return <><CardsEditor value={content.faq_items ?? ""} model={models.faq} labels={{question:"Вопрос",answer:"Ответ"}} disabled={disabled} onChange={items=>set({faq_items:items})}/>{commonMedia}</>;
  if (sectionId === "reviews") return <div className="grid gap-4"><ReviewsEditor reviews={content.reviews ?? []} disabled={disabled} onChange={reviews=>set({reviews})}/><CardsEditor value={content.reviews_items ?? ""} model={models.reviewItems} labels={{text:"Текст",author:"Автор",caption:"Подпись"}} disabled={disabled} onChange={items=>set({reviews_items:items})}/>{commonMedia}</div>;
  if (sectionId === "about") return <div className="grid gap-4"><MediaField label="Изображение о студии" value={content.about_image_url ?? ""} disabled={disabled} onChoose={()=>onChooseMedia({kind:"content",key:"about_image_url",label:"Изображение о студии"})} onChange={about_image_url=>set({about_image_url})}/><CardsEditor value={content.about_facts ?? ""} model={models.facts} labels={{value:"Значение",label:"Подпись"}} disabled={disabled} onChange={items=>set({about_facts:items})}/>{commonMedia}</div>;
  if (sectionId === "booking") return commonMedia;
  return commonMedia;
}
