import { pricing as englishPricing } from "../en/pricing";

export const pricing = {
  ...englishPricing,
  hero: { eyebrow: "TARIFS", title: ["Choisissez une offre", "adaptée à vos besoins"], lead: "Des offres pour différents besoins et budgets." }, plansHeading: "Offres OneStudio", plansSupporting: "14 jours gratuits avec les offres OneStudio.", planLabels: { included: "Inclus dans cette offre", storage: "Médias" },
  plans: {
    site: { ...englishPricing.plans.site, description: "Pour un site, un portfolio et une présence simple de votre activité en ligne.", features: ["Votre propre site", "Éditeur visuel", "Formulaires de contact et demandes", "Portfolio / galeries", "Analyses de base", "10 Go de trafic mensuel"], cta: "Créer un site" },
    business: { ...englishPricing.plans.business, description: "Tout ce qui est inclus dans Site, avec les réservations, les clients, les paiements et les processus de travail.", features: ["Tout ce qui est inclus dans Site", "Réservation en ligne", "Planning", "Services et tarifs", "Équipe / ressources", "CRM / base clients", "Paiements en ligne / acomptes", "Notifications / rappels", "100 Go de trafic mensuel"], cta: "Commencer", badge: "Le plus populaire" },
    pro: { ...englishPricing.plans.pro, description: "Tout ce qui est inclus dans Business, avec davantage d’équipe / ressources, de médias et de trafic.", features: ["Tout ce qui est inclus dans Business", "Davantage d’équipe / ressources", "Jusqu’à 3 sites", "100 Go de médias", "500 Go de trafic mensuel"], cta: "Choisir Pro" },
  },
  comparison: { ...englishPricing.comparison, title: "Spécifications techniques", sectionTitles: { websiteDesign: "SITE ET DESIGN", storageTraffic: "STOCKAGE ET TRAFIC", clientWork: "RELATION CLIENT", teamResources: "ÉQUIPE ET RESSOURCES" }, rowLabels: { websiteCount: "Nombre de sites", ssl: "SSL / connexion sécurisée", hosting: "Hébergement du site", mobile: "Mise en page mobile", visualEditor: "Éditeur visuel", basicTemplates: "Modèles de base", basicBlocks: "Blocs de base", imageOptimization: "Optimisation des images", media: "Médias", monthlyTraffic: "Trafic mensuel", contactForms: "Formulaires de contact et demandes", onlineBooking: "Réservation en ligne", schedule: "Planning", services: "Services et tarifs", crm: "CRM / base clients", payments: "Paiements en ligne / acomptes", notifications: "Notifications / rappels", staffResources: "Équipe / ressources" }, valueLabels: { standard: "Niveau standard", more: "Davantage d’équipe / ressources" }, yesLabel: "Inclus dans l’offre", noLabel: "Non inclus dans l’offre", priceUnitLabel: "/ mois", annualPriceLabel: "/ mois avec facturation annuelle" },
  billing: { monthly: "Mois", annual: "An", priceUnit: "/ mois", annualNote: "jusqu’à 68 % moins cher", annualTotal: "par an", ariaLabel: "Période de facturation" },
  design: { eyebrow: "PREMIUM DESIGN LIBRARY", title: "Premium Design Library", body: "Débloquez toute la bibliothèque de blocs premium, d’effets interactifs et d’animations OneStudio.", priceSuffix: "paiement unique", tagline: "Un achat. Toute la bibliothèque.", note: "Premium Design Library s’achète séparément et n’est incluse ni dans les offres ni dans la période gratuite de 14 jours.", cta: "Ouvrir la bibliothèque", items: [{ label: "Premium Blocks", description: "Des blocs premium pour composer des pages et des sections expressives." }, { label: "Premium Effects", description: "Des effets interactifs pour le bon accent visuel." }, { label: "Premium animations", description: "Des animations et composants visuels interactifs signés OneStudio." }] },
  faq: { eyebrow: "FAQ DES OFFRES", title: "Quelques réponses rapides sur les offres.", more: "Plus de réponses →", compactAriaLabel: "Questions sur les offres", items: [{ question: "Y a-t-il une période d’essai gratuite ?", answer: "Oui. Les offres OneStudio peuvent être testées gratuitement pendant 14 jours." }, { question: "Puis-je connecter mon propre domaine ?", answer: "Oui. Votre propre domaine est disponible avec les offres OneStudio payantes." }, { question: "Que se passe-t-il si le site dépasse sa limite de trafic ?", answer: "OneStudio ne désactive pas immédiatement un site après un dépassement ponctuel. Si le trafic élevé devient régulier, vous pouvez changer d’offre ou ajouter du trafic." }, { question: "Puis-je changer d’offre plus tard ?", answer: "Oui. Vous pouvez changer d’offre lorsque les besoins de votre activité évoluent." }] },
} as const;
