import { website as englishWebsite } from "../en/website";

export const website = {
  ...englishWebsite,
  hero: { eyebrow: "SITE CLÉ EN MAIN", title: "Site clé en main", priceLabel: "à partir de €249", projectUnit: "projet", lead: "Vous ne souhaitez pas créer le site vous-même ? Nous le concevons, le configurons et le mettons en ligne dans OneStudio.", priceNote: "Le prix dépend de la structure, du design et des fonctionnalités souhaitées. Avant de commencer, vous recevez un prix fixe pour le projet.", cta: "Parler du projet", ctaNote: "Nous vous proposerons la prochaine étape" },
  included: { eyebrow: "CE QUI EST INCLUS", title: "Tout le nécessaire pour lancer", lead: "Nous prenons en charge la création du site et sa mise en ligne technique dans OneStudio.", items: [{ title: "Design", description: "Nous construisons une direction visuelle autour de votre objectif." }, { title: "Création des pages", description: "Nous organisons la structure et les blocs nécessaires." }, { title: "Textes et photos", description: "Nous plaçons vos contenus sur les pages." }, { title: "Adaptation mobile", description: "Nous vérifions le site sur les petits écrans." }, { title: "Connexion du domaine", description: "Nous connectons votre domaine avant le lancement." }, { title: "SEO de base", description: "Nous réglons les principales métadonnées des pages." }, { title: "Publication", description: "Nous mettons le site terminé en ligne dans OneStudio." }] },
  scope: { eyebrow: "CE QUI INFLUENCE LE PRIX", title: "Un prix fixe pour votre projet", lead: "Le prix dépend de la structure, du design et des fonctionnalités souhaitées. Avant de commencer, vous recevez un prix fixe pour le projet.", items: ["Nombre et structure des pages", "Design personnalisé", "Premium Effects", "Réservation / fonctions métier", "CRM / paiements / intégrations", "Plusieurs langues", "Fonctions spécifiques", "Préparation des contenus"] },
  process: { eyebrow: "PROCESSUS", title: "De la discussion au lancement", steps: [{ number: "01", title: "Échanger", description: "Nous définissons l’objectif, la structure et les fonctionnalités." }, { number: "02", title: "Fixer le prix", description: "Nous convenons d’un prix de projet avant de commencer." }, { number: "03", title: "Créer", description: "Nous construisons les pages, le design et les fonctions nécessaires." }, { number: "04", title: "Lancer", description: "Nous connectons le domaine et publions le site." }] },
  showcase: { eyebrow: "PORTFOLIO", title: "Nos réalisations", lead: "Des sites créés et lancés avec OneStudio." },
  portfolio: { "sisters-studio": { projectType: "Projet client", cta: "Ouvrir le site", description: null, alt: null }, bembi: { projectType: "Projet client", cta: "Ouvrir le site", description: null, alt: null }, "noir-frame": { projectType: "OneStudio Original", cta: "Ouvrir le site", description: "Un studio photo premium avec portfolio, visite 3D et comparaison before/after.", alt: "Studio photo NOIR FRAME lumineux" }, "velora-house": { projectType: "OneStudio Original", cta: "Ouvrir le site", description: "Mariages, dîners privés et événements d’entreprise dans trois salles singulières.", alt: "Salle événementielle VELORA HOUSE de nuit" }, cashpath: { projectType: "Projet client", cta: "Ouvrir le site", description: "Un site clair, pensé pour explorer des options de prêts personnels.", alt: "Site CashPath avec des options de prêts personnels" } },
} as const;
