export type SolutionDetailSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  steps?: string[];
};

export type SolutionInternalLink = {
  label: string;
  href: string;
};

export type Solution = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  problem: string;
  workflow: string[];
  capabilities: string[];
  demo?: { name: string; href: string; image: string; alt: string };
  detailSections?: SolutionDetailSection[];
  internalLinks?: SolutionInternalLink[];
  setup: string[];
  faqs: Array<{ q: string; a: string }>;
  related: string[];
};

export const SOLUTIONS: readonly Solution[] = [
  { slug: "photography-studio-website", title: "Photography Studio Website Builder with Online Booking", description: "Build a photography studio website with a visual portfolio, booking, client records, scheduling and analytics in one system.", eyebrow: "FOR PHOTOGRAPHY STUDIOS", h1: "A photography studio website built to turn visits into bookings", intro: "Show the work first, then give every serious enquiry a clear next step. OneStudio connects your portfolio, services and daily follow-up without asking you to stitch together separate tools.", problem: "A beautiful portfolio can still leave visitors wondering what to book, when you are available, or what happens after they send an enquiry. OneStudio keeps that path visible.", workflow: ["Visitor explores the portfolio", "Chooses a session or sends a request", "The business receives a client record", "You manage schedule, payment and follow-up"], capabilities: ["Visual portfolio and media management", "Services and session formats", "Booking or inquiry flow", "Availability and scheduling", "Client records and booking history", "Payments where enabled", "Reminders, notifications and analytics", "Custom domain"], demo: { name: "NOIR FRAME", href: "/demos/premium-studio", image: "/images/demos/premium-studio/bright/hero.webp", alt: "Bright NOIR FRAME photo studio" }, setup: ["Choose the NOIR FRAME starting point or create a site", "Add your services, availability and visual content", "Connect the booking/request flow and publish on your domain"], faqs: [{ q: "Can I use the site for inquiries instead of instant booking?", a: "Yes. The public flow can guide visitors to a request when a session needs a conversation first." }, { q: "Does OneStudio deliver finished photographs?", a: "No. The platform covers the website, client and operational flow; photo delivery is not presented as a built-in feature." }], related: ["beauty-salon-website", "pilates-studio-website"] },
  { slug: "beauty-salon-website", title: "Beauty Salon Website Builder with Online Booking", description: "Build a beauty salon website with services, specialists, online booking, client history, reminders and payments.", eyebrow: "FOR BEAUTY SALONS", h1: "A beauty salon website that books while your team works", intro: "Let clients understand the service, specialist and time before they arrive. OneStudio gives a salon a polished front door and a practical operating flow behind it.", problem: "Salon teams lose time answering the same questions about duration, availability and who can provide a service. A connected service menu and booking flow puts those answers in front of the client.", workflow: ["Client compares services and specialists", "Selects duration and an available time", "Booking creates or updates the client record", "Reminders and payment support the visit and the next one"], capabilities: ["Service menu with duration", "Specialist profiles and availability", "Online booking", "Client history and repeat visits", "Reminders and notifications", "Payments where enabled", "Portfolio and before/after-style content", "Custom domain"], demo: { name: "LUMEA Beauty", href: "/demos/lumea-beauty", image: "/templates/lumea-beauty/hero.webp", alt: "LUMEA Beauty salon" }, setup: ["Start with LUMEA Beauty and shape the visual language", "Load services, specialists, durations and working windows", "Publish the booking path, payment options and domain"], faqs: [{ q: "Can each specialist have different availability?", a: "OneStudio supports working windows and availability as part of the booking and scheduling flow." }, { q: "Can I see another salon direction?", a: "Yes. GLOSS is a second relevant example in the template catalog." }], related: ["photography-studio-website", "pet-grooming-website"] },
  { slug: "pet-grooming-website", title: "Pet Grooming Website Builder with Online Booking", description: "Build a pet grooming website with service packages, groomer availability, booking, customer records, reminders and payments.", eyebrow: "FOR PET GROOMERS", h1: "A grooming website that makes booking the easy part", intro: "Make packages, hours and the next available option easy to understand for busy pet owners. OneStudio helps a grooming business turn that clarity into an organized booking flow.", problem: "Grooming enquiries often arrive with the same questions: which package fits, how long will it take, and when is the next opening? Put the useful details on the site before the conversation starts.", workflow: ["Owner compares grooming packages", "Chooses a groomer, service or available time", "The request becomes a customer record", "Your team uses notes, history, reminders and payment status"], capabilities: ["Grooming services and packages", "Groomer/resource availability", "Online booking", "Customer records and booking history", "Booking notes where supported", "Reminders and notifications", "Gallery, hours and custom domain", "Payments where enabled"], demo: { name: "PAWHAUS Grooming Studio", href: "/demos/pawhaus-grooming-studio", image: "/templates/pawhaus-grooming-studio/hero.webp", alt: "PAWHAUS grooming studio" }, setup: ["Open the PAWHAUS starting point", "Add packages, hours, resources and the gallery", "Publish a clear booking path and connect your domain"], faqs: [{ q: "Does OneStudio include dedicated pet profiles?", a: "No. Customer records and booking history are supported; a dedicated medical or pet-profile system is not claimed." }, { q: "Can I take payment online?", a: "Payment support is available where enabled for the site configuration." }], related: ["beauty-salon-website", "kids-center-website"] },
  { slug: "pilates-studio-website", title: "Pilates Studio Website Builder with Online Booking", description: "Build a Pilates studio website with formats, trainers, schedules, trial-session booking, client records and analytics.", eyebrow: "FOR PILATES STUDIOS", h1: "A Pilates studio website that keeps the next session clear", intro: "Give a new client enough context to choose a format and make a first visit feel simple. OneStudio joins the studio story to the schedule and client workflow.", problem: "Potential clients can hesitate when formats, trainers and trial options are scattered across messages and social posts. A structured site answers those questions at the moment of intent.", workflow: ["Visitor explores formats and trainers", "Chooses a trial session or service", "Booking creates a client record", "The studio follows schedule, reminders and payment status"], capabilities: ["Formats and services", "Trainer profiles", "Schedules and availability", "Trial-session booking", "Client records", "Payments where enabled", "Pages, content and analytics", "Reminders and custom domain"], demo: { name: "ALIGN Pilates Studio", href: "/demos/align-pilates-studio", image: "/templates/align-pilates/hero.webp", alt: "ALIGN Pilates Studio" }, setup: ["Choose ALIGN as the visual starting point", "Add formats, trainers, schedule and trial option", "Publish useful pages and connect booking to your domain"], faqs: [{ q: "Does this manage class capacity?", a: "This page does not claim capacity management; use the existing booking configuration for the capabilities it exposes." }, { q: "Can I offer a trial session?", a: "Yes, a trial session can be presented as a service or booking option." }], related: ["photography-studio-website", "kids-center-website"] },
  { slug: "kids-center-website", title: "Kids Center Website Builder with Booking", description: "Build a kids activity center website with programs, age groups, teachers, trial requests, scheduling, payments and analytics.", eyebrow: "FOR KIDS ACTIVITY CENTERS", h1: "A kids center website that helps families choose the right start", intro: "Parents need a quick view of programs, age groups, teachers and the next step. OneStudio turns that information into a welcoming, workable path from first visit to trial request.", problem: "A center can have excellent programs and still make families work too hard to understand fit, timing and contact details. Put the decision-making information in one clear place.", workflow: ["Parent compares programs and age groups", "Reviews teachers and requests a trial lesson", "The center receives a parent/client contact record", "Staff coordinate schedule, reminders and payment status"], capabilities: ["Programs and age groups", "Teacher profiles", "Trial lesson or request flow", "Parent/client contacts", "Scheduling", "Payments where enabled", "Pages, content, reminders and analytics", "Custom domain"], demo: { name: "RASTEM", href: "/demos/rastem-center", image: "/templates/rastem-center/hero-platform.webp", alt: "Children learning at RASTEM" }, setup: ["Start with the RASTEM content structure", "Add programs, age groups, teachers and trial options", "Publish family-friendly pages and connect the schedule"], faqs: [{ q: "Is OneStudio an LMS?", a: "No. This solution covers the public website and operational booking/client flow; it does not claim school or LMS functionality." }, { q: "Can families request a trial lesson?", a: "Yes. A trial lesson can be represented through the available booking or request flow." }], related: ["pilates-studio-website", "pet-grooming-website"] },
];

export const SOLUTION_PATHS = ["/solutions", ...SOLUTIONS.map((solution) => `/solutions/${solution.slug}`)] as const;
export function getSolution(slug: string) { return SOLUTIONS.find((solution) => solution.slug === slug); }
