import type { EditorInspectorPlacedField } from "./editor-spec.ts";
import type { PremiumTemplateEditorMediaTarget } from "./premium-template-editor-adapter.ts";
import type { AlignPilatesContent, AlignPilatesItem } from "./align-pilates-premium-template-content.ts";
import { DEFAULT_ALIGN_PILATES_CONTENT } from "./align-pilates-premium-template-content.ts";
import type { AlignPilatesNativeSectionId } from "./align-pilates-premium-template-contract.ts";

type Kind = "text" | "textarea" | "richText" | "url" | "action";
type Spec = { id: string; label: string; path: string; kind?: Kind; hrefPath?: string; group?: EditorInspectorPlacedField["group"] };
const field = (id: string, label: string, path: string, kind: Kind = "text", group: EditorInspectorPlacedField["group"] = "content"): Spec => ({ id, label, path, kind, group });
const action = (id: string, label: string, path: string, hrefPath: string): Spec => ({ id, label, path, hrefPath, kind: "action", group: "content" });
const items = (prefix: string, values: AlignPilatesItem[], fields: Array<[string, string, Kind?]>): Spec[] => values.flatMap((_, index) => fields.map(([key, label, kind]) => field(`${prefix}-${index}-${key}`, `${label} · ${index + 1}`, `${prefix}.${index}.${key}`, kind ?? "text", key === "image" || key === "alt" ? "media" : "content")));

export const ALIGN_PILATES_EDITOR_SPECS: Record<AlignPilatesNativeSectionId, Spec[]> = {
  hero: [field("promo", "Промо-плашка", "promo"), field("brand", "Название", "brand"), field("brand-note", "Подпись бренда", "brandNote"), ...items("navigation", DEFAULT_ALIGN_PILATES_CONTENT.navigation, [["label", "Навигация"], ["href", "Ссылка", "url"]]), action("header-cta", "CTA в шапке", "headerCta.label", "headerCta.href"), field("eyebrow", "Надзаголовок", "hero.eyebrow"), field("title", "Главный заголовок", "hero.title", "textarea"), field("text", "Текст", "hero.text", "richText"), action("primary-action", "Главная кнопка", "hero.primaryLabel", "hero.primaryUrl"), action("secondary-action", "Вторая кнопка", "hero.secondaryLabel", "hero.secondaryUrl"), field("note", "Примечание", "hero.note"), field("image", "Фото обложки", "hero.image", "url", "media"), field("alt", "Alt-текст", "hero.alt", "text", "media"), field("badge-number", "Число в бейдже", "hero.badgeNumber"), field("badge-text", "Подпись бейджа", "hero.badgeText")],
  formats: [field("title", "Заголовок", "formatsPresentation.title", "textarea"), field("text", "Подзаголовок", "formatsPresentation.text", "richText"), field("cta", "CTA карточки", "formatsPresentation.cta"), ...items("formats", DEFAULT_ALIGN_PILATES_CONTENT.formats, [["title", "Формат"], ["text", "Описание", "richText"], ["meta", "Длительность и цена"], ["image", "Фото", "url"], ["alt", "Alt-текст"]])],
  benefits: [field("title", "Заголовок", "benefitsTitle", "textarea"), ...items("benefits", DEFAULT_ALIGN_PILATES_CONTENT.benefits, [["icon", "Символ"], ["label", "Преимущество"]])],
  schedule: [field("eyebrow", "Метка", "schedulePresentation.eyebrow"), field("title", "Заголовок", "schedulePresentation.title", "textarea"), field("cta", "CTA", "schedulePresentation.cta"), ...items("schedule", DEFAULT_ALIGN_PILATES_CONTENT.schedule, [["time", "Время"], ["className", "Занятие"], ["trainer", "Тренер"], ["availability", "Доступность"]])],
  trainers: [field("title", "Заголовок", "trainersPresentation.title", "textarea"), ...items("trainers", DEFAULT_ALIGN_PILATES_CONTENT.trainers, [["name", "Имя"], ["role", "Специализация"], ["image", "Фото", "url"], ["alt", "Alt-текст"]])],
  trial: [field("eyebrow", "Метка", "trial.eyebrow"), field("title", "Заголовок", "trial.title", "textarea"), field("submit", "Кнопка", "trial.submit"), field("note", "Примечание", "trial.note", "richText")],
  memberships: [field("title", "Заголовок", "membershipsPresentation.title", "textarea"), field("popular", "Популярно", "membershipsPresentation.popular"), field("cta", "CTA", "membershipsPresentation.cta"), ...items("memberships", DEFAULT_ALIGN_PILATES_CONTENT.memberships, [["name", "Абонемент"], ["price", "Цена"], ["term", "Срок"]])],
  studio: [field("title", "Заголовок", "studioPresentation.title", "textarea"), field("text", "Подзаголовок", "studioPresentation.text", "richText"), ...items("studio", DEFAULT_ALIGN_PILATES_CONTENT.studio, [["image", "Фото студии", "url"], ["alt", "Alt-текст"]])],
  testimonial: [field("title", "Заголовок", "testimonial.title", "textarea"), field("quote", "Отзыв", "testimonial.quote", "richText"), field("author", "Автор", "testimonial.author")],
  faq: [field("title", "Заголовок", "faqPresentation.title", "textarea"), ...items("faq", DEFAULT_ALIGN_PILATES_CONTENT.faq, [["question", "Вопрос"], ["answer", "Ответ", "richText"]])],
  contacts: [field("eyebrow", "Метка", "contacts.eyebrow"), field("title", "Заголовок", "contacts.title", "textarea"), field("hours", "Часы", "contacts.hours"), field("address", "Адрес", "contacts.address"), field("cta", "CTA", "contacts.cta"), field("image", "Фото карты", "contacts.image", "url", "media"), field("alt", "Alt-текст", "contacts.alt", "text", "media")],
  footer: [field("text", "Описание", "footer.text", "richText"), field("cta", "CTA", "footer.cta"), field("address", "Адрес", "footer.address"), field("hours", "Часы", "footer.hours"), field("email", "Email", "footer.email"), field("phone", "Телефон", "footer.phone"), field("copyright", "Копирайт", "footer.copyright")],
};

const headingSections = new Set<AlignPilatesNativeSectionId>(["hero", "formats", "benefits", "schedule", "trainers", "trial", "memberships", "studio", "testimonial", "faq", "contacts"]);
const at = (root: unknown, path: string) => path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, root);
export function setAlignPilatesPath(content: AlignPilatesContent, path: string, value: string) { const next = structuredClone(content) as unknown as Record<string, unknown>; const keys = path.split("."); let target = next; for (const key of keys.slice(0, -1)) target = target[key] as Record<string, unknown>; target[keys.at(-1)!] = value; return next as unknown as AlignPilatesContent; }

export function buildAlignPilatesInspectorFields(content: AlignPilatesContent, section: AlignPilatesNativeSectionId, disabled: boolean, onChange: (next: AlignPilatesContent, group: string) => void, onChooseMedia?: (target: PremiumTemplateEditorMediaTarget) => void): EditorInspectorPlacedField[] {
  const fields = ALIGN_PILATES_EDITOR_SPECS[section].flatMap((spec) => {
    const value = String(at(content, spec.path) ?? ""); const originalValue = String(at(DEFAULT_ALIGN_PILATES_CONTENT, spec.path) ?? "");
    const update = (next: string) => onChange(setAlignPilatesPath(content, spec.path, next), `align:${section}:${spec.id}`);
    if (spec.kind === "action" && spec.hrefPath) return [{ id: spec.id, group: spec.group!, type: "action" as const, label: spec.label, text: value, href: String(at(content, spec.hrefPath) ?? ""), originalText: originalValue, originalHref: String(at(DEFAULT_ALIGN_PILATES_CONTENT, spec.hrefPath) ?? ""), disabled, onTextChange: update, onHrefChange: (next: string) => onChange(setAlignPilatesPath(content, spec.hrefPath!, next), `align:${section}:${spec.id}`) }];
    const base = spec.kind === "richText" ? { id: spec.id, group: spec.group!, type: "richText" as const, label: spec.label, value, originalValue, disabled, onChange: update } : spec.kind === "textarea" ? { id: spec.id, group: spec.group!, type: "textarea" as const, label: spec.label, rows: 3, value, originalValue, disabled, onChange: update } : { id: spec.id, group: spec.group!, type: spec.kind === "url" ? "url" as const : "text" as const, label: spec.label, value, ...(spec.kind === "url" ? {} : { originalValue }), disabled, onChange: update };
    if (spec.group !== "media" || spec.kind !== "url" || !onChooseMedia) return [base];
    return [{ id: spec.id, group: "media", type: "media", label: spec.label, value, originalValue, disabled, onChange: update, onChoose: () => onChooseMedia({ kind: "template-content", templateKey: "align-pilates-studio", path: spec.path, label: spec.label }) } as EditorInspectorPlacedField];
  });
  if (headingSections.has(section)) fields.push({ id: `align-${section}-heading-typography`, group: "typography", type: "typography", forFieldId: "title", title: "Оформление заголовка", description: "Главный заголовок выбранного раздела", value: content.headingTypography[section], disabled, onChange: (value) => onChange({ ...content, headingTypography: { ...content.headingTypography, [section]: value } }, `align:${section}:heading-typography`) });
  return fields;
}

export function resetAlignPilatesSection(content: AlignPilatesContent, section: AlignPilatesNativeSectionId) { let next = structuredClone(content); for (const spec of ALIGN_PILATES_EDITOR_SPECS[section]) { next = setAlignPilatesPath(next, spec.path, String(at(DEFAULT_ALIGN_PILATES_CONTENT, spec.path) ?? "")); if (spec.hrefPath) next = setAlignPilatesPath(next, spec.hrefPath, String(at(DEFAULT_ALIGN_PILATES_CONTENT, spec.hrefPath) ?? "")); } const headingTypography = { ...next.headingTypography }; delete headingTypography[section]; return { ...next, headingTypography }; }
