import type { EditorInspectorPlacedField } from "./editor-spec.ts";
import type { PublicSiteTypography } from "./types.ts";
import type { PremiumTemplateEditorMediaTarget } from "./premium-template-editor-adapter.ts";
import { DEFAULT_BLACKLINE_TATTOO_CONTENT, type BlacklineTattooContent } from "./blackline-tattoo-premium-template-content.ts";
import type { BlacklineTattooNativeSectionId } from "./blackline-tattoo-premium-template-contract.ts";

type FieldKind = "text" | "textarea" | "richText" | "action" | "media" | "typography";
type Spec = { id: string; label: string; path: string; kind?: FieldKind; hrefPath?: string };
const f = (id: string, label: string, path: string, kind: FieldKind = "text"): Spec => ({ id, label, path, kind });
const a = (id: string, label: string, path: string, hrefPath: string): Spec => ({ id, label, path, hrefPath, kind: "action" });
const fields = (path: string, count: number, entries: readonly [string, string, FieldKind?][]) => Array.from({ length: count }, (_, index) => entries.map(([key, label, kind]) => f(`${path}-${index}-${key}`, `${label} · ${index + 1}`, `${path}.${index}.${key}`, kind))).flat();
const values = (path: string, count: number, label: string, kind: FieldKind = "text") => Array.from({ length: count }, (_, index) => f(`${path}-${index}`, `${label} · ${index + 1}`, `${path}.${index}`, kind));

export const BLACKLINE_TATTOO_EDITOR_SPECS: Record<BlacklineTattooNativeSectionId, readonly Spec[]> = {
  hero: [f("announcement", "Промо-полоса", "announcement"), f("eyebrow", "Надзаголовок", "hero.eyebrow"), f("title", "Заголовок", "hero.title", "textarea"), f("description", "Описание", "hero.text", "richText"), ...values("hero.trust", 3, "Преимущество"), a("primary", "Основная кнопка", "hero.primaryLabel", "hero.primaryHref"), a("secondary", "Вторая кнопка", "hero.secondaryLabel", "hero.secondaryHref"), a("header-cta", "Кнопка в шапке", "headerCta.title", "headerCta.text"), f("hero-media", "Изображение обложки", "hero.image", "media")],
  styles: [f("title", "Заголовок", "stylesPresentation.title", "textarea"), f("description", "Описание", "stylesPresentation.text", "richText"), ...fields("styles", 4, [["title", "Название", "textarea"], ["text", "Описание", "richText"], ["image", "Изображение", "media"]])],
  artists: [f("title", "Заголовок", "artistsPresentation.title", "textarea"), f("description", "Описание", "artistsPresentation.text", "richText"), ...fields("artists", 4, [["title", "Имя", "textarea"], ["text", "Специализация", "richText"], ["image", "Фото", "media"]]), ...Array.from({ length: 4 }, (_, index) => a(`artist-${index}-cta`, `CTA мастера · ${index + 1}`, `artists.${index}.ctaLabel`, `artists.${index}.ctaHref`))],
  portfolio: [f("title", "Заголовок", "portfolio.title", "textarea"), f("description", "Описание", "portfolio.text", "richText"), ...fields("portfolio.items", 8, [["image", "Изображение", "media"], ["category", "Категория"], ["text", "Подпись", "text"]])],
  consultation: [f("title", "Заголовок", "consultation.title", "textarea"), f("description", "Описание", "consultation.text", "richText"), f("supporting-image", "Изображение консультации", "consultation.image", "media"), ...values("consultation.fields", 6, "Поле формы"), a("cta", "Кнопка формы", "consultation.ctaLabel", "consultation.ctaHref"), f("success", "Сообщение об успехе", "consultation.success", "richText")],
  process: [f("title", "Заголовок", "processPresentation.title", "textarea"), f("description", "Описание", "processPresentation.text", "richText"), ...fields("process", 4, [["title", "Шаг", "textarea"], ["text", "Описание", "richText"]])],
  safety: [f("title", "Заголовок", "safety.title", "textarea"), f("description", "Описание", "safety.text", "richText"), ...values("safety.items", 5, "Правило безопасности", "richText")],
  care: [f("title", "Заголовок", "care.title", "textarea"), f("description", "Описание", "care.text", "richText"), ...fields("care.groups", 3, [["title", "Группа", "textarea"], ["text", "Текст", "richText"]])],
  testimonials: [f("title", "Заголовок", "testimonialsPresentation.title", "textarea"), f("description", "Описание", "testimonialsPresentation.text", "richText"), ...fields("testimonials", 1, [["text", "Отзыв", "richText"], ["title", "Автор / источник"]])],
  faq: [f("title", "Заголовок", "faqPresentation.title", "textarea"), f("description", "Описание", "faqPresentation.text", "richText"), ...fields("faq", 4, [["title", "Вопрос", "textarea"], ["text", "Ответ", "richText"]])],
  contact: [f("title", "Заголовок", "contact.title", "textarea"), f("description", "Описание", "contact.text", "richText"), f("address", "Адрес", "contact.address"), f("hours", "Часы работы", "contact.hours"), f("phone", "Телефон", "contact.phone"), f("email", "Email", "contact.email"), a("cta", "Кнопка контактов", "contact.ctaLabel", "contact.ctaHref"), f("contact-image", "Изображение контактов", "contact.image", "media")],
  footer: [f("brand", "Бренд", "footer.title"), f("description", "Описание", "footer.text", "richText"), ...Array.from({ length: 7 }, (_, index) => [f(`footer-nav-${index}-title`, `Навигация · название · ${index + 1}`, `footer.navigation.${index}.title`), f(`footer-nav-${index}-href`, `Навигация · ссылка · ${index + 1}`, `footer.navigation.${index}.text`)]).flat(), f("address", "Адрес", "footer.address"), f("phone", "Телефон", "footer.phone"), f("email", "Email", "footer.email"), a("cta", "Кнопка подвала", "footer.ctaLabel", "footer.ctaHref"), f("copyright", "Копирайт", "footer.copyright"), f("credit", "Подпись OneStudio", "footer.credit", "richText")],
};

const get = (root: unknown, path: string): unknown => path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, root);
const set = (root: BlacklineTattooContent, path: string, value: unknown): BlacklineTattooContent => { const next = structuredClone(root) as unknown as Record<string, unknown>; const keys = path.split("."); let target = next; for (const key of keys.slice(0, -1)) target = target[key] as Record<string, unknown>; target[keys.at(-1)!] = value; return next as unknown as BlacklineTattooContent; };

export function buildBlacklineTattooInspectorFields(content: BlacklineTattooContent, section: BlacklineTattooNativeSectionId, disabled: boolean, onChange: (next: BlacklineTattooContent, group: string) => void, onChooseMedia?: (target: PremiumTemplateEditorMediaTarget) => void): EditorInspectorPlacedField[] {
  const result = BLACKLINE_TATTOO_EDITOR_SPECS[section].map((spec) => {
    const value = get(content, spec.path); const originalValue = get(DEFAULT_BLACKLINE_TATTOO_CONTENT, spec.path); const update = (next: string) => onChange(set(content, spec.path, next), `blackline:${section}:${spec.id}`);
    if (spec.kind === "media") return { id: spec.id, group: "media" as const, type: "media" as const, label: spec.label, value: String(value ?? ""), originalValue: String(originalValue ?? ""), disabled, onChange: update, onChoose: () => onChooseMedia?.({ kind: "template-content", templateKey: "blackline-tattoo", path: spec.path, label: spec.label }) };
    if (spec.kind === "action" && spec.hrefPath) return { id: spec.id, group: "content" as const, type: "action" as const, label: spec.label, text: String(value ?? ""), href: String(get(content, spec.hrefPath) ?? ""), originalText: String(originalValue ?? ""), originalHref: String(get(DEFAULT_BLACKLINE_TATTOO_CONTENT, spec.hrefPath) ?? ""), disabled, onTextChange: update, onHrefChange: (next: string) => onChange(set(content, spec.hrefPath!, next), `blackline:${section}:${spec.id}`) };
    if (spec.kind === "typography") return { id: spec.id, group: "typography" as const, type: "typography" as const, forFieldId: "title", title: spec.label, description: "Заголовок выбранного раздела", value: get(content, spec.path), disabled, onChange: (next: unknown) => onChange(set(content, spec.path, next), `blackline:${section}:${spec.id}`) };
    const type = spec.kind === "richText" ? "richText" : spec.kind === "textarea" ? "textarea" : "text";
    return { id: spec.id, group: "content" as const, type: type as "text" | "textarea" | "richText", ...(type === "textarea" ? { rows: 3 } : {}), label: spec.label, value: String(value ?? ""), originalValue: String(originalValue ?? ""), disabled, onChange: update };
  });
  if (section !== "footer") result.push({ id: `blackline-${section}-typography`, group: "typography", type: "typography", forFieldId: "title", title: "Оформление заголовка", description: "Главный заголовок выбранного раздела", value: content.headingTypography?.[section], disabled, onChange: (value: PublicSiteTypography | undefined) => onChange({ ...content, headingTypography: { ...(content.headingTypography ?? {}), [section]: value } }, `blackline:${section}:typography`) } as never);
  return result as EditorInspectorPlacedField[];
}

export function resetBlacklineTattooSection(content: BlacklineTattooContent, section: BlacklineTattooNativeSectionId): BlacklineTattooContent { let next = structuredClone(content); for (const spec of BLACKLINE_TATTOO_EDITOR_SPECS[section]) { next = set(next, spec.path, get(DEFAULT_BLACKLINE_TATTOO_CONTENT, spec.path)); if (spec.hrefPath) next = set(next, spec.hrefPath, get(DEFAULT_BLACKLINE_TATTOO_CONTENT, spec.hrefPath)); } const headingTypography = { ...next.headingTypography }; delete headingTypography[section]; return { ...next, headingTypography }; }
