import { BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT, type BloomFloralStudioNativeSectionId } from "./bloom-floral-studio-premium-template-contract.ts";
import { BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, resolveBloomFloralStudioContent, withBloomFloralStudioContent } from "./bloom-floral-studio-premium-template-content.ts";
import { createBloomFloralStudioPremiumTemplateSeed } from "./bloom-floral-studio-premium-template-seed.ts";
import { buildBloomFloralStudioInspectorFields, resetBloomFloralStudioSection } from "./bloom-floral-studio-editor-schema.ts";
import { createPremiumTemplateNativeToken, movePremiumTemplateCompositionItem, normalizePremiumTemplateComposition } from "./premium-template-composition.ts";
import { visibilityAfterPremiumEditorReset, type PremiumTemplateEditorAdapter } from "./premium-template-editor-adapter.ts";
import { isTemplateNativeSectionVisible, setTemplateNativeSectionVisibility } from "./template-native-section-state.ts";
import { clearPremiumNativeActionStyles, withPremiumActionAppearances } from "./premium-action-style.ts";
const nativeToken = (id: BloomFloralStudioNativeSectionId) => createPremiumTemplateNativeToken(BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id);
const nativeSectionId = (token: string) => { const prefix = `native:${BLOOM_FLORAL_STUDIO_TEMPLATE_KEY}:`; if (!token.startsWith(prefix)) return null; const id = token.slice(prefix.length); return BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT.nativeSections.some((section) => section.id === id) ? id as BloomFloralStudioNativeSectionId : null; };
const normalizeLayout = (tokens: readonly string[], ids: readonly string[]) => normalizePremiumTemplateComposition({ contract: BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT, tokens, customBlockIds: ids });
export const BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_EDITOR_ADAPTER = {
  templateKey: BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, contract: BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT, restoreLabel: "Restore BLOOM original", initialSectionId: "hero", nativeToken, nativeSectionId, normalizeLayout,
  moveLayoutItem: (input: any) => movePremiumTemplateCompositionItem({ contract: BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT, ...input }),
  isSectionVisible: (content, id) => isTemplateNativeSectionVisible(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id), setSectionVisibility: (content, id, visible) => setTemplateNativeSectionVisibility(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id, visible),
  resetSection: (content, id) => { const cleared = clearPremiumNativeActionStyles(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id); const current = resolveBloomFloralStudioContent(cleared); const next = withBloomFloralStudioContent(cleared, resetBloomFloralStudioSection(current, id), true); const definition = BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT.nativeSections.find((section) => section.id === id)!; return setTemplateNativeSectionVisibility(next, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id, visibilityAfterPremiumEditorReset(definition, isTemplateNativeSectionVisible(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, id))); },
  restoreTemplate: (content) => { const cleared = clearPremiumNativeActionStyles(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY); const locale = content.template_content?.[`${BLOOM_FLORAL_STUDIO_TEMPLATE_KEY}:locale`] === "en" ? "en" : "ru"; const seed = createBloomFloralStudioPremiumTemplateSeed(locale); return { ...cleared, ...seed, custom_blocks: [], pages: seed.pages, template_content: seed.template_content, layout_order: seed.layout_order }; },
  buildInspectorFields: ({ content, sectionId, disabled, onChange, onChooseMedia }: any) => withPremiumActionAppearances({ fields: buildBloomFloralStudioInspectorFields(resolveBloomFloralStudioContent(content), sectionId, disabled, (next, group) => onChange(withBloomFloralStudioContent(content, next), group), onChooseMedia), content, templateKey: BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, sectionId, disabled, onChange }),
  insertCustomBlock: (content, block) => { const ids = [...(content.custom_blocks ?? []).map((item) => item.id), block.id]; const layout = normalizeLayout(content.layout_order ?? [], ids).filter((token) => token !== `custom:${block.id}`); const footer = layout.indexOf(nativeToken("footer")); layout.splice(footer < 0 ? layout.length : footer, 0, `custom:${block.id}`); return { ...content, custom_blocks: [...(content.custom_blocks ?? []), block], layout_order: layout }; },
  history: { layout: "bloom-layout-order", visibility: (id: string) => `bloom:${id}:visibility`, reset: (id: string) => `bloom:${id}:reset`, restore: "bloom:restore-original" },
} satisfies PremiumTemplateEditorAdapter<BloomFloralStudioNativeSectionId>;
