import type { PublicSiteContent, PublicSiteTypography } from "./types.ts";
import type { BloomFloralStudioNativeSectionId } from "./bloom-floral-studio-premium-template-contract.ts";
import { replaceTemplateContentPreservingEditorState } from "./template-native-section-state.ts";

export const BLOOM_FLORAL_STUDIO_TEMPLATE_KEY = "bloom-floral-studio" as const;
export type BloomItem = { title: string; text: string; meta?: string; image?: string };
export type BloomAction = { title: string; text: string };
export type BloomFloralStudioContent = {
  version: 1; headingTypography: Partial<Record<BloomFloralStudioNativeSectionId, PublicSiteTypography>>;
  brand: string; brandNote: string; menuLabel: string; navigation: BloomItem[]; headerCta: BloomAction;
  hero: BloomItem & { eyebrow: string; primary: BloomAction; secondary: BloomAction; image: string };
  collections: BloomItem & { items: BloomItem[]; cta: BloomAction };
  occasions: BloomItem & { items: BloomItem[] };
  delivery: BloomItem & { cta: BloomAction; image: string; detailImage: string };
  weddings: BloomItem & { items: BloomItem[]; cta: BloomAction; image: string };
  subscription: BloomItem & { items: BloomItem[]; cta: BloomAction; image: string };
  workshops: BloomItem & { items: BloomItem[]; cta: BloomAction; image: string };
  testimonials: BloomItem[]; faq: BloomItem[]; contact: BloomItem & { cta: BloomAction; address: string; phone: string; email: string; image: string; detailImage: string };
  footer: BloomItem & { navigation: BloomItem[]; cta: BloomAction; copyright: string };
};

const asset = (name: string) => `/templates/bloom-floral-studio/${name}`;
const action = (title: string, text: string): BloomAction => ({ title, text });
const item = (title: string, text: string, meta?: string, image?: string): BloomItem => ({ title, text, ...(meta ? { meta } : {}), ...(image ? { image: asset(image) } : {}) });

export const DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT: BloomFloralStudioContent = {
  version: 1, headingTypography: {}, brand: "BLOOM", brandNote: "FLORAL ATELIER", menuLabel: "Меню",
  navigation: [item("Коллекции", "#collections"), item("Поводы", "#occasions"), item("Доставка", "#delivery"), item("Свадьбы", "#weddings"), item("Контакты", "#contact")], headerCta: action("Заказать букет", "#collections"),
  hero: { ...item("Цветы, которые говорят без лишних слов.", "Сезонные букеты и композиции, собранные вручную в нашей цветочной мастерской.", undefined, "hero-floral.webp"), eyebrow: "FLORAL ATELIER · KYIV", primary: action("Выбрать букет", "#collections"), secondary: action("Как это работает", "#delivery"), image: asset("hero-floral.webp") },
  collections: { ...item("Коллекции, собранные по сезону.", "От воздушных монобукетов до выразительных композиций для особенного вечера.", "01 / COLLECTIONS"), items: [item("Сезонные букеты", "Свежие цветы недели в авторской сборке.", "от 1 800 ₴", "collection-season.webp"), item("Монобукеты", "Один цветок. Максимум характера.", "от 1 400 ₴", "collection-mono.webp"), item("Композиции", "Форма, фактура и ритм для дома.", "от 2 400 ₴", "collection-composition.webp"), item("Цветы в коробках", "Подарок, который уже красиво оформлен.", "от 2 200 ₴", "collection-box.webp")], cta: action("Смотреть коллекцию", "#contact") },
  occasions: { ...item("Для момента, который хочется запомнить.", "Подберём цветы под настроение, историю и человека — даже если вы пока не знаете названия.", "02 / OCCASIONS"), items: [item("День рождения", "Яркое поздравление с личным характером."), item("Спасибо", "Тёплый жест без повода для длинной речи."), item("Романтический жест", "Цветы, которые оставляют пространство для чувств."), item("Просто так", "Потому что сегодня — хороший день.")] },
  delivery: { ...item("Доставка без лишних вопросов.", "Выберите удобный интервал, добавьте открытку или попросите нас согласовать детали с получателем. Заказ собираем ближе к отправке и присылаем фото готового букета перед выездом.", "03 / DELIVERY", "delivery.webp"), cta: action("Узнать о доставке", "#contact"), image: asset("delivery.webp"), detailImage: asset("floral-detail-01.webp") },
  weddings: { ...item("Цветы для большого «да».", "От первого мудборда до последнего стола — создаём цельную флористическую историю свадьбы.", "04 / WEDDINGS", "weddings.webp"), items: [item("Bridal bouquet", "Букет невесты, который продолжает ваш образ."), item("Boutonnières", "Маленькие детали для важных людей."), item("Ceremony", "Арка, проход и пространство для обещаний."), item("Tables", "Композиции, которые поддерживают разговор.")], cta: action("Запросить консультацию", "#contact"), image: asset("weddings.webp") },
  subscription: { ...item("Цветы, которые приходят вовремя.", "Еженедельная или двухнедельная доставка для дома и офиса. Поставьте на паузу или отмените подписку в любой момент.", "05 / SUBSCRIPTION", "subscription.webp"), items: [item("Weekly", "Новый сезонный букет каждую неделю.", "от 1 600 ₴"), item("Biweekly", "Ритм, который легко встроить в жизнь.", "от 1 800 ₴"), item("For office", "Свежий акцент для команды и клиентов.", "от 3 200 ₴")], cta: action("Выбрать ритм", "#contact"), image: asset("subscription.webp") },
  workshops: { ...item("Соберите свой букет.", "Сезонные floral workshops для тех, кто хочет замедлиться, попробовать новое и уйти с цветами.", "06 / WORKSHOPS", "workshops.webp"), items: [item("Seasonal workshop", "Композиция недели и бокал вина.", "1 900 ₴"), item("Private group", "Закрытый формат для команды или друзей.", "по запросу"), item("Gift certificate", "Подарок, который превращается в вечер.", "от 1 900 ₴")], cta: action("Записаться на workshop", "#contact"), image: asset("workshops.webp") },
  testimonials: [item("«Букет выглядел так, будто его только что собрали в саду.»", "Демо-отзыв о сезонной коллекции.", "Марина · коллекция BLOOM"), item("«Очень точное чувство цвета и никакой лишней помпезности.»", "Демо-отзыв о заказе для дома.", "Алексей · доставка BLOOM"), item("«С первой встречи стало понятно, что свадьба в надёжных руках.»", "Демо-отзыв о консультации.", "София · wedding consultation")],
  faq: [item("Как выбрать время доставки?", "При оформлении назовите желаемый интервал и адрес. Мы подтвердим доступные окна после проверки маршрута и передадим заказ курьеру бережно упакованным."), item("Когда собирается букет?", "Цветы собираются под конкретный заказ ближе к отправке. Так композиция проводит меньше времени в упаковке и приезжает в хорошем состоянии."), item("Что будет, если сезонный цветок закончился?", "Предложим замену похожего оттенка, формы и ценового уровня. Если замена меняет настроение букета, сначала согласуем её с вами."), item("Можно ли заказать в тот же день?", "Иногда да — если нужные цветы доступны и в расписании есть подходящий маршрут. Для спокойного выбора лучше оставить заказ за 1–2 дня."), item("Можно ли сделать сюрприз и не звонить получателю?", "Да, отметьте это в сообщении. Для адресов с пропускным режимом или сложным подъездом мы аккуратно уточним детали у получателя, не раскрывая повод."), item("Пришлёте фото перед отправкой?", "Да, для индивидуальных заказов мы можем отправить короткий снимок готового букета перед выездом, чтобы вы увидели результат."), item("Берёте заказы на свадьбы?", "Да. На встрече обсуждаем сезон, палитру, площадку, состав работ и ориентир бюджета. Дату лучше закреплять заранее, особенно в праздничные месяцы."), item("Как ухаживать за цветами дома?", "Подрежьте стебли по диагонали, поставьте букет в чистую прохладную воду вдали от солнца и обновляйте воду каждые 1–2 дня. Подробная памятка будет в заказе.")],
  contact: { ...item("Расскажите, что вы хотите почувствовать.", "Напишите нам — поможем выбрать букет, обсудить свадьбу или подобрать формат подписки. В мастерской можно забрать заказ по предварительной договорённости.", "07 / CONTACT", "atelier.webp"), cta: action("Написать BLOOM", "mailto:hello@bloom.demo"), address: "ул. Цветочная, 18 · Киев", phone: "+38 (099) 555-31-31", email: "hello@bloom.demo", image: asset("atelier.webp"), detailImage: asset("floral-detail-02.webp") },
  footer: { ...item("BLOOM", "Современная цветочная мастерская для красивых повседневных историй."), navigation: [item("Коллекции", "#collections"), item("Свадьбы", "#weddings"), item("Подписка", "#subscription"), item("FAQ", "#faq")], cta: action("Заказать консультацию", "#contact"), copyright: "© BLOOM Floral Atelier" },
};

export const EN_BLOOM_FLORAL_STUDIO_CONTENT: BloomFloralStudioContent = {
  ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT,
  menuLabel: "Menu", navigation: [item("Collections", "#collections"), item("Occasions", "#occasions"), item("Delivery", "#delivery"), item("Weddings", "#weddings"), item("Contact", "#contact")], headerCta: action("Order flowers", "#collections"),
  hero: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.hero, eyebrow: "FLORAL ATELIER · KYIV", title: "Flowers that speak without saying a word.", text: "Seasonal bouquets and arrangements, made by hand in our floral atelier.", primary: action("Choose a bouquet", "#collections"), secondary: action("How it works", "#delivery"), image: asset("hero-floral.webp") },
  collections: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.collections, title: "Collections shaped by the season.", text: "From airy mono bouquets to expressive arrangements for a memorable evening.", meta: "01 / COLLECTIONS", items: [item("Seasonal bouquets", "The freshest flowers of the week, arranged with a point of view.", "from ₴1,800", "collection-season.webp"), item("Mono bouquets", "One flower. A lot of character.", "from ₴1,400", "collection-mono.webp"), item("Arrangements", "Shape, texture and rhythm for the home.", "from ₴2,400", "collection-composition.webp"), item("Boxed flowers", "A gift that already knows how to arrive beautifully.", "from ₴2,200", "collection-box.webp")], cta: action("View the collection", "#contact") },
  occasions: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.occasions, title: "For the moment worth remembering.", text: "We match flowers to a mood, a story and a person — even when you do not know the names yet.", meta: "02 / OCCASIONS", items: [item("Birthday", "A bright note with a character of its own."), item("Thank you", "A warm gesture without a long speech."), item("Romantic gesture", "Flowers that leave room for feeling."), item("Just because", "Because today is a good day.")] },
  delivery: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.delivery, title: "Delivery without the extra questions.", text: "Choose a time window, add a note or ask us to coordinate the details with the recipient. We arrange each order close to dispatch and can send a photo of the finished bouquet before it leaves the atelier.", meta: "03 / DELIVERY", cta: action("Learn about delivery", "#contact"), image: asset("delivery.webp"), detailImage: asset("floral-detail-01.webp") },
  weddings: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.weddings, title: "Flowers for the big yes.", text: "From the first moodboard to the last table, we create one floral story for your wedding day.", meta: "04 / WEDDINGS", items: [item("Bridal bouquet", "A bouquet that continues your look."), item("Boutonnières", "Small details for the people who matter."), item("Ceremony", "Arches, aisles and a setting for your vows."), item("Tables", "Arrangements that keep the conversation flowing.")], cta: action("Request a consultation", "#contact") },
  subscription: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.subscription, title: "Flowers that arrive on cue.", text: "Weekly or biweekly flowers for home and office. Pause or cancel your subscription whenever you need.", meta: "05 / SUBSCRIPTION", items: [item("Weekly", "A new seasonal bouquet every week.", "from ₴1,600"), item("Biweekly", "A rhythm that fits easily into life.", "from ₴1,800"), item("For office", "A fresh accent for the team and clients.", "from ₴3,200")], cta: action("Choose your rhythm", "#contact") },
  workshops: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.workshops, title: "Make your own bouquet.", text: "Seasonal floral workshops for slowing down, trying something new and leaving with flowers.", meta: "06 / WORKSHOPS", items: [item("Seasonal workshop", "This week’s arrangement and a glass of wine.", "₴1,900"), item("Private group", "A closed format for a team or friends.", "on request"), item("Gift certificate", "A gift that becomes an evening.", "from ₴1,900")], cta: action("Book a workshop", "#contact") },
  testimonials: [item("“The bouquet looked as if it had just been picked from a garden.”", "Demo testimonial for a seasonal collection.", "Marina · BLOOM collection"), item("“Such a precise sense of colour, with none of the usual fuss.”", "Demo testimonial for a home delivery.", "Alex · BLOOM delivery"), item("“After the first meeting, we knew our wedding was in careful hands.”", "Demo testimonial for a consultation.", "Sofia · wedding consultation")],
  faq: [item("How do I choose a delivery window?", "Share the preferred time range and address when you order. We will confirm the available window after checking the route and hand the wrapped order to the courier with care."), item("When is the bouquet arranged?", "Flowers are arranged for the individual order close to dispatch, so the composition spends less time packed and arrives in good condition."), item("What if a seasonal flower is unavailable?", "We suggest a replacement with a similar colour, shape and price level. If it changes the feeling of the bouquet, we confirm it with you first."), item("Can I order for the same day?", "Sometimes, when the requested flowers are available and a suitable route remains. For a calmer choice, leave 1–2 days."), item("Can this be a surprise delivery?", "Yes. Tell us not to call the recipient. For controlled-access addresses we may quietly confirm practical details without revealing the occasion."), item("Will I see the bouquet before dispatch?", "For individual orders, we can send a quick photo of the finished bouquet before it leaves the atelier."), item("Do you take wedding commissions?", "Yes. We discuss season, palette, venue, scope and a working budget in a consultation. Popular dates are best discussed well in advance."), item("How should I care for the flowers?", "Trim the stems on an angle, place the bouquet in clean cool water away from direct sun and refresh the water every 1–2 days. A care note is included with the order.")],
  contact: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.contact, title: "Tell us what you want to feel.", text: "Write to us — we will help choose a bouquet, discuss a wedding or find the right subscription rhythm. Atelier pickup is available by prior arrangement.", meta: "07 / CONTACT", cta: action("Write to BLOOM", "mailto:hello@bloom.demo"), address: "18 Tsvetochnaya Street · Kyiv", image: asset("atelier.webp"), detailImage: asset("floral-detail-02.webp") },
  footer: { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT.footer, text: "A contemporary floral atelier for beautiful everyday stories.", navigation: [item("Collections", "#collections"), item("Weddings", "#weddings"), item("Subscription", "#subscription"), item("FAQ", "#faq")], cta: action("Book a consultation", "#contact"), copyright: "© BLOOM Floral Atelier" },
};

export function resolveBloomFloralStudioContent(content: PublicSiteContent): BloomFloralStudioContent {
  const stored = content.template_content?.[BLOOM_FLORAL_STUDIO_TEMPLATE_KEY];
  return stored && typeof stored === "object" && !Array.isArray(stored) ? { ...DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT, ...(stored as Partial<BloomFloralStudioContent>) } : DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT;
}
export function withBloomFloralStudioContent(content: PublicSiteContent, value: BloomFloralStudioContent, preserve = true): PublicSiteContent { return replaceTemplateContentPreservingEditorState(content, BLOOM_FLORAL_STUDIO_TEMPLATE_KEY, value as unknown as Record<string, unknown>, preserve); }
