import type { PublicSiteTypography } from "./types.ts";
import type { EditorInspectorPlacedField } from "./editor-spec.ts";
import type { PremiumTemplateEditorMediaTarget } from "./premium-template-editor-adapter.ts";
import { DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT, type BloomFloralStudioContent, type BloomFloralStudioContent as Content } from "./bloom-floral-studio-premium-template-content.ts";
import type { BloomFloralStudioNativeSectionId } from "./bloom-floral-studio-premium-template-contract.ts";

type Kind = "text" | "textarea" | "richText" | "action" | "media";
type Spec = { id: string; label: string; path: string; kind: Kind; hrefPath?: string };
const f = (id: string, label: string, path: string, kind: Kind = "text", hrefPath?: string): Spec => ({ id, label, path, kind, ...(hrefPath ? { hrefPath } : {}) });
const action = (section: string, id: string, label: string, path: string, hrefPath: string) => f(`${section}-${id}`, label, path, "action", hrefPath);
const specs: Record<BloomFloralStudioNativeSectionId, readonly Spec[]> = {
  hero: [f("eyebrow", "Надзаголовок", "hero.eyebrow"), f("title", "Заголовок", "hero.title", "textarea"), f("text", "Описание", "hero.text", "richText"), action("hero", "primary", "Основное действие", "hero.primary.title", "hero.primary.text"), action("hero", "secondary", "Второе действие", "hero.secondary.title", "hero.secondary.text"), f("image", "Изображение", "hero.image", "media")],
  collections: [f("title", "Заголовок", "collections.title", "textarea"), f("text", "Описание", "collections.text", "richText"), action("collections", "cta", "Действие", "collections.cta.title", "collections.cta.text"), ...Array.from({ length: 4 }, (_, i) => f(`item-${i}`, `Коллекция · ${i + 1}`, `collections.items.${i}.title`)), ...Array.from({ length: 4 }, (_, i) => f(`image-${i}`, `Изображение · ${i + 1}`, `collections.items.${i}.image`, "media"))],
  occasions: [f("title", "Заголовок", "occasions.title", "textarea"), f("text", "Описание", "occasions.text", "richText"), ...Array.from({ length: 4 }, (_, i) => f(`item-${i}`, `Повод · ${i + 1}`, `occasions.items.${i}.title`))],
  delivery: [f("title", "Заголовок", "delivery.title", "textarea"), f("text", "Описание", "delivery.text", "richText"), action("delivery", "cta", "Действие", "delivery.cta.title", "delivery.cta.text"), f("image", "Изображение", "delivery.image", "media"), f("detail-image", "Деталь доставки", "delivery.detailImage", "media")],
  weddings: [f("title", "Заголовок", "weddings.title", "textarea"), f("text", "Описание", "weddings.text", "richText"), action("weddings", "cta", "Действие", "weddings.cta.title", "weddings.cta.text"), f("image", "Изображение", "weddings.image", "media"), ...Array.from({ length: 4 }, (_, i) => f(`item-${i}`, `Формат · ${i + 1}`, `weddings.items.${i}.title`))],
  subscription: [f("title", "Заголовок", "subscription.title", "textarea"), f("text", "Описание", "subscription.text", "richText"), action("subscription", "cta", "Действие", "subscription.cta.title", "subscription.cta.text"), f("image", "Изображение", "subscription.image", "media"), ...Array.from({ length: 3 }, (_, i) => f(`item-${i}`, `План · ${i + 1}`, `subscription.items.${i}.title`))],
  workshops: [f("title", "Заголовок", "workshops.title", "textarea"), f("text", "Описание", "workshops.text", "richText"), action("workshops", "cta", "Действие", "workshops.cta.title", "workshops.cta.text"), f("image", "Изображение", "workshops.image", "media"), ...Array.from({ length: 3 }, (_, i) => f(`item-${i}`, `Формат · ${i + 1}`, `workshops.items.${i}.title`))],
  testimonials: Array.from({ length: 3 }, (_, i) => f(`item-${i}`, `Отзыв · ${i + 1}`, `testimonials.${i}.text`, "textarea")),
  faq: Array.from({ length: 8 }, (_, i) => f(`item-${i}`, `Вопрос · ${i + 1}`, `faq.${i}.title`, "textarea")),
  contact: [f("title", "Заголовок", "contact.title", "textarea"), f("text", "Описание", "contact.text", "richText"), action("contact", "cta", "Действие", "contact.cta.title", "contact.cta.text"), f("image", "Изображение", "contact.image", "media"), f("detail-image", "Деталь мастерской", "contact.detailImage", "media"), f("address", "Адрес", "contact.address"), f("phone", "Телефон", "contact.phone"), f("email", "Email", "contact.email")],
  footer: [f("title", "Название", "footer.title"), f("text", "Описание", "footer.text", "richText"), action("footer", "cta", "Действие", "footer.cta.title", "footer.cta.text")],
};
function get(value: unknown, path: string): unknown { return path.split(".").reduce((current: any, key) => current?.[key], value); }
function set(value: Content, path: string, next: unknown): Content { const clone = structuredClone(value) as any; const keys = path.split("."); let cursor = clone; keys.slice(0, -1).forEach((key) => { cursor[key] ??= {}; cursor = cursor[key]; }); cursor[keys.at(-1)!] = next; return clone; }
export const BLOOM_FLORAL_STUDIO_EDITOR_SPECS = specs;
export function buildBloomFloralStudioInspectorFields(content: BloomFloralStudioContent, section: BloomFloralStudioNativeSectionId, disabled: boolean, onChange: (next: BloomFloralStudioContent, group: string) => void, onChooseMedia?: (target: PremiumTemplateEditorMediaTarget) => void): EditorInspectorPlacedField[] {
  const result = specs[section].map((spec) => { const value = String(get(content, spec.path) ?? ""); const originalValue = String(get(DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT, spec.path) ?? ""); const update = (next: string) => onChange(set(content, spec.path, next), `bloom:${section}:${spec.id}`); if (spec.kind === "action") return { id: spec.id, group: "content" as const, type: "action" as const, label: spec.label, text: value, href: String(get(content, spec.hrefPath!) ?? ""), originalText: originalValue, originalHref: String(get(DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT, spec.hrefPath!) ?? ""), disabled, onTextChange: update, onHrefChange: (next: string) => onChange(set(content, spec.hrefPath!, next), `bloom:${section}:${spec.id}`) }; if (spec.kind === "media") return { id: spec.id, group: "media" as const, type: "media" as const, label: spec.label, value, originalValue, disabled, onChange: update, onChoose: () => onChooseMedia?.({ kind: "template-content", templateKey: "bloom-floral-studio", path: spec.path, label: spec.label }) }; return { id: spec.id, group: "content" as const, type: spec.kind === "richText" ? "richText" as const : spec.kind === "textarea" ? "textarea" as const : "text" as const, label: spec.label, ...(spec.kind === "textarea" ? { rows: 3 } : {}), value, originalValue, disabled, onChange: update }; }) as EditorInspectorPlacedField[];
  if (section !== "footer") result.push({ id: `bloom-${section}-heading-typography`, group: "typography", type: "typography", forFieldId: "title", title: "Оформление заголовка", description: "Главный заголовок выбранного раздела", value: content.headingTypography?.[section], disabled, onChange: (value: PublicSiteTypography | undefined) => onChange({ ...content, headingTypography: { ...(content.headingTypography ?? {}), [section]: value } }, `bloom:${section}:typography`) });
  return result;
}
export function resetBloomFloralStudioSection(content: BloomFloralStudioContent, section: BloomFloralStudioNativeSectionId) { return set(content, section === "hero" ? "hero" : section, (DEFAULT_BLOOM_FLORAL_STUDIO_CONTENT as any)[section]); }
