import type { PublicSiteContent, PublicSiteCustomBlock, PublicSitePage } from "./types.ts";
export function createCashPathPremiumTemplateSeed(): PublicSiteContent { return {
  template_id: "cashpath", brand_name: "CashPath", theme_accent: "#167a6a", theme_dark: "#182b29", theme_surface: "#f7f5ef",
  hero_eyebrow: "PERSONAL LOAN OPTIONS", hero_title: "Find a clearer path to the funds you need.", hero_text: "CashPath connects consumers with participating providers. CashPath is not a lender and does not make credit decisions.",
  booking_label: "Start Your Request", services_label: "How it works", portfolio_label: "Loan options", about_label: "About", contact_label: "Contact", about_title: "About CashPath", about_text: "CashPath helps consumers explore participating-provider options online.", services_title: "How CashPath works", portfolio_title: "Loan options", contact_title: "Contact", show_hero: true, show_services: false, show_portfolio: false, show_about: false, show_contact: false,
  custom_blocks: [{ id: "cashpath-request", kind: "leadsgate_form", eyebrow: "REQUEST OPTIONS", title: "Start your request", text: "Choose an amount and enter your details to continue securely.", items: "", button_label: "", button_url: "", tone: "light", is_visible: true, leadsgate_aid: "4848", leadsgate_template: "wallet-lines" }],
  pages: CASHPATH_PAGES, section_order: [], layout_order: ["native:cashpath:hero", "custom:cashpath-request", "native:cashpath:footer"], favicon_url: "/templates/cashpath/favicon.svg", seo_image_url: "/templates/cashpath/hero-woman-wide-v2.png", seo_title: "CashPath | Explore Personal Loan Options Online", seo_description: "Submit a secure online request to explore personal loan options from participating providers. CashPath is not a lender and approval is not guaranteed.", seo_keywords: "personal loan options, online personal loan options, personal loans online, installment loan options, loan request online, compare loan offers, emergency expense loan options, personal loan marketplace"
} as PublicSiteContent; }

export const CASH_PATH_LEGACY_INTROS: Record<string, string> = {
about: "CashPath is an online service that helps consumers submit a request that may be connected with participating providers. CashPath is not a lender and does not make credit decisions. Any offer and its terms come from the provider.", contact: "Contact CashPath at contact@cashpath.org.", faq: "CashPath is not a lender. Requests do not guarantee approval or funding. Providers set rates, fees and terms; review every offer carefully before accepting.", "rates-fees": "CashPath does not set rates or fees. Participating providers determine APR, fees, payment schedules and other terms, which vary by provider and applicant.", "responsible-lending": "Borrowing has costs. Borrow only what you can reasonably repay, review rates, fees and the repayment schedule, and consider alternatives before accepting.", "privacy-policy": "cashpath.org (\"CashPath\", \"we\", \"our\", or \"us\") may process ordinary website and technical information. The external LeadsGate flow handles application fields; CashPath does not intentionally intercept or persist them. For privacy questions or requests, email contact@cashpath.org.", "terms-of-use": "CashPath is not a lender. Use of this website does not guarantee approval, matching or funding. Provider terms govern any financial product. For questions about these terms, contact CashPath at contact@cashpath.org.", "e-consent": "This notice explains electronic delivery of communications, access and retention requirements, and withdrawal of consent where applicable. For questions or to withdraw consent, email contact@cashpath.org.", "advertiser-disclosure": "CashPath may receive compensation when a visitor is connected with, or takes action involving, a participating provider. CashPath is not the lender; review provider terms independently.", "do-not-sell-share": "For applicable privacy-rights requests, including requests not to sell or share personal information, email contact@cashpath.org.", disclaimer: "CashPath is not a lender and does not guarantee approval, an offer, or funding timing. Rates, fees and terms are controlled by providers. Website information is general, not financial or legal advice."
};
export const CASH_PATH_FULL_INTROS: Record<string, string> = { about: "Learn what CashPath does, how the request flow works, and what to consider before accepting any provider offer.", contact: "Questions about CashPath, privacy, or the website? Here is how to reach us and where provider questions belong.", faq: "Clear answers about CashPath, provider requests, terms, and responsible decision-making.", "rates-fees": "Understand how participating providers disclose rates, fees, repayment terms, and total cost.", "responsible-lending": "Practical considerations to review before taking on a repayment obligation.", "privacy-policy": "How CashPath handles ordinary website information and the separate provider application flow.", "terms-of-use": "Terms for using the CashPath website and request service.", "e-consent": "Information about electronic communications and records related to CashPath.", "advertiser-disclosure": "How CashPath’s advertiser-supported referral model works.", "do-not-sell-share": "Privacy choices and request instructions where applicable under law.", disclaimer: "Important limitations and disclosures about the CashPath website and participating-provider flow." };
const blocks = (slug: string, sections: [string, string, string?][]): PublicSiteCustomBlock[] => sections.map(([title, text, items], index) => ({ id: `${slug}-${index + 1}`, kind: "text", eyebrow: "", title, text, items: items ?? "", button_label: "", button_url: "", tone: "light", is_visible: true }));
const CONTENT: Record<string, [string, string, string?][]> = {
about: [["What CashPath does", "CashPath is an online request and referral service. After a consumer submits a request, a participating provider or network may evaluate it. CashPath does not extend credit."], ["How the request process works", "Submit a request, review any available provider response, then decide whether to proceed.", "Submit a request\nReview any available provider response\nDecide whether to proceed"], ["What CashPath does not do", "CashPath does not make loans, make credit decisions, set APR or fees, guarantee approval, or guarantee funding."], ["How CashPath may be compensated", "CashPath may receive referral or advertising compensation when a visitor is connected with a participating provider. Compensation does not change the need to review each offer independently."], ["Before accepting an offer", "Review the APR, fees, payment schedule, total repayment, late or default terms, and the provider’s identity before deciding."]],
contact: [["Contact us", "For website, privacy, or CashPath content questions, email contact@cashpath.org."], ["What CashPath can help with", "We can help with CashPath website questions, privacy requests, page-content questions, and technical issues reaching the request flow."], ["Questions about a specific loan or offer", "Approval, underwriting, repayment, servicing, funding, and provider agreements must be discussed directly with the provider."], ["Privacy requests", "See the Privacy Policy and Do Not Sell or Share My Personal Information pages, or email contact@cashpath.org."]],
faq: [["What is CashPath?", "CashPath is an online request and referral service, not a lender."], ["Is CashPath a lender?", "No. CashPath does not make credit decisions or extend credit."], ["Does submitting a request guarantee an offer?", "No. A provider response may not be available."], ["How much can I request?", "The entry form lets you indicate a requested range from $200 to $5,000. A provider may offer a different amount or no offer."], ["Does CashPath set rates or fees?", "No. Providers determine their own terms."], ["Does CashPath charge to submit a request?", "CashPath does not charge a visitor to submit a request."], ["Will a provider check my credit?", "Providers may use credit, identity, income, or other information according to their own criteria and disclosures."], ["How quickly can funds arrive?", "Provider processing and funding timing vary; no timing is guaranteed."], ["Do I have to accept an offer?", "No. A request does not require you to accept an offer."], ["What should I review?", "Review APR, fees, payment schedule, total repayment, and provider terms."], ["How is application information handled?", "CashPath’s backend is not designed to persist application values. The browser hands supported values into the LeadsGate and participating-provider flow."], ["What if repayment is difficult?", "Contact the actual provider as early as possible and consider available alternatives."], ["Are products available everywhere?", "Availability, eligibility, and permitted terms may vary by location and applicable law."]],
"rates-fees": [["CashPath does not set rates or fees", "CashPath is not a lender. Providers determine the terms of any offer."], ["Understanding APR", "APR is a way to express the annual cost of credit. It should be reviewed with all disclosed terms, not in isolation."], ["Possible provider charges", "A provider agreement may disclose origination, late-payment, returned-payment, or other fees if applicable."], ["Repayment terms", "A provider determines the amount, term, payment frequency, and payment amount."], ["Review total cost", "Consider principal, interest, and disclosed fees—not only the monthly payment."], ["Before accepting", "Read the provider agreement carefully. State, provider, and consumer eligibility may affect available terms."], ["No obligation", "Do not accept an offer that you do not understand or that does not work for your circumstances."]],
"responsible-lending": [["Borrow only what you can reasonably repay", "Consider your budget and existing obligations before accepting credit."], ["Review the complete cost", "Review APR, fees, payment schedule, and total repayment."], ["Consider alternatives", "Depending on your situation, alternatives may include savings, a payment plan with an existing creditor, family or community assistance, or other lower-cost resources."], ["Late or missed payments", "Fees, collection activity, or credit impact may result depending on the provider agreement and applicable law."], ["Avoid advance-fee scams", "Verify provider identity and written terms. Do not assume someone is a CashPath lender because they contact you."], ["If repayment becomes difficult", "Contact the actual provider as early as possible."]],
"privacy-policy": [["Last updated", "September 7, 2026"], ["Scope and ordinary website use", "CashPath may process ordinary technical information involved in operating a website, such as network, browser, device, page, referrer, and cookie-related information where applicable."], ["Loan request information", "CashPath’s own application backend is not designed to store loan-request field values. The short form holds supported values in browser memory and passes them directly into the LeadsGate/provider flow. Providers may process information under their own notices."], ["Uses and third parties", "Information may be used to operate and improve the website, respond to requests, and support provider integrations. Independent providers control their own processing."], ["Cookies, retention, and security", "Technical records may be retained as needed for operation, security, and legal obligations. CashPath uses reasonable technical and organizational measures where applicable, but no method is absolutely secure."], ["Choices and contact", "Where applicable under law, you may request access, correction, deletion, or other privacy choices by emailing contact@cashpath.org."], ["Changes", "We may update this policy. The current version will be posted on this page."]],
"terms-of-use": [["Acceptance", "By using CashPath, you agree to these terms."], ["Description of service", "CashPath is an online request and referral service, not a lender."], ["No guarantee", "Use does not guarantee a provider match, offer, approval, requested amount, or funding."], ["Provider decisions", "Providers make their own decisions and their agreements govern any financial product."], ["Your responsibilities", "Provide accurate information, use the site lawfully, and review provider terms."], ["Third-party services", "Third-party websites and services have their own terms and notices."], ["Availability and disclaimers", "CashPath may change or update the site. Information is general and is not financial or legal advice."], ["Limitation and contact", "To the extent permitted by applicable law, CashPath disclaims liability as described by law. Contact contact@cashpath.org with questions."]],
"e-consent": [["Last updated", "September 7, 2026"], ["What this notice covers", "This notice addresses CashPath electronic communications and records."], ["Electronic communications", "You may receive communications electronically when using the site where applicable."], ["What you need", "Use an internet-capable device, current web browser, email access where needed, and the ability to save or print records."], ["Paper copies and withdrawal", "Provider-specific paper-copy requests or withdrawal of consent should follow that provider’s instructions. For CashPath website communications, contact contact@cashpath.org."], ["Provider E-Consent", "This page does not replace a separate E-Consent presented by a participating provider."], ["Contact information", "Keep relevant contact information current and contact us with questions."]],
"advertiser-disclosure": [["Advertiser-supported service", "CashPath is an advertiser-supported referral service and is not a lender."], ["Compensation", "CashPath may receive compensation for referrals or actions involving participating providers."], ["What compensation means", "Compensation may affect which provider opportunities are available or presented."], ["Not every provider is represented", "CashPath does not represent every provider or product."], ["Review independently", "CashPath does not set provider terms. Review and compare any offer independently before accepting."]],
"do-not-sell-share": [["Last updated", "September 7, 2026"], ["Your privacy choices", "Where applicable, privacy requests may include access, deletion, correction, or opting out of sale or sharing."], ["Submit a request", "Email contact@cashpath.org. Do not send an SSN or sensitive loan details by email."], ["Verification and authorized agents", "We may need information sufficient to understand and verify a request. Authorized agents may act where applicable law permits."], ["Third-party data", "CashPath cannot process rights requests for data controlled solely by an independent provider; you may need to contact that provider."], ["Non-discrimination", "Where applicable, we will not discriminate for exercising privacy rights."], ["More information", "See the Privacy Policy for additional information."]],
disclaimer: [["CashPath is not a lender", "CashPath does not make loans or credit decisions."], ["No guarantees", "CashPath does not guarantee a provider match, offer, approval, requested amount, APR, funding, or funding timing."], ["Provider controls terms", "Providers control financial terms and their agreement controls any offer."], ["General information", "Website information is general and is not financial, legal, or tax advice."], ["Availability and third parties", "Eligibility and availability vary. Third-party content and services are governed by their own terms."], ["Accuracy and contact", "Information may change. Contact contact@cashpath.org with website questions."]]
};
const DEPTH: Record<string, string> = {
about: "CashPath gives consumers a place to begin, but it does not stand in for a provider. The information entered after choosing an amount continues into an independent request flow. A provider may use its own eligibility, identity, income, and other criteria. If a next step appears, take time to compare the payment obligation with your budget and read the written terms rather than relying on a headline amount alone.",
contact: "When you write to CashPath, include enough non-sensitive detail to describe the website issue or privacy question. Do not email an SSN, bank information, or loan application details. If your question concerns an offer, payment, account balance, payoff, funding status, cancellation, or changing bank information, review the provider’s communications or agreement to identify the organization that can address it.",
faq: "Each provider uses its own process and disclosures. A request is not an offer, and an offer is not an obligation to proceed. Before taking any action, review the provider identity, the amount offered, the repayment schedule, and the complete written agreement. If you are unsure whether a payment fits your circumstances, consider alternatives or seek independent guidance before accepting.",
"rates-fees": "A lower payment can sometimes result from a longer repayment period, which may change the total amount repaid. Compare the full schedule, not just the first payment. Ask the provider how interest is calculated, whether fees apply, what happens if a payment is late, and whether there are conditions that can change the amount due. The provider’s written agreement is the source of actual terms.",
"responsible-lending": "Before borrowing, list regular income, housing, transportation, food, health, and existing debt obligations. Leave room for unexpected costs. Do not borrow more simply because a provider makes a larger amount available. If a payment becomes difficult, contact the provider promptly. Be cautious of anyone asking for an advance fee or promising approval because they mention CashPath.",
"privacy-policy": "Ordinary web operation can create technical records such as IP or network information, browser and device characteristics, pages viewed, referrer information, timestamps, and cookies or similar technology where used. CashPath uses this information where applicable to operate, secure, troubleshoot, and respond to requests. Independent hosting, integration, analytics, and provider services may have separate notices. Do not send sensitive application information by email when making a privacy request.",
"terms-of-use": "Use CashPath only for lawful purposes and provide accurate information when you choose to continue a request. CashPath content is general website information, not financial, legal, or tax advice. We may change, suspend, or update website features. Third-party services remain responsible for their own availability, decisions, terms, and privacy practices. To the extent permitted by applicable law, CashPath provides the service without promises of a particular result.",
"e-consent": "Electronic communications may include notices, disclosures, and confirmations made available through the website or email where applicable. Keep a current browser, an internet-capable device, email access when needed, and the ability to save or print records. You may withdraw consent for CashPath website communications by contacting us, but a provider’s disclosures and consent process are separate and must be handled under that provider’s instructions.",
"advertiser-disclosure": "CashPath may receive compensation when a visitor is referred to or takes an action involving a participating provider. This compensation may affect which opportunities are available or presented, and CashPath does not represent every provider or product. A visitor does not pay CashPath merely to submit a request. Compare any response independently; CashPath does not set the provider’s APR, fees, repayment terms, or approval decision.",
"do-not-sell-share": "Privacy rights and available requests vary by state and applicable law. You may ask about access, correction, deletion, or opt-out choices where applicable by emailing contact@cashpath.org. We may need reasonable information to understand and verify a request, but do not send an SSN or application details. An authorized agent may act where law permits. Provider-controlled information requires a request to that provider.",
disclaimer: "CashPath does not promise a provider response, match, approval, requested amount, APR, fees, repayment terms, funding, or funding timing. Provider agreements control actual financial terms. Website information may change and is general educational information only; it is not financial, legal, or tax advice. Third-party services and provider availability can change without notice. Review any provider agreement carefully before deciding."
};
export function cashPathFullPageBlocks(slug: string) { const base = blocks(slug, CONTENT[slug] ?? []); const note = DEPTH[slug]; return note ? [...base, { id: `${slug}-details`, kind: "text" as const, eyebrow: "", title: "Additional information", text: note, items: "", button_label: "", button_url: "", tone: "light" as const, is_visible: true }] : base; }
const page = (slug: string, title: string, intro: string, seoTitle: string, seoDescription: string): PublicSitePage => ({ id: slug, type: "custom", slug, nav_label: title, eyebrow: "CASHPATH", title, intro: CASH_PATH_FULL_INTROS[slug] ?? intro, seo_title: seoTitle, seo_description: seoDescription, is_visible: true, show_in_navigation: ["about", "faq", "contact"].includes(slug), show_booking_cta: false, blocks: cashPathFullPageBlocks(slug) });
const CASHPATH_PAGES = [
page("about", "About", "CashPath is an online service that helps consumers submit a request that may be connected with participating providers. CashPath is not a lender and does not make credit decisions. Any offer and its terms come from the provider.", "About CashPath | How Our Loan Request Service Works", "Learn how CashPath helps consumers request personal loan options from participating providers. CashPath is not a lender."),
page("contact", "Contact CashPath", "Contact CashPath at contact@cashpath.org.", "Contact CashPath | Customer Support", "Contact CashPath for website and privacy questions at contact@cashpath.org."),
page("faq", "Frequently Asked Questions", "CashPath is not a lender. Requests do not guarantee approval or funding. Providers set rates, fees and terms; review every offer carefully before accepting.", "Personal Loan FAQ | CashPath", "Answers to common questions about requesting personal loan options through CashPath."),
page("rates-fees", "Rates & Fees", "CashPath does not set rates or fees. Participating providers determine APR, fees, payment schedules and other terms, which vary by provider and applicant.", "Rates & Fees | CashPath", "Learn how rates, fees and terms are set by participating providers."),
page("responsible-lending", "Responsible Lending", "Borrowing has costs. Borrow only what you can reasonably repay, review rates, fees and the repayment schedule, and consider alternatives before accepting.", "Responsible Lending | CashPath", "Review responsible borrowing considerations before accepting a loan offer."),
page("privacy-policy", "Privacy Policy", "cashpath.org (\"CashPath\", \"we\", \"our\", or \"us\") may process ordinary website and technical information. The external LeadsGate flow handles application fields; CashPath does not intentionally intercept or persist them. For privacy questions or requests, email contact@cashpath.org.", "Privacy Policy | CashPath", "Learn how CashPath handles website information and where to send privacy questions."),
page("terms-of-use", "Terms of Use", "CashPath is not a lender. Use of this website does not guarantee approval, matching or funding. Provider terms govern any financial product. For questions about these terms, contact CashPath at contact@cashpath.org.", "Terms of Use | CashPath", "Review the terms that apply to use of the CashPath website."),
page("e-consent", "E-Consent", "This notice explains electronic delivery of communications, access and retention requirements, and withdrawal of consent where applicable. For questions or to withdraw consent, email contact@cashpath.org.", "E-Consent | CashPath", "Understand electronic communications and consent related to CashPath."),
page("advertiser-disclosure", "Advertiser Disclosure", "CashPath may receive compensation when a visitor is connected with, or takes action involving, a participating provider. CashPath is not the lender; review provider terms independently.", "Advertiser Disclosure | CashPath", "Learn about CashPath's advertising and participating-provider relationships."),
page("do-not-sell-share", "Do Not Sell or Share My Personal Information", "For applicable privacy-rights requests, including requests not to sell or share personal information, email contact@cashpath.org.", "Do Not Sell or Share | CashPath", "Submit an applicable privacy request to CashPath."),
page("disclaimer", "Disclaimer", "CashPath is not a lender and does not guarantee approval, an offer, or funding timing. Rates, fees and terms are controlled by providers. Website information is general, not financial or legal advice.", "Disclaimer | CashPath", "Review important CashPath disclaimers about participating-provider options.")
];
