/* AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Source: docs/cashpath/guides/*.md
 * Source SHA-256: deb8d9b1779583ba77b205cd7138d699c86abace1a9c4060e4e712796b8cfc4e
 * Regenerate with: node scripts/generate-cashpath-guides.mjs
 */

import type { PublicSitePage } from "./types.ts";

export const CASH_PATH_GUIDES_SOURCE_SHA256 = "deb8d9b1779583ba77b205cd7138d699c86abace1a9c4060e4e712796b8cfc4e";

export type CashPathGuide = PublicSitePage & { section_count: number; plain_text_word_count: number };

export const CASH_PATH_GUIDES: CashPathGuide[] = [
  {
    "id": "what-is-apr-on-a-personal-loan",
    "type": "custom",
    "slug": "what-is-apr-on-a-personal-loan",
    "nav_label": "What Is APR?",
    "eyebrow": "PERSONAL LOAN GUIDE",
    "title": "What Is APR on a Personal Loan?",
    "intro": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"If you are comparing personal loan offers, APR is one of the clearest numbers to review. It can help you look beyond a headline interest rate and ask a more useful question: what could this credit cost over time? APR is not a promise that you will qualify for a particular offer, and it does not replace reading the full loan agreement. It is a comparison tool that can help you slow down, compare like with like, and decide whether an offer fits your budget.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender and does not make credit decisions. Participating providers determine whether to make an offer and what terms may be available. Before accepting any offer, review the provider's disclosures, all fees, the payment schedule, and the total amount you may repay.\"}]}]}}",
    "is_visible": true,
    "show_in_navigation": false,
    "show_booking_cta": false,
    "seo_title": "What Is APR on a Personal Loan? | CashPath",
    "seo_description": "Learn what APR means on a personal loan, how it differs from the interest rate, which fees can affect costs, and how to compare loan offers.",
    "seo_no_index": false,
    "blocks": [
      {
        "id": "what-is-apr-on-a-personal-loan-1",
        "kind": "text",
        "eyebrow": "",
        "title": "What APR means in plain English",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"APR\"}]},{\"type\":\"text\",\"text\":\" stands for annual percentage rate. It is a yearly measure designed to show the cost of borrowing as a percentage. For many loans, APR includes the interest rate and may also reflect certain required finance charges. That is why APR can be more informative than looking at the interest rate alone.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Think of APR as a common language for comparing credit. One offer may advertise a lower interest rate but include required charges that make its APR higher. Another may have a similar APR but a different repayment term or payment amount. APR gives you a starting point, not a final answer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The disclosures for a particular loan explain what is included and how the provider calculates the figures. Read those disclosures carefully because costs, terms, and eligibility are determined by the provider and can vary by offer.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-2",
        "kind": "text",
        "eyebrow": "",
        "title": "APR vs. interest rate: what is the difference?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The interest rate is generally the percentage charged on the amount you borrow. APR is a broader annual cost measure that may include the interest rate plus certain fees or other finance charges required to obtain the loan. Because of that difference, APR can be higher than the interest rate.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Neither number tells the whole story on its own. A lower rate does not automatically mean lower total repayment, especially if the loan term, fees, or payment structure differ. Compare the APR, then compare the payment amount and the total of payments shown in each offer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The Consumer Financial Protection Bureau explains the general distinction between an interest rate and APR in its \"},{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/\",\"children\":[{\"type\":\"text\",\"text\":\"consumer explanation\"}]},{\"type\":\"text\",\"text\":\". The exact disclosures and calculations for a personal loan come from the provider offering it.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-3",
        "kind": "text",
        "eyebrow": "",
        "title": "Which fees can affect the cost of a personal loan?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Personal installment loans can involve fees, depending on the provider and the loan terms. Examples may include an origination fee, a late fee, a returned-payment fee, or another charge described in the agreement. Some fees may affect the amount you receive, the amount you owe, or both.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Do not assume a fee applies or does not apply based on a headline. Ask the provider to identify every fee, when it may be charged, whether it is optional, and how it affects your repayment. The CFPB's \"},{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/do-personal-installment-loans-have-fees-en-2120/\",\"children\":[{\"type\":\"text\",\"text\":\"overview of personal installment loan fees\"}]},{\"type\":\"text\",\"text\":\" is a useful starting point for questions to ask.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Fees are only one part of the cost picture. A careful comparison also includes APR, payment timing, late-payment consequences, and the total amount you could repay if you follow the scheduled payments.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-4",
        "kind": "text",
        "eyebrow": "",
        "title": "How APR helps you compare loan offers",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"APR is most useful when you compare offers for a similar amount and a similar term. Put the offers side by side and review the APR, payment amount, number of payments, total repayment, and any listed fees. That makes differences easier to see before you commit.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For example, Offer A might have a lower stated interest rate and an origination fee, while Offer B might have a slightly higher stated interest rate and no comparable origination fee. Looking at the interest rate alone cannot establish which offer has the lower overall borrowing cost. APR helps make otherwise comparable offers easier to evaluate, alongside the payment schedule and total repayment.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"If you are using an online request service, an offer is still only a proposal until you review its disclosures. CashPath does not determine rates, fees, or approval. Use the offer documents themselves as the source of truth, and see our \"},{\"type\":\"a\",\"href\":\"/p/rates-fees\",\"children\":[{\"type\":\"text\",\"text\":\"Rates & Fees\"}]},{\"type\":\"text\",\"text\":\" page for a practical checklist of cost terms to compare.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Avoid comparing one number in isolation. APR can help you ask better questions, but the payment must still fit your actual budget and the agreement must make sense for your circumstances.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-5",
        "kind": "text",
        "eyebrow": "",
        "title": "Why the loan term still matters",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The loan term is the time you have to repay the loan. A longer term can make an individual payment smaller, but it can also mean making payments for a longer period. A shorter term can result in a higher payment that may be harder to manage from month to month.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"That is why two offers with similar APRs can feel very different in practice. Review the payment schedule and the total of payments, not only the annual percentage. Be realistic about recurring expenses, changes in income, and whether the scheduled payment leaves room for essentials and unexpected costs.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Before accepting an offer, compare the repayment plan with your budget. Our \"},{\"type\":\"a\",\"href\":\"/p/responsible-lending\",\"children\":[{\"type\":\"text\",\"text\":\"Responsible Lending\"}]},{\"type\":\"text\",\"text\":\" page has general reminders about reviewing repayment ability and considering alternatives when a payment would stretch your finances too far.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-6",
        "kind": "text",
        "eyebrow": "",
        "title": "Where can you find the APR?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For a loan offer, APR is commonly shown in the provider's disclosures and agreement. It may appear alongside the interest rate, finance-charge information, payment schedule, and total repayment. If you cannot find it, ask the provider where the APR and required fees are explained before accepting anything.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Be careful not to confuse a marketing claim with final loan terms. A provider's final disclosures are more important than an early estimate, advertisement, or prequalification message. The terms you receive can depend on the provider's review and the details of the offered loan. \"},{\"type\":\"em\",\"children\":[{\"type\":\"text\",\"text\":\"A preliminary result is not the same as a final agreement.\"}]}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Save or print the offer disclosures if you need time to compare them. Taking a short pause to read the documents can make it easier to spot questions about fees, payment dates, or consequences of late payments.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-7",
        "kind": "text",
        "eyebrow": "",
        "title": "Questions to ask before accepting a loan offer",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Before you accept, make sure you can answer the following questions from the provider's current disclosures:\"}]},{\"type\":\"ul\",\"children\":[{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"What is the APR and interest rate for this specific offer?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Is the interest rate fixed or variable?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Are there origination or other upfront fees, and will any fee be deducted from the proceeds?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"What is the payment amount, how often is it due, and how long is the repayment term?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"What is the total amount scheduled to be repaid?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"What fees may apply for late or returned payments?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"What does the agreement say about early repayment?\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Which company is actually providing the credit?\"}]}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"You may also want to compare the answers across more than one offer. The \"},{\"type\":\"a\",\"href\":\"/p/faq\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath FAQ\"}]},{\"type\":\"text\",\"text\":\" explains that available offers, terms, and eligibility are determined by participating providers, and that you are not required to accept an offer simply because you submitted a request.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-8",
        "kind": "text",
        "eyebrow": "",
        "title": "Is the lowest APR always the best choice?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Not necessarily. A lower APR may be an important advantage, but it should be considered with the rest of the agreement. A payment that does not fit your budget, a term you do not understand, or fees you did not expect can still create difficulty.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Compare the offers you actually receive using the same set of questions. Look at the APR, but also review the term, scheduled payment, total repayment, fees, and the provider's policies. If one offer is unclear, ask for an explanation or take more time before deciding.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"There is no obligation to accept an offer through CashPath. Borrow only if you understand the agreement and believe you can reasonably repay according to its terms.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-9",
        "kind": "text",
        "eyebrow": "",
        "title": "The bottom line",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"APR can make personal loan comparisons clearer because it provides a standardized annual cost measure. It is especially useful when you compare offers that differ in interest rates or required charges. Still, APR is one part of a larger decision.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Read the provider's disclosures, compare the payment and total repayment, and consider how the loan fits your budget. Do not rely on a single number or assume that an offer is right for you because it appears quickly online. A careful comparison can help you make a more informed choice.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender and does not make credit decisions or determine APR, rates, fees, approval, or funding. This guide is for general educational information only.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "what-is-apr-on-a-personal-loan-10",
        "kind": "text",
        "eyebrow": "",
        "title": "Sources and further reading",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"ul\",\"children\":[{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: What is the difference between a loan interest rate and the APR?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/do-personal-installment-loans-have-fees-en-2120/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: Do personal installment loans have fees?\"}]}]}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      }
    ],
    "section_count": 10,
    "plain_text_word_count": 1473
  },
  {
    "id": "apr-vs-interest-rate",
    "type": "custom",
    "slug": "apr-vs-interest-rate",
    "nav_label": "APR vs. Interest Rate",
    "eyebrow": "PERSONAL LOAN GUIDE",
    "title": "APR vs. Interest Rate: What’s the Difference?",
    "intro": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Interest rate and APR are related, but they are not the same number. An interest rate focuses on the cost charged for borrowing the principal. APR, or annual percentage rate, is a broader annualized cost measure that can incorporate the interest rate plus certain loan charges. Neither number alone tells you everything about whether a payment or loan agreement is affordable.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"When comparing personal loan offers, it helps to understand what each number is intended to show. Start with the provider's actual disclosures, then compare the payment, repayment term, fees, and total amount scheduled to be repaid where disclosed. For a foundation on the broader measure itself, see \"},{\"type\":\"a\",\"href\":\"/p/what-is-apr-on-a-personal-loan\",\"children\":[{\"type\":\"text\",\"text\":\"What Is APR on a Personal Loan?\"}]},{\"type\":\"text\",\"text\":\".\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender and does not make credit decisions. Providers determine whether to make an offer and what terms may be available.\"}]}]}}",
    "is_visible": true,
    "show_in_navigation": false,
    "show_booking_cta": false,
    "seo_title": "APR vs. Interest Rate on a Personal Loan | CashPath",
    "seo_description": "Learn how APR differs from a personal loan interest rate, why fees matter, and which numbers to compare before accepting an offer.",
    "seo_no_index": false,
    "blocks": [
      {
        "id": "apr-vs-interest-rate-1",
        "kind": "text",
        "eyebrow": "",
        "title": "Interest rate vs. APR: the quick answer",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The interest rate is the percentage charged for borrowing the principal. It affects the interest expense associated with a loan. APR is a broader annualized measure that can include the interest rate and certain finance charges or fees included under applicable disclosure rules.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"APR is designed to make borrowing-cost comparisons more useful, but it should not be read as a complete description of every possible charge or contract term. The provider's disclosures control for a particular offer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Monthly payment is a separate concept. It depends on factors such as the amount borrowed, rate, repayment term, and payment schedule. A payment amount should not be confused with APR, even though both are important when reviewing an offer.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-2",
        "kind": "text",
        "eyebrow": "",
        "title": "What the interest rate tells you",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The principal is the amount borrowed before interest and other possible charges. The interest rate describes the cost charged for using that borrowed principal, expressed as a percentage. When other terms are comparable, a lower stated rate can reduce the borrowing cost associated with interest.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The rate alone does not show every loan charge. It also does not tell you whether the payment schedule works for your budget or whether the provider will offer the amount you requested. Review the full agreement instead of treating a headline rate as the entire decision.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"According to the CFPB, personal installment loans are repaid over a defined period, and their interest rates may be fixed or adjustable depending on the provider and product. Ask the provider which rate structure applies to the actual offer and how it is described in the agreement.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-3",
        "kind": "text",
        "eyebrow": "",
        "title": "What APR tells you",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"APR gives a broader annualized view of borrowing cost. It may reflect the interest rate, certain origination or finance charges, and certain other charges included under applicable disclosure rules. That is why APR and interest rate should not be treated as interchangeable metrics.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Do not assume APR includes every possible fee. The actual provider disclosure explains what applies to the offer you are considering. CashPath does not calculate or determine a provider's APR, rate, or fees. For a fuller plain-English explanation, visit \"},{\"type\":\"a\",\"href\":\"/p/what-is-apr-on-a-personal-loan\",\"children\":[{\"type\":\"text\",\"text\":\"What Is APR on a Personal Loan?\"}]},{\"type\":\"text\",\"text\":\".\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-4",
        "kind": "text",
        "eyebrow": "",
        "title": "Why APR can be higher than the interest rate",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"A loan can display an interest rate lower than its APR because certain charges increase the broader disclosed borrowing cost. This is one reason a stated rate by itself may not be enough to compare otherwise similar offers.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For example, Offer A might have a lower stated interest rate plus an origination charge. Offer B might have a slightly higher stated interest rate without a comparable charge. The stated rate alone cannot determine which comparable offer has the lower borrowing cost. APR helps reveal more of the cost picture, alongside the payment schedule and total repayment.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Review fees carefully rather than assuming every provider uses the same structure. Our \"},{\"type\":\"a\",\"href\":\"/p/rates-fees\",\"children\":[{\"type\":\"text\",\"text\":\"Rates & Fees\"}]},{\"type\":\"text\",\"text\":\" page lists practical questions to bring to a provider's disclosures.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-5",
        "kind": "text",
        "eyebrow": "",
        "title": "Can APR and the interest rate be the same?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"They can sometimes be equal or very close when there are no additional finance charges included in the APR calculation. That possibility does not mean consumers should assume a loan has no fees of any kind, or that every charge is included in APR.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Use the provider's actual disclosures for the offer in front of you. If the APR and interest rate are similar, still read the fee section, payment schedule, and any terms about late payments, returned payments, or early repayment.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-6",
        "kind": "text",
        "eyebrow": "",
        "title": "APR, payment amount, and loan term answer different questions",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Interest rate asks, “What am I being charged for borrowing?” APR asks, “What is the broader annualized borrowing cost?” Payment asks, “What am I expected to pay each payment period?” The loan term asks, “How long will repayment last?” Total repayment asks, “How much is scheduled to be paid overall, where disclosed?”\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"These are different questions, and they deserve separate answers. A longer term can produce a different payment pattern and a different total cost even when headline rates initially look attractive. A lower payment is not automatically a lower-cost or better-fitting agreement.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Compare the payment against your real budget before accepting. \"},{\"type\":\"a\",\"href\":\"/p/responsible-lending\",\"children\":[{\"type\":\"text\",\"text\":\"Responsible Lending\"}]},{\"type\":\"text\",\"text\":\" offers general reminders about repayment ability and reviewing terms before you decide.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-7",
        "kind": "text",
        "eyebrow": "",
        "title": "Which number should you use to compare personal loan offers?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For otherwise comparable offers, compare APR with APR and interest rate with interest rate. Do not compare one provider's APR with another provider's interest rate; those numbers may describe different parts of the cost picture.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Then review the requested or offered amount, the amount of proceeds actually received, APR, interest rate, whether the rate is fixed or adjustable, and any origination or upfront fees. Also compare the payment amount, payment frequency, repayment term, total scheduled repayment where disclosed, late or returned-payment charges, and early repayment terms.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The lowest APR does not automatically make an offer the best product for every person. The payment, term, provider agreement, and your circumstances still matter.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-8",
        "kind": "text",
        "eyebrow": "",
        "title": "What APR and interest rate do not tell you",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Neither metric alone tells you whether a payment fits your budget, whether the requested amount is appropriate, or whether an offer will be made. Neither tells you every consequence of a missed payment or every contractual condition that may apply.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"They also do not mean CashPath or a provider will approve a request. Eligibility, offers, rates, and terms are determined by providers. Read the actual agreement and ask questions before accepting anything.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-9",
        "kind": "text",
        "eyebrow": "",
        "title": "Common APR vs. interest rate questions",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"Why is my APR higher than my interest rate?\"}]},{\"type\":\"text\",\"text\":\" Certain finance charges or fees included in the APR calculation can make the broader annualized measure higher than the stated rate.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"Does a lower interest rate always mean a cheaper loan?\"}]},{\"type\":\"text\",\"text\":\" Not by itself. Compare APR with APR, then review fees, term, payment amount, and total repayment where disclosed.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"Should I compare APR or monthly payment?\"}]},{\"type\":\"text\",\"text\":\" Compare both, along with the term and total repayment. They answer different questions about the offer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"Can personal loan interest rates change?\"}]},{\"type\":\"text\",\"text\":\" Some personal installment loan products may use fixed or adjustable rates. The provider's agreement explains the rate structure for a particular offer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"strong\",\"children\":[{\"type\":\"text\",\"text\":\"Where do I find the final APR?\"}]},{\"type\":\"text\",\"text\":\" Look in the provider's current disclosures and agreement. If it is unclear, ask the provider to identify the APR and applicable fees before accepting.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For more general consumer questions about offers and provider responsibility, see the \"},{\"type\":\"a\",\"href\":\"/p/faq\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath FAQ\"}]},{\"type\":\"text\",\"text\":\".\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-10",
        "kind": "text",
        "eyebrow": "",
        "title": "The bottom line",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Interest rate and APR answer different questions. Start by comparing APR with APR and rates with rates. Then read the fees, payment amount, repayment term, total scheduled repayment, and provider agreement.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender and does not make credit decisions or determine APR, interest rates, fees, approval, or funding. This guide is for general educational information only.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "apr-vs-interest-rate-11",
        "kind": "text",
        "eyebrow": "",
        "title": "Sources and further reading",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"ul\",\"children\":[{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: What is the difference between a loan interest rate and the APR?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-a-personal-installment-loan-en-2114/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: What is a personal installment loan?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/do-personal-installment-loans-have-fees-en-2120/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: Do personal installment loans have fees?\"}]}]}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      }
    ],
    "section_count": 11,
    "plain_text_word_count": 1317
  },
  {
    "id": "how-to-compare-personal-loan-offers",
    "type": "custom",
    "slug": "how-to-compare-personal-loan-offers",
    "nav_label": "Compare Loan Offers",
    "eyebrow": "PERSONAL LOAN GUIDE",
    "title": "How to Compare Personal Loan Offers",
    "intro": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Comparing personal loan offers is easier when you use the same questions for each one. A headline rate or a low payment can be useful information, but neither answers every question about cost, repayment, or the agreement itself. Put the disclosures you receive side by side and take time to understand what each offer actually says.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"This guide focuses on how to compare offers, rather than on how APR is calculated. For a plain-English foundation, read \"},{\"type\":\"a\",\"href\":\"/p/what-is-apr-on-a-personal-loan\",\"children\":[{\"type\":\"text\",\"text\":\"What Is APR on a Personal Loan?\"}]},{\"type\":\"text\",\"text\":\" and \"},{\"type\":\"a\",\"href\":\"/p/apr-vs-interest-rate\",\"children\":[{\"type\":\"text\",\"text\":\"APR vs. Interest Rate\"}]},{\"type\":\"text\",\"text\":\". CashPath is not a lender and does not make credit decisions, determine rates or fees, or make an offer of credit.\"}]}]}}",
    "is_visible": true,
    "show_in_navigation": false,
    "show_booking_cta": false,
    "seo_title": "How to Compare Personal Loan Offers | CashPath",
    "seo_description": "Learn how to compare personal loan offers by reviewing APR, interest rate, fees, payment amount, loan term, and lender disclosures before deciding.",
    "seo_no_index": false,
    "blocks": [
      {
        "id": "how-to-compare-personal-loan-offers-1",
        "kind": "text",
        "eyebrow": "",
        "title": "Start by comparing similar offers",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Begin with offers that are similar enough to compare fairly. Look at the amount offered, the purpose and structure of the loan, and the repayment term. A payment shown for one amount or term may not mean much next to a payment for a very different amount or term.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"It can help to write each offer on one page or in a simple table. Keep the provider's disclosures with your notes. If an important detail is missing or unclear, ask the provider before deciding. Comparing similar terms makes differences in cost and repayment easier to see.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-2",
        "kind": "text",
        "eyebrow": "",
        "title": "Compare APR with APR",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"APR is a broader annualized measure of borrowing cost. Depending on the offer and applicable disclosure rules, it can reflect the interest rate plus certain finance charges. Use it as a starting point for comparing offers with similar amounts and terms.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Compare APR with APR, not one offer's APR with another offer's interest rate. Those figures can describe different parts of the cost picture. APR also does not replace the agreement or tell you every possible charge. The provider's current disclosures control for the specific offer you are considering. See \"},{\"type\":\"a\",\"href\":\"/p/what-is-apr-on-a-personal-loan\",\"children\":[{\"type\":\"text\",\"text\":\"What Is APR on a Personal Loan?\"}]},{\"type\":\"text\",\"text\":\" and \"},{\"type\":\"a\",\"href\":\"/p/apr-vs-interest-rate\",\"children\":[{\"type\":\"text\",\"text\":\"APR vs. Interest Rate\"}]},{\"type\":\"text\",\"text\":\" for more context.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-3",
        "kind": "text",
        "eyebrow": "",
        "title": "Check the interest rate and whether it can change",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The interest rate describes the cost charged for borrowing the principal. It is an important number, but it is not the same as APR and it does not describe every term in an offer.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Personal installment loan rates may be fixed or adjustable depending on the product and provider. Do not assume that every personal loan uses the same rate structure. Check the actual offer and agreement to see how the rate is described and whether it can change. The CFPB explains the general difference between a \"},{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/\",\"children\":[{\"type\":\"text\",\"text\":\"loan interest rate and APR\"}]},{\"type\":\"text\",\"text\":\"; the provider's documents explain the terms offered to you.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-4",
        "kind": "text",
        "eyebrow": "",
        "title": "Look beyond the headline rate to fees",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The rate shown in an offer is only part of the cost picture. Personal installment loans can involve fees or charges depending on the provider and the agreement. The CFPB identifies examples that can include an origination fee, a documentation fee, late fees, and optional insurance when applicable.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Read the disclosures to identify which charges apply, when they may be charged, and whether they are optional. If an upfront or origination fee is deducted from the proceeds, pay attention to both the amount you are borrowing or obligated to repay and the amount of money you actually receive. A fee is not automatically a reason to accept or reject an offer, but it should be understood before you decide. The CFPB's \"},{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/do-personal-installment-loans-have-fees-en-2120/\",\"children\":[{\"type\":\"text\",\"text\":\"personal installment loan fee guidance\"}]},{\"type\":\"text\",\"text\":\" and CashPath's \"},{\"type\":\"a\",\"href\":\"/p/rates-fees\",\"children\":[{\"type\":\"text\",\"text\":\"Rates & Fees\"}]},{\"type\":\"text\",\"text\":\" page can help frame the questions to ask.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-5",
        "kind": "text",
        "eyebrow": "",
        "title": "Compare the payment amount and payment schedule",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"A payment needs to fit your budget, but the smallest payment alone does not prove an offer is cheaper. A lower periodic payment can be associated with a different amount, term, rate, fee structure, or payment schedule.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Review the payment amount, how often it is due, the first payment timing if it is disclosed, and the number of scheduled payments. Put those details next to regular household expenses and other obligations. If a payment feels difficult to manage before you accept, take that concern seriously and ask the provider for clarification.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-6",
        "kind": "text",
        "eyebrow": "",
        "title": "Compare the repayment term and total cost",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The repayment term is the period over which scheduled payments are made. A longer term can spread repayment across more time. A shorter term may result in larger periodic payments. Both cost and affordability deserve attention.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"When other terms are comparable, a longer term can change the total amount paid over the life of the loan. Actual cost depends on the rate, fees, agreement, and payment structure, so do not rely on a universal rule. Review total scheduled repayment where it is disclosed, then consider whether the payments are realistic for your circumstances. CashPath's \"},{\"type\":\"a\",\"href\":\"/p/responsible-lending\",\"children\":[{\"type\":\"text\",\"text\":\"Responsible Lending\"}]},{\"type\":\"text\",\"text\":\" page has general reminders about reviewing repayment ability.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-7",
        "kind": "text",
        "eyebrow": "",
        "title": "Check how much money you actually receive",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Requested amount, loan amount, and net proceeds can be different. The amount you request is what you ask for. The loan amount is the amount stated in an offer. Net proceeds are the money actually delivered after any disclosed deduction that applies.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"For example, Offer A could show a lower interest rate but have an origination fee deducted from the proceeds. Offer B could have a slightly higher rate with no comparable deduction. The headline rate alone does not establish which offer fits a consumer better. Compare what you would receive, what you would repay, and the terms that connect those two amounts.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-8",
        "kind": "text",
        "eyebrow": "",
        "title": "Read the late-payment and early-repayment terms",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Read the agreement for late-payment charges, returned-payment charges, and the consequences described for missed payments. These terms can affect the cost and difficulty of repayment if a payment is not made as scheduled.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Also check whether early repayment is allowed and whether any early-repayment-related charge applies. Do not assume every lender charges a prepayment penalty, and do not assume every lender allows penalty-free early payoff. The actual agreement controls. If the wording is unclear, ask the provider to explain it before accepting.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-9",
        "kind": "text",
        "eyebrow": "",
        "title": "Make sure you know who is actually offering the loan",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Before accepting an offer, identify the actual credit provider, its contact information, where the offer terms and disclosures come from, and which company will receive payments if that information is stated. These details matter when you have a question about an offer or a payment obligation.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender. CashPath does not determine APR, interest rates, fees, approval, or funding, and it does not make credit decisions. The provider offering credit is responsible for its offer and disclosures. Read the provider's agreement, not only an introductory page or message.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-10",
        "kind": "text",
        "eyebrow": "",
        "title": "Watch for loan-offer red flags",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Be cautious when someone says approval is guaranteed before meaningful review, demands payment in exchange for a guarantee that a loan will be provided, pressures you to act immediately after unexpected contact, or seeks sensitive information through suspicious messages or links. A company that is difficult to identify or verify also deserves extra care.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Not every upfront or application-related fee means fraud. The FTC notes that legitimate lenders can require an application or appraisal fee in some circumstances. The warning sign is a demand for money in exchange for a promise or guarantee of credit. Read the FTC's \"},{\"type\":\"a\",\"href\":\"https://consumer.ftc.gov/articles/what-know-about-advance-fee-loans\",\"children\":[{\"type\":\"text\",\"text\":\"What To Know About Advance-Fee Loans\"}]},{\"type\":\"text\",\"text\":\" for more on recognizing that distinction.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-11",
        "kind": "text",
        "eyebrow": "",
        "title": "A simple personal loan comparison checklist",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Use the same checklist for each offer you are seriously considering:\"}]},{\"type\":\"ul\",\"children\":[{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Provider name and contact details\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Amount offered and amount actually received\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"APR and interest rate\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Whether the rate is fixed or adjustable\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Upfront or origination fees and other disclosed charges\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Payment amount and payment frequency\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Number of scheduled payments and repayment term\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Total scheduled repayment where disclosed\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Late-payment and returned-payment charges\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Early repayment terms\"}]},{\"type\":\"li\",\"children\":[{\"type\":\"text\",\"text\":\"Questions that still need clarification\"}]}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"This list does not replace the provider's disclosures. It helps you compare those disclosures consistently and identify questions before you agree to anything. For answers to common questions about CashPath and provider responsibility, visit the \"},{\"type\":\"a\",\"href\":\"/p/faq\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath FAQ\"}]},{\"type\":\"text\",\"text\":\".\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-12",
        "kind": "text",
        "eyebrow": "",
        "title": "Which personal loan offer is best?",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"There is no single metric that determines the best offer for every borrower. A lower-cost offer may have a payment that does not fit someone's budget. A lower payment may come with different term or total-cost tradeoffs.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"The practical decision depends on cost, payment affordability, term, fees, the agreement, and your own circumstances. This guide provides general educational information, not individualized financial advice. If an offer is difficult to understand or does not fit your budget, it may be appropriate to pause and seek clarification or consider alternatives.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-13",
        "kind": "text",
        "eyebrow": "",
        "title": "The bottom line",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"Compare like with like. Read APR, rate, fees, payment, term, and total repayment together. Review the actual provider agreement before accepting, and do not pay for a promise of guaranteed credit.\"}]},{\"type\":\"p\",\"children\":[{\"type\":\"text\",\"text\":\"CashPath is not a lender and does not make credit decisions or determine APR, interest rates, fees, approval, or funding. This guide is general educational information only.\"}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      },
      {
        "id": "how-to-compare-personal-loan-offers-14",
        "kind": "text",
        "eyebrow": "",
        "title": "Sources and further reading",
        "text": "__osrt1__:{\"version\":1,\"root\":{\"type\":\"root\",\"children\":[{\"type\":\"ul\",\"children\":[{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-a-personal-installment-loan-en-2114/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: What is a personal installment loan?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/do-personal-installment-loans-have-fees-en-2120/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: Do personal installment loans have fees?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/\",\"children\":[{\"type\":\"text\",\"text\":\"Consumer Financial Protection Bureau: What is the difference between a loan interest rate and the APR?\"}]}]},{\"type\":\"li\",\"children\":[{\"type\":\"a\",\"href\":\"https://consumer.ftc.gov/articles/what-know-about-advance-fee-loans\",\"children\":[{\"type\":\"text\",\"text\":\"Federal Trade Commission: What To Know About Advance-Fee Loans\"}]}]}]}]}}",
        "items": "",
        "button_label": "",
        "button_url": "",
        "tone": "light",
        "is_visible": true
      }
    ],
    "section_count": 14,
    "plain_text_word_count": 1520
  }
];
