import type { PublicSiteContent, PublicSiteTypography } from "./types.ts";
import type { PawhausGroomingStudioNativeSectionId } from "./pawhaus-grooming-studio-premium-template-contract.ts";
import { replaceTemplateContentPreservingEditorState } from "./template-native-section-state.ts";
export const PAWHAUS_GROOMING_STUDIO_TEMPLATE_KEY = "pawhaus-grooming-studio" as const;
type Item = { title: string; text: string; meta?: string; price?: string; image?: string };
const asset = (name: string) => `/templates/pawhaus-grooming-studio/${name}`;
type FooterContent = Item & { navigation: Item[]; contact: Item; cta: Item; copyright: string; credit: string };
export type PawhausGroomingStudioContent = { version: 1; headingTypography: Partial<Record<PawhausGroomingStudioNativeSectionId, PublicSiteTypography>>; brand: string; brandNote: string; menuLabel: string; navigation: Item[]; headerCta: Item; hero: Item & { eyebrow: string; primaryLabel: string; secondaryLabel: string; statOne: string; statTwo: string; statThree: string; image: string }; services: Item[]; beforeAfter: Item & { image: string; beforeImage: string; afterImage: string }; groomers: Item[]; process: Item[]; packages: Item[]; gallery: Item & { images: string[] }; testimonials: Item[]; booking: Item & { fields: string[] }; faq: Item[]; contact: Item; footer: FooterContent };
export const DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT: PawhausGroomingStudioContent = {
  version: 1, headingTypography: {}, brand: "PAWHAUS", brandNote: "GROOMING STUDIO", menuLabel: "Меню",
  navigation: [{ title: "Услуги", text: "#services" }, { title: "Мастера", text: "#groomers" }, { title: "Пакеты", text: "#packages" }, { title: "FAQ", text: "#faq" }, { title: "Контакты", text: "#contact" }],
  headerCta: { title: "Записаться", text: "#booking" },
  hero: { eyebrow: "CALM CARE FOR CITY PETS", title: "Спокойный груминг. Счастливый питомец.", text: "PAWHAUS — современный салон для собак и кошек, где уход становится приятным ритуалом.", primaryLabel: "Выбрать время", secondaryLabel: "Смотреть услуги", statOne: "4.9 / 5 рейтинг", statTwo: "безопасная адаптация", statThree: "центр города", image: asset("hero.webp") },
  services: [{ title: "Dog grooming", text: "Стрижка, мытьё и укладка под породу и характер.", meta: "от 60 мин", price: "от 1 200 ₴", image: asset("service-01.webp") }, { title: "Puppy first visit", text: "Мягкое знакомство с салоном без спешки и стресса.", meta: "45 мин", price: "900 ₴", image: asset("service-02.webp") }, { title: "Cat grooming", text: "Бережный уход для кошек в тихом отдельном окне.", meta: "от 50 мин", price: "от 1 100 ₴", image: asset("service-03.webp") }, { title: "Spa / coat care", text: "Увлажнение, вычёсывание и восстановление шерсти.", meta: "30–45 мин", price: "от 650 ₴", image: asset("service-04.webp") }, { title: "Nail & hygiene express", text: "Быстрый уход для тех, кому нужен только essential.", meta: "20 мин", price: "450 ₴", image: asset("service-04.webp") }],
  beforeAfter: { title: "Видимый результат, мягкий процесс.", text: "До и после — это не про идеальность. Это про здоровую шерсть, чистые лапы и питомца, который выходит спокойнее, чем пришёл.", meta: "editable before / after media", image: asset("after.webp"), beforeImage: asset("before.webp"), afterImage: asset("after.webp") },
  groomers: [{ title: "Саша Воронова", text: "Породные стрижки · спокойная адаптация", meta: "01", image: asset("groomer-01.webp") }, { title: "Лера Ким", text: "Кошки · деликатный уход", meta: "02", image: asset("groomer-02.webp") }, { title: "Миша Орлов", text: "Spa-ритуалы · curly coats", meta: "03", image: asset("groomer-03.webp") }],
  process: [{ title: "Выберите услугу", text: "Расскажите нам о породе, размере и характере питомца." }, { title: "Приезжайте без спешки", text: "Мы оставляем время на знакомство и спокойную адаптацию." }, { title: "Мы берём заботу на себя", text: "Работаем бережно, с понятными этапами и обновлениями." }, { title: "Забирайте счастливого", text: "Покажем результат и дадим короткие рекомендации домой." }],
  packages: [{ title: "First visit", text: "для первого знакомства", price: "900 ₴", image: asset("package-01.webp") }, { title: "Full groom", text: "полный уход по породе", price: "от 1 600 ₴", image: asset("package-02.webp") }, { title: "PAWHAUS club", text: "2 визита в месяц + приоритет", price: "от 2 800 ₴", image: asset("package-03.webp") }],
  gallery: { title: "Тихая эстетика ухода.", text: "Оригинальная съёмка MintPaw, восстановленная для PAWHAUS.", meta: "editable gallery", images: [asset("hero.webp"), asset("service-01.webp"), asset("service-03.webp"), asset("package-03.webp"), asset("before.webp"), asset("after.webp")] },
  testimonials: [{ title: "Марта и Тофи", text: "Тофи впервые не дрожал у двери. А шерсть после — просто вау.", meta: "dog parent" }, { title: "Ирина и Пиксель", text: "Очень спокойное отношение к кошкам и никакой суеты.", meta: "cat parent" }, { title: "Олег и Бублик", text: "Понравилась честная консультация и понятная цена до начала.", meta: "dog parent" }],
  booking: { title: "Запланируем красивый день ухода.", text: "Оставьте заявку — администратор уточнит детали и предложит лучшее окно.", fields: ["Имя", "Телефон", "Имя питомца"] },
  faq: [{ title: "Нужно ли записываться заранее?", text: "Да, особенно для первого визита и выходных. Обычно мы рекомендуем бронировать за 3–7 дней." }, { title: "Можно ли остаться рядом?", text: "Для адаптации — да. Дальше мастер предложит формат, в котором питомцу спокойнее." }, { title: "Что взять с собой?", text: "Только питомца и актуальный номер телефона. Остальное подготовит PAWHAUS." }, { title: "Как определяется стоимость?", text: "По услуге, размеру, состоянию шерсти и времени работы. Финальную сумму согласуем заранее." }],
  contact: { title: "ул. Лапкина, 12 · Киев", text: "Ежедневно 09:00–21:00 · hello@pawhaus.demo · +38 (099) 555-21-21", meta: "Проложить маршрут" }, footer: { title: "PAWHAUS", text: "Спокойный груминг для собак и кошек.", meta: "", navigation: [{ title: "Услуги", text: "#services" }, { title: "Мастера", text: "#groomers" }, { title: "Пакеты", text: "#packages" }, { title: "Галерея", text: "#gallery" }, { title: "Вопросы", text: "#faq" }, { title: "Контакты", text: "#contact" }], contact: { title: "ул. Лапкина, 12 · Киев", text: "Ежедневно 09:00–21:00 · hello@pawhaus.demo · +38 (099) 555-21-21", meta: "" }, cta: { title: "Записать питомца", text: "#booking" }, copyright: "© PAWHAUS Grooming Studio", credit: "Сделано на OneStudio OS" },
};
export function createPawhausGroomingStudioEnglishContent(): PawhausGroomingStudioContent {
  const v = structuredClone(DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT);
  v.menuLabel = "Menu";
  v.navigation = [{ title: "Services", text: "#services" }, { title: "Groomers", text: "#groomers" }, { title: "Packages", text: "#packages" }, { title: "FAQ", text: "#faq" }, { title: "Contact", text: "#contact" }];
  v.headerCta = { title: "Book a visit", text: "#booking" };
  v.hero = { ...v.hero, eyebrow: "CALM CARE FOR CITY PETS", title: "Calm grooming. Happy pets.", text: "PAWHAUS is a modern grooming studio for dogs and cats, where care becomes a gentle ritual.", primaryLabel: "Choose a time", secondaryLabel: "Explore services", statOne: "4.9 / 5 rating", statTwo: "gentle first visits", statThree: "city centre" };
  v.services = [
    { title: "Dog grooming", text: "A breed-aware cut, wash and finish shaped around your pet's character.", meta: "from 60 min", price: "from ₴1,200", image: asset("service-01.webp") },
    { title: "Puppy first visit", text: "A gentle introduction to the studio, with no rush and no stress.", meta: "45 min", price: "₴900", image: asset("service-02.webp") },
    { title: "Cat grooming", text: "Thoughtful care for cats in a quiet, separate appointment window.", meta: "from 50 min", price: "from ₴1,100", image: asset("service-03.webp") },
    { title: "Spa / coat care", text: "Moisture, brushing and coat recovery for a softer, healthier finish.", meta: "30–45 min", price: "from ₴650", image: asset("service-04.webp") },
    { title: "Nail & hygiene express", text: "A quick care visit for the essentials your pet needs today.", meta: "20 min", price: "₴450", image: asset("service-04.webp") },
  ];
  v.beforeAfter = { ...v.beforeAfter, title: "Visible results, gentle process.", text: "Before and after is not about perfection. It is about healthy coats, clean paws and a pet who leaves calmer than they arrived.", meta: "editable before / after media" };
  v.groomers = [{ title: "Sasha Voronova", text: "Breed-aware cuts · gentle introductions", meta: "01", image: asset("groomer-01.webp") }, { title: "Lera Kim", text: "Cats · delicate care", meta: "02", image: asset("groomer-02.webp") }, { title: "Misha Orlov", text: "Spa rituals · curly coats", meta: "03", image: asset("groomer-03.webp") }];
  v.process = [{ title: "Choose your service", text: "Tell us about your pet's breed, size and personality." }, { title: "Arrive without rushing", text: "We leave time for introductions and a calm first adjustment." }, { title: "Let us take care", text: "We work gently, with clear steps and regular updates." }, { title: "Take home a happy pet", text: "We show you the result and share a few simple tips for home." }];
  v.packages = [{ title: "First visit", text: "for a gentle introduction", price: "₴900", image: asset("package-01.webp") }, { title: "Full groom", text: "complete breed-aware care", price: "from ₴1,600", image: asset("package-02.webp") }, { title: "PAWHAUS club", text: "2 visits a month + priority booking", price: "from ₴2,800", image: asset("package-03.webp") }];
  v.gallery = { ...v.gallery, title: "The quiet aesthetics of care.", text: "Original MintPaw photography, restored for PAWHAUS.", meta: "editable gallery" };
  v.testimonials = [{ title: "Marta & Toffee", text: "Toffee did not tremble at the door for the first time. And the coat afterwards? Just wow.", meta: "dog parent" }, { title: "Irina & Pixel", text: "Such a calm approach to cats, with none of the usual rush.", meta: "cat parent" }, { title: "Oleg & Bublik", text: "We loved the honest consultation and clear price before we started.", meta: "dog parent" }];
  v.booking = { ...v.booking, title: "Let’s plan a beautiful care day.", text: "Leave a request and our host will suggest the best time for your pet.", fields: ["Your name", "Phone", "Pet’s name"] };
  v.faq = [{ title: "Should I book in advance?", text: "Yes, especially for first visits and weekends. We usually recommend booking 3–7 days ahead." }, { title: "Can I stay nearby?", text: "Yes, during the introduction. Then your groomer will suggest the format that feels calmest for your pet." }, { title: "What should I bring?", text: "Just your pet and a current phone number. PAWHAUS will prepare everything else." }, { title: "How is the price determined?", text: "It depends on the service, size, coat condition and time required. We confirm the final price in advance." }];
  v.contact = { title: "12 Lapkina Street · Kyiv", text: "Every day 09:00–21:00 · hello@pawhaus.demo · +38 (099) 555-21-21", meta: "Get directions" };
  v.footer = { title: "PAWHAUS", text: "Calm grooming for dogs and cats.", meta: "", navigation: [{ title: "Services", text: "#services" }, { title: "Groomers", text: "#groomers" }, { title: "Packages", text: "#packages" }, { title: "Gallery", text: "#gallery" }, { title: "FAQ", text: "#faq" }, { title: "Contacts", text: "#contact" }], contact: { title: v.contact.title, text: v.contact.text, meta: "" }, cta: { title: "Book a visit", text: "#booking" }, copyright: "© PAWHAUS Grooming Studio", credit: "Powered by OneStudio OS" };
  return v;
}
export function resolvePawhausGroomingStudioContent(content: PublicSiteContent) { const value = content.template_content?.[PAWHAUS_GROOMING_STUDIO_TEMPLATE_KEY]; return value && typeof value === "object" ? value as PawhausGroomingStudioContent : DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT; }
export function withPawhausGroomingStudioContent(content: PublicSiteContent, value: PawhausGroomingStudioContent, preserve = true): PublicSiteContent { const next = replaceTemplateContentPreservingEditorState(content, PAWHAUS_GROOMING_STUDIO_TEMPLATE_KEY, value as unknown as Record<string, unknown>, preserve); return { ...next, template_content: { ...(next.template_content ?? {}), [`${PAWHAUS_GROOMING_STUDIO_TEMPLATE_KEY}:locale`]: content.template_content?.[`${PAWHAUS_GROOMING_STUDIO_TEMPLATE_KEY}:locale`] ?? "ru" } }; }
