import type { EditorInspectorPlacedField } from "./editor-spec.ts";
import type { PremiumTemplateEditorMediaTarget } from "./premium-template-editor-adapter.ts";
import { DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT, type PawhausGroomingStudioContent } from "./pawhaus-grooming-studio-premium-template-content.ts";
import type { PawhausGroomingStudioNativeSectionId } from "./pawhaus-grooming-studio-premium-template-contract.ts";
type Spec = { id: string; label: string; path: string; kind?: "text" | "textarea" | "media" };
const f = (id: string, label: string, path: string, kind: Spec["kind"] = "text"): Spec => ({ id, label, path, kind });
const specs: Record<PawhausGroomingStudioNativeSectionId, Spec[]> = {
  hero: [f("brand", "Бренд", "brand"), f("eyebrow", "Надзаголовок", "hero.eyebrow"), f("title", "Заголовок", "hero.title", "textarea"), f("text", "Описание", "hero.text", "textarea"), f("hero-media", "Медиа обложки", "hero.image", "media"), f("primary", "Основная кнопка", "hero.primaryLabel")],
  services: [f("title", "Заголовок", "services.0.title"), ...DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.services.flatMap((_, i) => [f(`service-${i}-title`, `Услуга ${i + 1}`, `services.${i}.title`), f(`service-${i}-price`, `Цена ${i + 1}`, `services.${i}.price`), f(`service-${i}-media`, `Медиа услуги ${i + 1}`, `services.${i}.image`, "media")])],
  "before-after": [f("title", "Заголовок", "beforeAfter.title", "textarea"), f("text", "Описание", "beforeAfter.text", "textarea"), f("before-media", "Медиа до", "beforeAfter.beforeImage", "media"), f("after-media", "Медиа после", "beforeAfter.afterImage", "media")],
  groomers: DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.groomers.flatMap((_, i) => [f(`groomer-${i}-name`, `Грумер ${i + 1}`, `groomers.${i}.title`), f(`groomer-${i}-specialty`, `Специализация ${i + 1}`, `groomers.${i}.text`), f(`groomer-${i}-media`, `Медиа грумера ${i + 1}`, `groomers.${i}.image`, "media")]),
  process: DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.process.map((_, i) => f(`step-${i}`, `Шаг ${i + 1}`, `process.${i}.text`, "textarea")),
  packages: DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.packages.flatMap((_, i) => [f(`package-${i}-name`, `Пакет ${i + 1}`, `packages.${i}.title`), f(`package-${i}-price`, `Цена ${i + 1}`, `packages.${i}.price`), f(`package-${i}-media`, `Медиа пакета ${i + 1}`, `packages.${i}.image`, "media")]),
  gallery: [f("title", "Заголовок", "gallery.title"), ...DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.gallery.images.map((_, i) => f(`gallery-${i}`, `Галерея ${i + 1}`, `gallery.images.${i}`, "media"))],
  testimonials: DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.testimonials.map((_, i) => f(`testimonial-${i}`, `Отзыв ${i + 1}`, `testimonials.${i}.text`, "textarea")),
  booking: [f("title", "Заголовок", "booking.title", "textarea"), f("text", "Описание", "booking.text", "textarea")],
  faq: DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.faq.map((_, i) => f(`faq-${i}`, `Вопрос ${i + 1}`, `faq.${i}.title`)),
  contact: [f("title", "Адрес", "contact.title"), f("text", "Контакты", "contact.text")],
  footer: [f("title", "Название", "footer.title"), f("text", "Описание", "footer.text", "textarea"), ...DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT.footer.navigation.flatMap((_, i) => [f(`footer-nav-${i}-label`, `Навигация ${i + 1}`, `footer.navigation.${i}.title`), f(`footer-nav-${i}-link`, `Ссылка ${i + 1}`, `footer.navigation.${i}.text`)]), f("contact-address", "Адрес контактов", "footer.contact.title"), f("contact-details", "Контактные данные", "footer.contact.text", "textarea"), f("cta", "Кнопка записи", "footer.cta.title"), f("copyright", "Копирайт", "footer.copyright"), f("credit", "Подпись OneStudio", "footer.credit")],
};
const get = (root: unknown, path: string): unknown => path.split(".").reduce((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, root);
const set = (root: PawhausGroomingStudioContent, path: string, value: string) => { const next = structuredClone(root) as unknown as Record<string, unknown>; const keys = path.split("."); let target = next; for (const key of keys.slice(0, -1)) target = target[key] as Record<string, unknown>; target[keys.at(-1)!] = value; return next as unknown as PawhausGroomingStudioContent; };
export function buildPawhausGroomingStudioInspectorFields(content: PawhausGroomingStudioContent, section: PawhausGroomingStudioNativeSectionId, disabled: boolean, onChange: (next: PawhausGroomingStudioContent, group: string) => void, onChooseMedia?: (target: PremiumTemplateEditorMediaTarget) => void): EditorInspectorPlacedField[] { return specs[section].map((spec) => { const value = String(get(content, spec.path) ?? ""); const originalValue = String(get(DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT, spec.path) ?? ""); const update = (next: string) => onChange(set(content, spec.path, next), `pawhaus:${section}:${spec.id}`); if (spec.kind === "media") return { id: spec.id, group: "media" as const, type: "media" as const, label: spec.label, value, originalValue, disabled, onChange: update, onChoose: () => onChooseMedia?.({ kind: "template-content", templateKey: "pawhaus-grooming-studio", path: spec.path, label: spec.label }) }; return { id: spec.id, group: "content" as const, type: spec.kind === "textarea" ? "textarea" as const : "text" as const, label: spec.label, ...(spec.kind === "textarea" ? { rows: 3 } : {}), value, originalValue, disabled, onChange: update }; }) as EditorInspectorPlacedField[]; }
export function resetPawhausGroomingStudioSection(content: PawhausGroomingStudioContent, section: PawhausGroomingStudioNativeSectionId) { let next = structuredClone(content); for (const spec of specs[section]) next = set(next, spec.path, String(get(DEFAULT_PAWHAUS_GROOMING_STUDIO_CONTENT, spec.path) ?? "")); const headingTypography = { ...next.headingTypography }; delete headingTypography[section]; return { ...next, headingTypography }; }
