// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { createPremiumTemplateManifestLookup, validatePremiumTemplateManifests, type PremiumTemplatePackageManifest } from "./premium-template-package.ts";

export const PREMIUM_TEMPLATE_PACKAGE_MANIFESTS = [
  {
    "packageVersion": "1.0",
    "templateKey": "gloss-nail-studio",
    "name": "GLOSS",
    "description": "Полный editorial-сайт nail-студии с записью, командой, клубом и портфолио.",
    "category": "beauty",
    "aliases": [
      "gloss"
    ],
    "library": {
      "tier": "standard",
      "visible": true,
      "order": 10
    },
    "preview": {
      "collectionVisible": true,
      "group": "beauty",
      "order": 10,
      "title": {
        "ru": "Nail-студия",
        "en": "Nail studio"
      },
      "description": {
        "ru": "Полный editorial-сайт nail-студии с записью, командой, клубом и портфолио.",
        "en": "An editorial nail studio website with booking, team, club and portfolio."
      },
      "alt": {
        "ru": "Интерьер и работы nail-студии GLOSS",
        "en": "GLOSS nail studio interior and work"
      },
      "route": "/demos/gloss-nail-studio",
      "image": "/templates/gloss/gloss-hero.webp",
      "accent": "#9d3151",
      "dark": "#321722",
      "surface": "#fff7f5"
    },
    "persistence": {
      "schemaVersion": "1.0",
      "compatibleSince": "gloss-1.0",
      "contentNamespace": false
    },
    "capabilities": {
      "customerCreatable": true,
      "editorSelectable": true,
      "previewRenderable": true,
      "publicHome": true,
      "customPages": true,
      "seoMetadata": true,
      "nativeSections": true,
      "customBlocks": true
    },
    "nativeSectionIds": [
      "services",
      "portfolio",
      "team",
      "booking",
      "membership",
      "safety",
      "reviews",
      "gift",
      "faq",
      "about",
      "contact"
    ],
    "assets": [
      "/templates/gloss/gloss-hero.webp",
      "/templates/gloss/gloss-gallery-1.webp"
    ]
  },
  {
    "packageVersion": "1.0",
    "templateKey": "premium-studio",
    "name": "NOIR FRAME — Premium Photo Studio",
    "description": "Премиальная фотостудия с portfolio viewer, 3D-туром и before/after.",
    "category": "studio",
    "aliases": [
      "noir",
      "noir-frame"
    ],
    "library": {
      "tier": "premium",
      "visible": true,
      "order": 30
    },
    "preview": {
      "collectionVisible": true,
      "group": "studio",
      "order": 30,
      "title": {
        "ru": "Фотостудия",
        "en": "Photo studio"
      },
      "description": {
        "ru": "Премиальная фотостудия с portfolio viewer, 3D-туром и before/after.",
        "en": "A premium photo studio with a portfolio viewer, 3D tour and before/after."
      },
      "alt": {
        "ru": "Светлый зал фотостудии NOIR FRAME",
        "en": "Bright NOIR FRAME photo studio"
      },
      "route": "/demos/premium-studio",
      "image": "/images/demos/premium-studio/bright/hero.webp",
      "accent": "#b58b57",
      "dark": "#111111",
      "surface": "#f3efe8"
    },
    "persistence": {
      "schemaVersion": "1.0",
      "compatibleSince": "noir-phase-1",
      "contentNamespace": true
    },
    "capabilities": {
      "customerCreatable": true,
      "editorSelectable": true,
      "previewRenderable": true,
      "publicHome": true,
      "customPages": true,
      "seoMetadata": true,
      "nativeSections": true,
      "customBlocks": true
    },
    "nativeSectionIds": [
      "hero",
      "manifest",
      "light",
      "services",
      "portfolio",
      "retouch",
      "film",
      "team",
      "process",
      "equipment",
      "tour",
      "reviews",
      "faq",
      "contact",
      "footer"
    ],
    "assets": [
      "/images/demos/premium-studio/bright/hero.webp"
    ]
  },
  {
    "packageVersion": "1.0",
    "templateKey": "velora-event-venue",
    "name": "VELORA HOUSE",
    "description": "Премиальная event-площадка с проверкой даты, выбором зала, пакета и заявкой.",
    "category": "events",
    "aliases": [
      "velora",
      "velora-house"
    ],
    "library": {
      "tier": "premium",
      "visible": true,
      "order": 40
    },
    "preview": {
      "collectionVisible": true,
      "group": "events",
      "order": 40,
      "title": {
        "ru": "Площадка для событий",
        "en": "Private event venue"
      },
      "description": {
        "ru": "Свадьбы, частные ужины и корпоративные события в трёх выразительных залах.",
        "en": "Weddings, private dinners and corporate events across three distinctive halls."
      },
      "alt": {
        "ru": "Вечерний зал VELORA HOUSE",
        "en": "VELORA HOUSE event hall at night"
      },
      "route": "/demos/velora-event-venue",
      "image": "/templates/velora/hero.svg",
      "accent": "#C6A66B",
      "dark": "#101827",
      "surface": "#F4EFE6"
    },
    "persistence": {
      "schemaVersion": "1.0",
      "compatibleSince": "velora-1.0",
      "contentNamespace": true
    },
    "capabilities": {
      "customerCreatable": true,
      "editorSelectable": true,
      "previewRenderable": true,
      "publicHome": true,
      "customPages": true,
      "seoMetadata": true,
      "nativeSections": true,
      "customBlocks": true
    },
    "nativeSectionIds": [
      "hero",
      "availability",
      "venues",
      "formats",
      "packages",
      "gallery",
      "catering",
      "planner",
      "facts",
      "reviews",
      "faq",
      "contact",
      "footer"
    ],
    "assets": [
      "/templates/velora/hero.svg",
      "/templates/velora/grand-hall.svg",
      "/templates/velora/garden-hall.svg",
      "/templates/velora/private-salon.svg"
    ]
  }
] as const satisfies readonly PremiumTemplatePackageManifest[];
export const PREMIUM_TEMPLATE_PACKAGES = PREMIUM_TEMPLATE_PACKAGE_MANIFESTS;
export type PremiumTemplateKey = (typeof PREMIUM_TEMPLATE_PACKAGE_MANIFESTS)[number]["templateKey"];
const errors = validatePremiumTemplateManifests(PREMIUM_TEMPLATE_PACKAGE_MANIFESTS);
if (errors.length) throw new Error(`Invalid Premium Template Package catalog: ${errors.join("; ")}`);
export const getPremiumTemplatePackage = createPremiumTemplateManifestLookup(PREMIUM_TEMPLATE_PACKAGE_MANIFESTS);
