// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { createBloomFloralStudioPremiumTemplateSeed as PACKAGE_0_SEED } from "./bloom-floral-studio-premium-template-seed.ts";
import { createPawhausGroomingStudioPremiumTemplateSeed as PACKAGE_1_SEED } from "./pawhaus-grooming-studio-premium-template-seed.ts";
import { createRitmoDanceStudioPremiumTemplateSeed as PACKAGE_2_SEED } from "./ritmo-dance-studio-premium-template-seed.ts";
import { createAlignPilatesPremiumTemplateSeed as PACKAGE_3_SEED } from "./align-pilates-premium-template-seed.ts";
import { createGlossPremiumTemplateSeed as PACKAGE_4_SEED } from "./gloss-premium-template-seed.ts";
import { createNoirPremiumTemplateSeed as PACKAGE_5_SEED } from "./noir-premium-template-seed.ts";
import { createVeloraPremiumTemplateSeed as PACKAGE_6_SEED } from "./velora-premium-template-seed.ts";
import { createVowPremiumTemplateSeed as PACKAGE_7_SEED } from "./vow-premium-template-seed.ts";
import { createLumeaPremiumTemplateSeed as PACKAGE_8_SEED } from "./lumea-premium-template-seed.ts";
import { createRastemCenterPremiumTemplateSeed as PACKAGE_9_SEED } from "./rastem-center-premium-template-seed.ts";
import { createBlacklineTattooPremiumTemplateSeed as PACKAGE_10_SEED } from "./blackline-tattoo-premium-template-seed.ts";
import type { PremiumTemplateSeedFactory } from "./premium-template-seed-factory.ts";

const factories = {
  "bloom-floral-studio": PACKAGE_0_SEED,
  "pawhaus-grooming-studio": PACKAGE_1_SEED,
  "ritmo-dance-studio": PACKAGE_2_SEED,
  "align-pilates-studio": PACKAGE_3_SEED,
  "gloss-nail-studio": PACKAGE_4_SEED,
  "premium-studio": PACKAGE_5_SEED,
  "velora-event-venue": PACKAGE_6_SEED,
  "vow-films": PACKAGE_7_SEED,
  "lumea-beauty": PACKAGE_8_SEED,
  "rastem-center": PACKAGE_9_SEED,
  "blackline-tattoo": PACKAGE_10_SEED,
} satisfies Record<string, PremiumTemplateSeedFactory>;
export function getPremiumTemplateSeedFactory(templateKey: string | null | undefined) { return templateKey ? factories[templateKey as keyof typeof factories] : undefined; }
