// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { ALIGN_PILATES_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_0_CONTRACT } from "./align-pilates-premium-template-contract.ts";
import { GLOSS_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_1_CONTRACT } from "./gloss-premium-template-contract.ts";
import { NOIR_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_2_CONTRACT } from "./noir-premium-template-contract.ts";
import { VELORA_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_3_CONTRACT } from "./velora-premium-template-contract.ts";
import { VOW_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_4_CONTRACT } from "./vow-premium-template-contract.ts";
import { LUMEA_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_5_CONTRACT } from "./lumea-premium-template-contract.ts";
import { createPremiumTemplateContractRegistry } from "./premium-template-registry-builder.ts";

export const { contracts: PREMIUM_TEMPLATE_DEFINITIONS, get: getPremiumTemplateDefinition } = createPremiumTemplateContractRegistry(Object.values({
  "align-pilates-studio": PACKAGE_0_CONTRACT,
  "gloss-nail-studio": PACKAGE_1_CONTRACT,
  "premium-studio": PACKAGE_2_CONTRACT,
  "velora-event-venue": PACKAGE_3_CONTRACT,
  "vow-films": PACKAGE_4_CONTRACT,
  "lumea-beauty": PACKAGE_5_CONTRACT,
}));
