// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { ALIGN_PILATES_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_0_EDITOR } from "./align-pilates-premium-template-editor-adapter.ts";
import { GLOSS_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_1_EDITOR } from "./gloss-premium-template-editor-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_2_EDITOR } from "./noir-premium-template-editor-adapter.ts";
import { VELORA_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_3_EDITOR } from "./velora-premium-template-editor-adapter.ts";
import { VOW_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_4_EDITOR } from "./vow-premium-template-editor-adapter.ts";
import { LUMEA_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_5_EDITOR } from "./lumea-premium-template-editor-adapter.ts";
import { createPremiumTemplateEditorRegistry } from "./premium-template-editor-registry-builder.ts";
export { validatePremiumTemplateEditorAdapterRegistry } from "./premium-template-editor-registry-builder.ts";
import { getPremiumTemplateDefinition } from "./premium-template-registry.ts";

export const { adapters: PREMIUM_TEMPLATE_EDITOR_ADAPTERS, get: getPremiumTemplateEditorAdapter } = createPremiumTemplateEditorRegistry(Object.values({
  "align-pilates-studio": PACKAGE_0_EDITOR,
  "gloss-nail-studio": PACKAGE_1_EDITOR,
  "premium-studio": PACKAGE_2_EDITOR,
  "velora-event-venue": PACKAGE_3_EDITOR,
  "vow-films": PACKAGE_4_EDITOR,
  "lumea-beauty": PACKAGE_5_EDITOR,
}), getPremiumTemplateDefinition);
