// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_0_EDITOR } from "./bloom-floral-studio-premium-template-editor-adapter.ts";
import { PAWHAUS_GROOMING_STUDIO_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_1_EDITOR } from "./pawhaus-grooming-studio-premium-template-editor-adapter.ts";
import { RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_2_EDITOR } from "./ritmo-dance-studio-premium-template-editor-adapter.ts";
import { ALIGN_PILATES_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_3_EDITOR } from "./align-pilates-premium-template-editor-adapter.ts";
import { GLOSS_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_4_EDITOR } from "./gloss-premium-template-editor-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_5_EDITOR } from "./noir-premium-template-editor-adapter.ts";
import { VELORA_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_6_EDITOR } from "./velora-premium-template-editor-adapter.ts";
import { VOW_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_7_EDITOR } from "./vow-premium-template-editor-adapter.ts";
import { LUMEA_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_8_EDITOR } from "./lumea-premium-template-editor-adapter.ts";
import { RASTEM_CENTER_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_9_EDITOR } from "./rastem-center-premium-template-editor-adapter.ts";
import { BLACKLINE_TATTOO_PREMIUM_TEMPLATE_EDITOR_ADAPTER as PACKAGE_10_EDITOR } from "./blackline-tattoo-premium-template-editor-adapter.ts";
import { createPremiumTemplateEditorRegistry } from "./premium-template-editor-registry-builder.ts";
export { validatePremiumTemplateEditorAdapterRegistry } from "./premium-template-editor-registry-builder.ts";
import { getPremiumTemplateDefinition } from "./premium-template-registry.ts";

export const { adapters: PREMIUM_TEMPLATE_EDITOR_ADAPTERS, get: getPremiumTemplateEditorAdapter } = createPremiumTemplateEditorRegistry(Object.values({
  "bloom-floral-studio": PACKAGE_0_EDITOR,
  "pawhaus-grooming-studio": PACKAGE_1_EDITOR,
  "ritmo-dance-studio": PACKAGE_2_EDITOR,
  "align-pilates-studio": PACKAGE_3_EDITOR,
  "gloss-nail-studio": PACKAGE_4_EDITOR,
  "premium-studio": PACKAGE_5_EDITOR,
  "velora-event-venue": PACKAGE_6_EDITOR,
  "vow-films": PACKAGE_7_EDITOR,
  "lumea-beauty": PACKAGE_8_EDITOR,
  "rastem-center": PACKAGE_9_EDITOR,
  "blackline-tattoo": PACKAGE_10_EDITOR,
}), getPremiumTemplateDefinition);
