// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { ALIGN_PILATES_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_0_CUSTOMPAGE } from "./align-pilates-premium-template-custom-page-runtime-adapter.ts";
import { GLOSS_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_1_CUSTOMPAGE } from "./gloss-premium-template-custom-page-runtime-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_2_CUSTOMPAGE } from "./noir-premium-template-custom-page-runtime-adapter.ts";
import { VELORA_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_3_CUSTOMPAGE } from "./velora-premium-template-custom-page-runtime-adapter.ts";
import { VOW_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_4_CUSTOMPAGE } from "./vow-premium-template-custom-page-runtime-adapter.ts";
import { LUMEA_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_5_CUSTOMPAGE } from "./lumea-premium-template-custom-page-runtime-adapter.ts";
import { createPremiumTemplateCustomPageRuntimeRegistry } from "./premium-template-custom-page-runtime-registry-builder.ts";
import { getPremiumTemplateDefinition, PREMIUM_TEMPLATE_DEFINITIONS } from "./premium-template-registry.ts";

export const { runtimes: PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTERS, get: getPremiumTemplateCustomPageRuntime } = createPremiumTemplateCustomPageRuntimeRegistry(Object.values({
  "align-pilates-studio": PACKAGE_0_CUSTOMPAGE,
  "gloss-nail-studio": PACKAGE_1_CUSTOMPAGE,
  "premium-studio": PACKAGE_2_CUSTOMPAGE,
  "velora-event-venue": PACKAGE_3_CUSTOMPAGE,
  "vow-films": PACKAGE_4_CUSTOMPAGE,
  "lumea-beauty": PACKAGE_5_CUSTOMPAGE,
}), PREMIUM_TEMPLATE_DEFINITIONS, getPremiumTemplateDefinition);
