// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_0_PUBLICHOME } from "./bloom-floral-studio-premium-template-runtime-adapter.ts";
import { PAWHAUS_GROOMING_STUDIO_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_1_PUBLICHOME } from "./pawhaus-grooming-studio-premium-template-runtime-adapter.ts";
import { RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_2_PUBLICHOME } from "./ritmo-dance-studio-premium-template-runtime-adapter.ts";
import { ALIGN_PILATES_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_3_PUBLICHOME } from "./align-pilates-premium-template-runtime-adapter.ts";
import { GLOSS_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_4_PUBLICHOME } from "./gloss-premium-template-runtime-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_5_PUBLICHOME } from "./noir-premium-template-runtime-adapter.ts";
import { VELORA_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_6_PUBLICHOME } from "./velora-premium-template-runtime-adapter.ts";
import { VOW_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_7_PUBLICHOME } from "./vow-premium-template-runtime-adapter.ts";
import { LUMEA_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_8_PUBLICHOME } from "./lumea-premium-template-runtime-adapter.ts";
import { RASTEM_CENTER_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_9_PUBLICHOME } from "./rastem-center-premium-template-runtime-adapter.ts";
import { BLACKLINE_TATTOO_PREMIUM_TEMPLATE_RUNTIME_ADAPTER as PACKAGE_10_PUBLICHOME } from "./blackline-tattoo-premium-template-runtime-adapter.ts";
import { createPremiumTemplatePublicRuntimeRegistry } from "./premium-template-runtime-registry-builder.ts";
import { getPremiumTemplateDefinition, PREMIUM_TEMPLATE_DEFINITIONS } from "./premium-template-registry.ts";

export const { runtimes: PREMIUM_TEMPLATE_RUNTIME_ADAPTERS, get: getPremiumTemplatePublicRuntime } = createPremiumTemplatePublicRuntimeRegistry(Object.values({
  "bloom-floral-studio": PACKAGE_0_PUBLICHOME,
  "pawhaus-grooming-studio": PACKAGE_1_PUBLICHOME,
  "ritmo-dance-studio": PACKAGE_2_PUBLICHOME,
  "align-pilates-studio": PACKAGE_3_PUBLICHOME,
  "gloss-nail-studio": PACKAGE_4_PUBLICHOME,
  "premium-studio": PACKAGE_5_PUBLICHOME,
  "velora-event-venue": PACKAGE_6_PUBLICHOME,
  "vow-films": PACKAGE_7_PUBLICHOME,
  "lumea-beauty": PACKAGE_8_PUBLICHOME,
  "rastem-center": PACKAGE_9_PUBLICHOME,
  "blackline-tattoo": PACKAGE_10_PUBLICHOME,
}), PREMIUM_TEMPLATE_DEFINITIONS, getPremiumTemplateDefinition);
