// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { GLOSS_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_0_CUSTOMPAGE } from "./gloss-premium-template-custom-page-runtime-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_1_CUSTOMPAGE } from "./noir-premium-template-custom-page-runtime-adapter.ts";
import { createPremiumTemplateCustomPageRuntimeRegistry } from "./premium-template-custom-page-runtime-registry-builder.ts";
import { getPremiumTemplateDefinition, PREMIUM_TEMPLATE_DEFINITIONS } from "./premium-template-registry.ts";

export const { runtimes: PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTERS, get: getPremiumTemplateCustomPageRuntime } = createPremiumTemplateCustomPageRuntimeRegistry(Object.values({
  "gloss-nail-studio": PACKAGE_0_CUSTOMPAGE,
  "premium-studio": PACKAGE_1_CUSTOMPAGE,
}), PREMIUM_TEMPLATE_DEFINITIONS, getPremiumTemplateDefinition);
