// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_0_CONTRACT } from "./bloom-floral-studio-premium-template-contract.ts";
import { PAWHAUS_GROOMING_STUDIO_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_1_CONTRACT } from "./pawhaus-grooming-studio-premium-template-contract.ts";
import { RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_2_CONTRACT } from "./ritmo-dance-studio-premium-template-contract.ts";
import { ALIGN_PILATES_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_3_CONTRACT } from "./align-pilates-premium-template-contract.ts";
import { GLOSS_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_4_CONTRACT } from "./gloss-premium-template-contract.ts";
import { NOIR_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_5_CONTRACT } from "./noir-premium-template-contract.ts";
import { VELORA_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_6_CONTRACT } from "./velora-premium-template-contract.ts";
import { VOW_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_7_CONTRACT } from "./vow-premium-template-contract.ts";
import { LUMEA_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_8_CONTRACT } from "./lumea-premium-template-contract.ts";
import { RASTEM_CENTER_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_9_CONTRACT } from "./rastem-center-premium-template-contract.ts";
import { BLACKLINE_TATTOO_PREMIUM_TEMPLATE_CONTRACT as PACKAGE_10_CONTRACT } from "./blackline-tattoo-premium-template-contract.ts";
import { createPremiumTemplateContractRegistry } from "./premium-template-registry-builder.ts";

export const { contracts: PREMIUM_TEMPLATE_DEFINITIONS, get: getPremiumTemplateDefinition } = createPremiumTemplateContractRegistry(Object.values({
  "bloom-floral-studio": PACKAGE_0_CONTRACT,
  "pawhaus-grooming-studio": PACKAGE_1_CONTRACT,
  "ritmo-dance-studio": PACKAGE_2_CONTRACT,
  "align-pilates-studio": PACKAGE_3_CONTRACT,
  "gloss-nail-studio": PACKAGE_4_CONTRACT,
  "premium-studio": PACKAGE_5_CONTRACT,
  "velora-event-venue": PACKAGE_6_CONTRACT,
  "vow-films": PACKAGE_7_CONTRACT,
  "lumea-beauty": PACKAGE_8_CONTRACT,
  "rastem-center": PACKAGE_9_CONTRACT,
  "blackline-tattoo": PACKAGE_10_CONTRACT,
}));
