// Generated by scripts/generate-premium-template-packages.mjs. Do not edit.
import { BLOOM_FLORAL_STUDIO_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_0_CUSTOMPAGE } from "./bloom-floral-studio-premium-template-custom-page-runtime-adapter.ts";
import { PAWHAUS_GROOMING_STUDIO_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_1_CUSTOMPAGE } from "./pawhaus-grooming-studio-premium-template-custom-page-runtime-adapter.ts";
import { RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_2_CUSTOMPAGE } from "./ritmo-dance-studio-premium-template-custom-page-runtime-adapter.ts";
import { ALIGN_PILATES_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_3_CUSTOMPAGE } from "./align-pilates-premium-template-custom-page-runtime-adapter.ts";
import { GLOSS_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_4_CUSTOMPAGE } from "./gloss-premium-template-custom-page-runtime-adapter.ts";
import { NOIR_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_5_CUSTOMPAGE } from "./noir-premium-template-custom-page-runtime-adapter.ts";
import { VELORA_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_6_CUSTOMPAGE } from "./velora-premium-template-custom-page-runtime-adapter.ts";
import { VOW_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_7_CUSTOMPAGE } from "./vow-premium-template-custom-page-runtime-adapter.ts";
import { LUMEA_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_8_CUSTOMPAGE } from "./lumea-premium-template-custom-page-runtime-adapter.ts";
import { RASTEM_CENTER_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_9_CUSTOMPAGE } from "./rastem-center-premium-template-custom-page-runtime-adapter.ts";
import { BLACKLINE_TATTOO_PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTER as PACKAGE_10_CUSTOMPAGE } from "./blackline-tattoo-premium-template-custom-page-runtime-adapter.ts";
import { createPremiumTemplateCustomPageRuntimeRegistry } from "./premium-template-custom-page-runtime-registry-builder.ts";
import { getPremiumTemplateDefinition, PREMIUM_TEMPLATE_DEFINITIONS } from "./premium-template-registry.ts";

export const { runtimes: PREMIUM_TEMPLATE_CUSTOM_PAGE_RUNTIME_ADAPTERS, get: getPremiumTemplateCustomPageRuntime } = createPremiumTemplateCustomPageRuntimeRegistry(Object.values({
  "bloom-floral-studio": PACKAGE_0_CUSTOMPAGE,
  "pawhaus-grooming-studio": PACKAGE_1_CUSTOMPAGE,
  "ritmo-dance-studio": PACKAGE_2_CUSTOMPAGE,
  "align-pilates-studio": PACKAGE_3_CUSTOMPAGE,
  "gloss-nail-studio": PACKAGE_4_CUSTOMPAGE,
  "premium-studio": PACKAGE_5_CUSTOMPAGE,
  "velora-event-venue": PACKAGE_6_CUSTOMPAGE,
  "vow-films": PACKAGE_7_CUSTOMPAGE,
  "lumea-beauty": PACKAGE_8_CUSTOMPAGE,
  "rastem-center": PACKAGE_9_CUSTOMPAGE,
  "blackline-tattoo": PACKAGE_10_CUSTOMPAGE,
}), PREMIUM_TEMPLATE_DEFINITIONS, getPremiumTemplateDefinition);
