import type { PublicSiteContent, PublicSiteTypography } from "./types.ts";
import { replaceTemplateContentPreservingEditorState } from "./template-native-section-state.ts";
import type { RastemCenterNativeSectionId } from "./rastem-center-premium-template-contract.ts";

export const RASTEM_CENTER_TEMPLATE_KEY = "rastem-center" as const;
export type RastemTone = "blue" | "yellow" | "coral" | "aqua" | "mint";
export type RastemCenterSection = { eyebrow: string; title: string; text: string };
export type RastemCenterContent = {
  version: 1;
  headingTypography: Partial<Record<RastemCenterNativeSectionId, PublicSiteTypography>>;
  brand: string;
  brandNote: string;
  promo: string;
  navigation: { label: string; href: string }[];
  hero: RastemCenterSection & { primaryLabel: string; primaryUrl: string; secondaryLabel: string; secondaryUrl: string; facts: string[]; image: string; imageAlt: string };
  ages: RastemCenterSection & { items: { label: string; note: string; image: string; tone: RastemTone }[] };
  programs: RastemCenterSection & { items: { title: string; note: string; icon: string; image: string; tone: RastemTone }[] };
  schedule: RastemCenterSection & { filters: string[]; items: { day: string; time: string; title: string; age: string; seats: string }[]; buttonLabel: string; buttonUrl: string };
  teachers: RastemCenterSection & { items: { name: string; role: string; image: string }[] };
  trial: RastemCenterSection & { buttonLabel: string; note: string; ages: string[]; programs: string[]; times: string[] };
  benefits: RastemCenterSection & { items: { title: string; text: string; icon: string }[] };
  memberships: RastemCenterSection & { items: { title: string; price: string; text: string; tone: RastemTone }[] };
  parents: RastemCenterSection & { linkLabel: string; linkUrl: string; phoneTitle: string; phoneClass: string; phoneTime: string; phoneNote: string; phoneNext: string };
  gallery: RastemCenterSection & { images: string[] };
  testimonials: RastemCenterSection & { items: { quote: string; author: string; age: string }[] };
  faq: RastemCenterSection & { items: { question: string; answer: string }[] };
  contact: RastemCenterSection & { hoursLabel: string; hours: string; addressLabel: string; address: string; phone: string; email: string; buttonLabel: string; buttonUrl: string };
  footer: { description: string; address: string; credit: string; phone: string; email: string; navigationLabel: string; navigation: { label: string; href: string }[]; parentLabel: string; parentLinks: { label: string; href: string }[]; ctaLabel: string; ctaUrl: string };
};

const image = (name: string) => `/templates/rastem-center/${name}`;

export const DEFAULT_RASTEM_CENTER_CONTENT: RastemCenterContent = {
  version: 1, headingTypography: {}, brand: "РАСТЁМ", brandNote: "ЦЕНТР РАЗВИТИЯ", promo: "★  Пробная неделя для новых семей — бесплатно",
  navigation: [{ label: "Программы", href: "#programs" }, { label: "Возраст", href: "#ages" }, { label: "Расписание", href: "#schedule" }, { label: "Педагоги", href: "#teachers" }, { label: "Родителям", href: "#parents" }, { label: "Контакты", href: "#contact" }],
  hero: { eyebrow: "ИГРАЕМ · УЧИМСЯ · РАСТЁМ", title: "Место, где интересно быть собой", text: "Бережные занятия для детей от 2 до 10 лет, в маленьких группах, с вниманием к характеру и темпу каждого ребёнка.", primaryLabel: "Подобрать программу", primaryUrl: "#ages", secondaryLabel: "Посмотреть расписание", secondaryUrl: "#schedule", facts: ["Группы до 8 детей", "Опытные педагоги", "Обратная связь родителям"], image: image("hero-platform.webp"), imageAlt: "Педагог занимается с детьми в центре РАСТЁМ" },
  ages: { eyebrow: "ВОЗРАСТ", title: "Занятия по возрасту", text: "Подбираем программу под этап развития, интересы и темп каждого ребёнка.", items: [{ label: "2–3 года", note: "Мама и малыш", image: image("home-learning.webp"), tone: "coral" }, { label: "4–5 лет", note: "Развиваем речь и мышление", image: image("math-manipulatives.webp"), tone: "aqua" }, { label: "6–7 лет", note: "Готовимся к школе", image: image("reading-story.webp"), tone: "blue" }, { label: "8–10 лет", note: "Исследуем и создаём", image: image("science-prism.webp"), tone: "yellow" }] },
  programs: { eyebrow: "ПРОГРАММЫ", title: "Что интересно вашему ребёнку?", text: "Шесть направлений, чтобы пробовать новое, находить своё и расти с удовольствием.", items: [{ title: "Творческая мастерская", note: "Рисуем, лепим, создаём", icon: "✂", image: image("creative-studio.webp"), tone: "aqua" }, { title: "Подготовка к школе", note: "Читаем, считаем, готовимся", icon: "✎", image: image("workbook-cover.webp"), tone: "yellow" }, { title: "Английский через игру", note: "Слушаем, говорим, понимаем", icon: "A", image: image("reading-story.webp"), tone: "mint" }, { title: "Музыка и ритм", note: "Песни, движение, ритм", icon: "♪", image: image("music-motion.webp"), tone: "coral" }, { title: "Маленькие исследователи", note: "Эксперименты, наблюдения", icon: "⌁", image: image("science-prism.webp"), tone: "blue" }, { title: "Логика и конструирование", note: "Строим, решаем, думаем", icon: "▦", image: image("math-manipulatives.webp"), tone: "yellow" }] },
  schedule: { eyebrow: "РАСПИСАНИЕ", title: "Выберите удобную группу", text: "Небольшие группы по будням и выходным — выберите подходящий ритм.", filters: ["Все", "2–3 года", "4–5 лет", "6–7 лет", "8–10 лет"], items: [{ day: "Пн · 10:00", time: "10:00", title: "Мама и малыш", age: "2–3 года", seats: "2 места" }, { day: "Вт · 17:30", time: "17:30", title: "Творческая мастерская", age: "4–5 лет", seats: "4 места" }, { day: "Ср · 18:00", time: "18:00", title: "Подготовка к школе", age: "6–7 лет", seats: "1 место" }, { day: "Сб · 11:00", time: "11:00", title: "Маленькие исследователи", age: "8–10 лет", seats: "3 места" }], buttonLabel: "Всё расписание", buttonUrl: "#trial" },
  teachers: { eyebrow: "КОМАНДА", title: "Педагоги, которым доверяют дети", text: "Внимательные взрослые, которые умеют слышать, поддерживать и увлекать.", items: [{ name: "Анна Светлова", role: "Раннее развитие", image: image("teacher-elena.webp") }, { name: "Мария Добрая", role: "Подготовка к школе", image: image("teacher-jan.webp") }, { name: "Ольга Мир", role: "Творчество и музыка", image: image("collaboration.webp") }] },
  trial: { eyebrow: "ПРОБНОЕ ЗАНЯТИЕ", title: "Познакомимся без спешки", text: "Расскажем о формате, познакомим с педагогом и подберём первую группу для ребёнка.", buttonLabel: "Записаться бесплатно", note: "Подтверждение и напоминание придут на email", ages: ["2–3 года", "4–5 лет", "6–7 лет", "8–10 лет"], programs: ["Творческая мастерская", "Подготовка к школе", "Английский через игру", "Маленькие исследователи"], times: ["10:00", "17:30", "18:00"] },
  benefits: { eyebrow: "ПОЧЕМУ МЫ", title: "Среда, в которой спокойно расти", text: "Всё, что важно ребёнку и родителям каждый день.", items: [{ title: "Безопасное пространство", text: "Продуманная среда и забота о каждом.", icon: "♢" }, { title: "Маленькие группы", text: "До 8 детей, внимание каждому.", icon: "◎" }, { title: "Мягкая адаптация", text: "Постепенно, бережно и без давления.", icon: "✿" }, { title: "Обратная связь", text: "Вы всегда знаете, как прошёл день.", icon: "◌" }] },
  memberships: { eyebrow: "АБОНЕМЕНТЫ", title: "Выберите свой ритм", text: "Простые форматы для регулярных занятий без лишних условий.", items: [{ title: "4 занятия", price: "1 600 ₴", text: "Один раз в неделю", tone: "yellow" }, { title: "8 занятий", price: "2 900 ₴", text: "Два раза в неделю", tone: "aqua" }, { title: "12 занятий", price: "3 900 ₴", text: "Три раза в неделю", tone: "coral" }] },
  parents: { eyebrow: "ДЛЯ РОДИТЕЛЕЙ", title: "Вы всегда знаете, как прошёл день", text: "После занятия педагог оставит короткий комментарий, а система напомнит о следующей встрече.", linkLabel: "Для родителей", linkUrl: "#contact", phoneTitle: "Сегодня в РАСТЁМ", phoneClass: "Творческая мастерская", phoneTime: "10:05–11:00", phoneNote: "Комментарий педагога\n«Сегодня ребёнок придумал целую историю из цвета и формы»", phoneNext: "Следующее занятие\nПн, 27 мая · 10:00" },
  gallery: { eyebrow: "В ЦЕНТРЕ", title: "Обычный день в РАСТЁМ", text: "Смотрим, пробуем, создаём — и радуемся маленьким открытиям.", images: [image("studio-interior.webp"), image("collaboration.webp"), image("creative-studio.webp"), image("math-manipulatives.webp"), image("music-motion.webp"), image("article-math.webp")] },
  testimonials: { eyebrow: "ОТЗЫВЫ", title: "Родители замечают перемены", text: "", items: [{ quote: "Дочка теперь сама просит дома задания и рассказывает, что нового узнала. Для нас это главный результат.", author: "Марина, мама Алисы", age: "группа 6–7 лет" }, { quote: "Очень бережная адаптация. Сын впервые остался без нас и вышел с занятия счастливый.", author: "Ирина, мама Миши", age: "группа 4–5 лет" }, { quote: "Нравится, что педагоги видят не только успехи, но и настроение ребёнка в этот день.", author: "Олег, папа Сони", age: "группа 8–10 лет" }] },
  faq: { eyebrow: "FAQ", title: "Ответы на частые вопросы", text: "", items: [{ question: "Можно прийти без подготовки?", answer: "Да. Занятия рассчитаны на детей с разным уровнем и опытом." }, { question: "Как проходит первое занятие?", answer: "Мы знакомимся, показываем пространство и мягко подключаем ребёнка к группе." }, { question: "Нужно ли родителям оставаться?", answer: "Для малышей можно начать вместе, а дальше педагог подскажет комфортный темп адаптации." }, { question: "Как выбрать программу?", answer: "На пробной встрече мы узнаем интересы ребёнка и предложим подходящие направления." }] },
  contact: { eyebrow: "КОНТАКТЫ", title: "Приходите знакомиться", text: "Напишите нам — ответим на вопросы и подберём удобное время для пробного занятия.", hoursLabel: "ЧАСЫ РАБОТЫ", hours: "Пн–Сб · 09:00–19:00", addressLabel: "МЫ ЗДЕСЬ", address: "ул. Больших открытий, 7 · центр города", phone: "+38 (099) 555-12-34", email: "hello@rastem.demo", buttonLabel: "Записаться на пробное", buttonUrl: "#trial" },
  footer: { description: "Место, где интересно быть собой.", address: "ул. Больших открытий, 7", credit: "Сайт и система управления созданы на OneStudio OS", phone: "+38 (099) 555-12-34", email: "hello@rastem.demo", navigationLabel: "Навигация", navigation: [{ label: "Программы", href: "#programs" }, { label: "Возраст", href: "#ages" }, { label: "Расписание", href: "#schedule" }, { label: "Контакты", href: "#contact" }], parentLabel: "Родителям", parentLinks: [{ label: "Как проходит день", href: "#parents" }, { label: "Адаптация", href: "#parents" }, { label: "Оплата", href: "#memberships" }], ctaLabel: "Записаться на пробное", ctaUrl: "#trial" },
};

export function createRastemCenterEnglishContent(): RastemCenterContent {
  const v = structuredClone(DEFAULT_RASTEM_CENTER_CONTENT);
  v.brandNote = "CHILDREN'S DISCOVERY CENTER"; v.promo = "★  A free trial week for new families";
  v.navigation = [{ label: "Programs", href: "#programs" }, { label: "Ages", href: "#ages" }, { label: "Schedule", href: "#schedule" }, { label: "Teachers", href: "#teachers" }, { label: "For parents", href: "#parents" }, { label: "Contact", href: "#contact" }];
  v.hero = { ...v.hero, eyebrow: "PLAY · LEARN · GROW", title: "A place to be curious and yourself", text: "Thoughtful classes for children aged 2 to 10, in small groups with attention to every child's character and pace.", primaryLabel: "Find a program", secondaryLabel: "View the schedule", facts: ["Groups of up to 8", "Experienced teachers", "Feedback for parents"], imageAlt: "Teacher learning with children at RASTEM" };
  v.ages = { ...v.ages, eyebrow: "AGES", title: "Classes by age", text: "We match each program to a child's stage, interests and pace.", items: [{ label: "2–3 years", note: "Parent and toddler", image: image("home-learning.webp"), tone: "coral" }, { label: "4–5 years", note: "Speech and thinking", image: image("math-manipulatives.webp"), tone: "aqua" }, { label: "6–7 years", note: "Getting ready for school", image: image("reading-story.webp"), tone: "blue" }, { label: "8–10 years", note: "Exploring and creating", image: image("science-prism.webp"), tone: "yellow" }] };
  v.programs = { ...v.programs, eyebrow: "PROGRAMS", title: "What sparks your child's interest?", text: "Six ways to try something new, find a passion and grow with joy.", items: [{ title: "Creative workshop", note: "Drawing, clay and making", icon: "✂", image: image("creative-studio.webp"), tone: "aqua" }, { title: "School readiness", note: "Reading, numbers and confidence", icon: "✎", image: image("workbook-cover.webp"), tone: "yellow" }, { title: "English through play", note: "Listening, speaking and understanding", icon: "A", image: image("reading-story.webp"), tone: "mint" }, { title: "Music and rhythm", note: "Songs, movement and rhythm", icon: "♪", image: image("music-motion.webp"), tone: "coral" }, { title: "Little explorers", note: "Experiments and observation", icon: "⌁", image: image("science-prism.webp"), tone: "blue" }, { title: "Logic and building", note: "Building, solving and thinking", icon: "▦", image: image("math-manipulatives.webp"), tone: "yellow" }] };
  v.schedule = { ...v.schedule, eyebrow: "SCHEDULE", title: "Find the right group", text: "Small weekday and weekend groups for an easy family rhythm.", filters: ["All", "2–3 years", "4–5 years", "6–7 years", "8–10 years"], items: [{ day: "Mon · 10:00", time: "10:00", title: "Parent and toddler", age: "2–3 years", seats: "2 spots" }, { day: "Tue · 17:30", time: "17:30", title: "Creative workshop", age: "4–5 years", seats: "4 spots" }, { day: "Wed · 18:00", time: "18:00", title: "School readiness", age: "6–7 years", seats: "1 spot" }, { day: "Sat · 11:00", time: "11:00", title: "Little explorers", age: "8–10 years", seats: "3 spots" }], buttonLabel: "View full schedule" };
  v.teachers = { ...v.teachers, eyebrow: "TEAM", title: "Teachers children trust", text: "Attentive adults who know how to listen, support and spark curiosity.", items: [{ name: "Anna Svetlova", role: "Early development", image: image("teacher-elena.webp") }, { name: "Maria Dobraya", role: "School readiness", image: image("teacher-jan.webp") }, { name: "Olga Mir", role: "Creative work and music", image: image("collaboration.webp") }] };
  v.trial = { ...v.trial, eyebrow: "TRIAL CLASS", title: "Let's meet without rushing", text: "We will explain the format, introduce the teacher and find the right first group.", buttonLabel: "Book a free trial", note: "Confirmation and a reminder will arrive by email", ages: ["2–3 years", "4–5 years", "6–7 years", "8–10 years"], programs: ["Creative workshop", "School readiness", "English through play", "Little explorers"], times: ["10:00", "17:30", "18:00"] };
  v.benefits = { ...v.benefits, eyebrow: "WHY US", title: "A calm place to grow", text: "Everything children and parents need to feel good each day.", items: [{ title: "A safe space", text: "A thoughtful environment and care for every child.", icon: "♢" }, { title: "Small groups", text: "Up to 8 children, with attention for everyone.", icon: "◎" }, { title: "Gentle settling in", text: "Gradual, kind and without pressure.", icon: "✿" }, { title: "Parent feedback", text: "You always know how the day went.", icon: "◌" }] };
  v.memberships = { ...v.memberships, eyebrow: "MEMBERSHIPS", title: "Choose your rhythm", text: "Simple formats for regular classes without hidden terms.", items: [{ title: "4 classes", price: "UAH 1,600", text: "Once a week", tone: "yellow" }, { title: "8 classes", price: "UAH 2,900", text: "Twice a week", tone: "aqua" }, { title: "12 classes", price: "UAH 3,900", text: "Three times a week", tone: "coral" }] };
  v.parents = { ...v.parents, eyebrow: "FOR PARENTS", title: "You always know how the day went", text: "After class, the teacher leaves a short note and the system reminds you about the next visit.", linkLabel: "For parents", phoneTitle: "Today at RASTEM", phoneClass: "Creative workshop", phoneTime: "10:05–11:00", phoneNote: "Teacher's note\n“Today your child made a whole story from colour and shape.”", phoneNext: "Next class\nMon, May 27 · 10:00" };
  v.gallery = { ...v.gallery, eyebrow: "AT THE CENTER", title: "A regular day at RASTEM", text: "Look, try, create — and celebrate small discoveries." };
  v.testimonials = { ...v.testimonials, eyebrow: "TESTIMONIALS", title: "Parents notice the change", items: [{ quote: "Our daughter now asks for activities at home and tells us what she discovered. That is the best result for us.", author: "Marina, Alice's mother", age: "6–7 years group" }, { quote: "The settling-in process was so gentle. Our son stayed without us for the first time and came out happy.", author: "Irina, Misha's mother", age: "4–5 years group" }, { quote: "I love that teachers notice not only progress, but also how a child feels that day.", author: "Oleg, Sonya's father", age: "8–10 years group" }] };
  v.faq = { ...v.faq, eyebrow: "FAQ", title: "Answers for parents", items: [{ question: "Can we come without prior preparation?", answer: "Yes. Classes are designed for children with different levels and experience." }, { question: "What happens during the first class?", answer: "We meet, show you the space and gently help your child join the group." }, { question: "Do parents need to stay?", answer: "For younger children, you can start together; the teacher will suggest a comfortable pace." }, { question: "How do we choose a program?", answer: "At the trial meeting, we learn about your child's interests and suggest the right options." }] };
  v.contact = { ...v.contact, eyebrow: "CONTACT", title: "Come and meet us", text: "Write to us with your questions and we will find a convenient time for a trial class.", hoursLabel: "OPENING HOURS", hours: "Mon–Sat · 09:00–19:00", addressLabel: "FIND US", address: "7 Big Discoveries Street · city center", buttonLabel: "Book a trial" };
  v.footer = { ...v.footer, description: "A place to be curious and yourself.", address: "7 Big Discoveries Street", credit: "Website and management system by OneStudio OS", navigationLabel: "Navigation", navigation: [{ label: "Programs", href: "#programs" }, { label: "Ages", href: "#ages" }, { label: "Schedule", href: "#schedule" }, { label: "Contact", href: "#contact" }], parentLabel: "For parents", parentLinks: [{ label: "A day at RASTEM", href: "#parents" }, { label: "Settling in", href: "#parents" }, { label: "Payment", href: "#memberships" }], ctaLabel: "Book a trial" };
  return v;
}

export function resolveRastemCenterContent(content: PublicSiteContent): RastemCenterContent { const stored = content.template_content?.[RASTEM_CENTER_TEMPLATE_KEY]; return stored && typeof stored === "object" ? stored as RastemCenterContent : DEFAULT_RASTEM_CENTER_CONTENT; }
export function withRastemCenterContent(content: PublicSiteContent, value: RastemCenterContent, preserve = true): PublicSiteContent { return replaceTemplateContentPreservingEditorState(content, RASTEM_CENTER_TEMPLATE_KEY, value as unknown as Record<string, unknown>, preserve); }
