import type { PublicSiteContent } from "./types.ts";
import { RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_CONTRACT } from "./ritmo-dance-studio-premium-template-contract.ts";
import { createRitmoDanceStudioEnglishContent, DEFAULT_RITMO_DANCE_STUDIO_CONTENT, RITMO_DANCE_STUDIO_TEMPLATE_KEY, withRitmoDanceStudioContent } from "./ritmo-dance-studio-premium-template-content.ts";
export const RITMO_DANCE_STUDIO_NATIVE_LAYOUT_ORDER = RITMO_DANCE_STUDIO_PREMIUM_TEMPLATE_CONTRACT.nativeSections.map(({ id }) => `native:${RITMO_DANCE_STUDIO_TEMPLATE_KEY}:${id}`);
export function createRitmoDanceStudioPremiumTemplateSeed(locale = "ru"): PublicSiteContent {
  const english = locale.toLowerCase().startsWith("en"); const value = english ? createRitmoDanceStudioEnglishContent() : DEFAULT_RITMO_DANCE_STUDIO_CONTENT;
  const base = { template_id: RITMO_DANCE_STUDIO_TEMPLATE_KEY, template_content: { [`${RITMO_DANCE_STUDIO_TEMPLATE_KEY}:locale`]: english ? "en" : "ru" }, brand_name: "RITMO Dance Studio", theme_dark: "#150A26", theme_accent: "#FF5B47", theme_surface: "#F5F0E8", hero_eyebrow: value.hero.eyebrow, hero_title: value.hero.title, hero_text: value.hero.text, about_title: value.gallery.title, about_text: value.membershipsPresentation.text, services_title: value.directionsPresentation.title, portfolio_title: value.coachesPresentation.title, contact_title: value.contact.title, booking_label: value.trial.submit, services_label: english ? "Classes" : "Направления", portfolio_label: english ? "Instructors" : "Тренеры", about_label: english ? "Studio" : "Студия", contact_label: english ? "Contact" : "Контакты", show_services: true, show_portfolio: true, show_about: true, show_contact: true, seo_title: english ? "RITMO Dance Studio — classes for adults" : "RITMO Dance Studio — танцы для взрослых", seo_description: english ? "Dance classes for adults: contemporary, hip-hop, high heels, latina and stretching." : "Танцы для взрослых: contemporary, hip-hop, high heels, latina и stretching.", layout_order: [...RITMO_DANCE_STUDIO_NATIVE_LAYOUT_ORDER], custom_blocks: [], pages: [] } as PublicSiteContent;
  return withRitmoDanceStudioContent(base, value, false);
}
