import type { EditorInspectorPlacedField } from "./editor-spec.ts";
import type { PremiumTemplateEditorMediaTarget } from "./premium-template-editor-adapter.ts";
import type { RitmoDanceStudioContent } from "./ritmo-dance-studio-premium-template-content.ts";
import { DEFAULT_RITMO_DANCE_STUDIO_CONTENT } from "./ritmo-dance-studio-premium-template-content.ts";
import type { RitmoDanceStudioNativeSectionId } from "./ritmo-dance-studio-premium-template-contract.ts";
type Kind = "text" | "textarea" | "richText" | "action" | "media"; type Spec = { id: string; label: string; path: string; kind?: Kind; hrefPath?: string };
const f = (id: string, label: string, path: string, kind: Kind = "text"): Spec => ({ id, label, path, kind }); const a = (id: string, label: string, path: string, hrefPath: string): Spec => ({ id, label, path, hrefPath, kind: "action" });
const items = (path: keyof RitmoDanceStudioContent, count: number, keys: [string, string][]) => Array.from({ length: count }, (_, i) => keys.map(([key, label]) => f(`${String(path)}-${i}-${key}`, `${label} · ${i + 1}`, `${String(path)}.${i}.${key}`, key === "image" ? "media" : "text"))).flat();
export const RITMO_DANCE_STUDIO_EDITOR_SPECS: Record<RitmoDanceStudioNativeSectionId, Spec[]> = {
 hero: [f("promo", "Промо-полоса", "promo"), f("brand", "Название", "brand"), f("brand-note", "Подпись бренда", "brandNote"), ...items("navigation", 5, [["label", "Навигация"], ["href", "Ссылка"]]), a("header-cta", "Кнопка в шапке", "headerCta.label", "headerCta.href"), f("eyebrow", "Надзаголовок", "hero.eyebrow"), f("title", "Главный заголовок", "hero.title", "textarea"), f("text", "Вводный текст", "hero.text", "richText"), a("primary", "Главная кнопка", "hero.primaryLabel", "hero.primaryUrl"), a("secondary", "Вторая кнопка", "hero.secondaryLabel", "hero.secondaryUrl"), f("image", "Фото обложки", "hero.image", "media"), f("image-alt", "Alt-текст", "hero.imageAlt")],
 directions: [f("title", "Заголовок", "directionsPresentation.title", "textarea"), f("text", "Подзаголовок", "directionsPresentation.text", "richText"), ...items("directions", 5, [["name", "Направление"], ["note", "Описание"], ["tag", "Метка"], ["image", "Фото"]])],
 schedule: [f("eyebrow", "Метка", "schedulePresentation.eyebrow"), f("title", "Заголовок", "schedulePresentation.title", "textarea"), a("cta", "Кнопка расписания", "schedulePresentation.cta", "schedulePresentation.ctaUrl"), ...items("schedule", 4, [["day", "День"], ["time", "Время"], ["title", "Класс"], ["coach", "Тренер"], ["seats", "Места"]])],
 coaches: [f("title", "Заголовок", "coachesPresentation.title", "textarea"), f("text", "Подзаголовок", "coachesPresentation.text", "richText"), ...items("coaches", 4, [["name", "Имя"], ["role", "Направление"], ["image", "Фото"]])],
 trial: [f("eyebrow", "Метка", "trial.eyebrow"), f("title", "Заголовок", "trial.title", "textarea"), f("note", "Примечание", "trial.note"), a("submit", "Кнопка формы", "trial.submit", "headerCta.href"), f("image", "Фото пробного урока", "trial.image", "media"), f("image-alt", "Alt-текст", "trial.imageAlt")],
 memberships: [f("eyebrow", "Метка", "membershipsPresentation.eyebrow"), f("title", "Заголовок", "membershipsPresentation.title", "textarea"), f("text", "Описание", "membershipsPresentation.text", "richText"), a("plan-cta", "Кнопка тарифа", "membershipsPresentation.cta", "membershipsPresentation.ctaUrl"), ...items("memberships", 3, [["name", "Название"], ["note", "Условия"], ["price", "Цена"]])],
 gallery: [f("eyebrow", "Метка", "gallery.eyebrow"), f("title", "Заголовок", "gallery.title", "textarea"), ...Array.from({ length: 6 }, (_, index) => f(`image-${index}`, `Фото галереи · ${index + 1}`, `gallery.images.${index}`, "media"))],
 contact: [f("eyebrow", "Метка отзыва", "contact.eyebrow"), f("quote", "Отзыв", "contact.quote", "richText"), f("person", "Автор", "contact.person"), f("image", "Фото автора", "contact.image", "media"), f("image-alt", "Alt-текст", "contact.imageAlt"), f("title", "Часы работы", "contact.title", "textarea"), f("address", "Адрес", "contact.address"), a("cta", "Маршрут", "contact.cta", "contact.ctaUrl")],
 footer: [f("phone", "Телефон", "footer.phone"), f("email", "Email", "footer.email"), f("credit", "Подпись OneStudio", "footer.credit")],
};
const at = (root: unknown, path: string) => path.split(".").reduce<unknown>((v, key) => v && typeof v === "object" ? (v as Record<string, unknown>)[key] : undefined, root);
const set = (content: RitmoDanceStudioContent, path: string, value: string) => { const next = structuredClone(content) as unknown as Record<string, unknown>; const keys = path.split("."); let target = next; for (const key of keys.slice(0, -1)) target = target[key] as Record<string, unknown>; target[keys.at(-1)!] = value; return next as unknown as RitmoDanceStudioContent; };
export function buildRitmoDanceStudioInspectorFields(content: RitmoDanceStudioContent, section: RitmoDanceStudioNativeSectionId, disabled: boolean, onChange: (next: RitmoDanceStudioContent, group: string) => void, onChooseMedia?: (target: PremiumTemplateEditorMediaTarget) => void): EditorInspectorPlacedField[] { const fields = RITMO_DANCE_STUDIO_EDITOR_SPECS[section].map((spec) => { const value = String(at(content, spec.path) ?? ""); const originalValue = String(at(DEFAULT_RITMO_DANCE_STUDIO_CONTENT, spec.path) ?? ""); const update = (next: string) => onChange(set(content, spec.path, next), `ritmo:${section}:${spec.id}`); if (spec.kind === "action" && spec.hrefPath) return { id: spec.id, group: "content" as const, type: "action" as const, label: spec.label, text: value, href: String(at(content, spec.hrefPath) ?? ""), originalText: originalValue, originalHref: String(at(DEFAULT_RITMO_DANCE_STUDIO_CONTENT, spec.hrefPath) ?? ""), disabled, onTextChange: update, onHrefChange: (next: string) => onChange(set(content, spec.hrefPath!, next), `ritmo:${section}:${spec.id}`) }; if (spec.kind === "media") return { id: spec.id, group: "media" as const, type: "media" as const, label: spec.label, value, originalValue, disabled, onChange: update, onChoose: () => onChooseMedia?.({ kind: "template-content", templateKey: "ritmo-dance-studio", path: spec.path, label: spec.label }) }; return spec.kind === "richText" ? { id: spec.id, group: "content" as const, type: "richText" as const, label: spec.label, value, originalValue, disabled, onChange: update } : spec.kind === "textarea" ? { id: spec.id, group: "content" as const, type: "textarea" as const, label: spec.label, rows: 3, value, originalValue, disabled, onChange: update } : { id: spec.id, group: "content" as const, type: "text" as const, label: spec.label, value, originalValue, disabled, onChange: update }; }) as EditorInspectorPlacedField[]; if (section !== "footer") fields.push({ id: `ritmo-${section}-typography`, group: "typography", type: "typography", forFieldId: "title", title: "Оформление заголовка", description: "Главный заголовок раздела", value: content.headingTypography[section], disabled, onChange: (value) => onChange({ ...content, headingTypography: { ...content.headingTypography, [section]: value } }, `ritmo:${section}:typography`) }); return fields; }
export function resetRitmoDanceStudioSection(content: RitmoDanceStudioContent, section: RitmoDanceStudioNativeSectionId) { let next = structuredClone(content); for (const spec of RITMO_DANCE_STUDIO_EDITOR_SPECS[section]) { next = set(next, spec.path, String(at(DEFAULT_RITMO_DANCE_STUDIO_CONTENT, spec.path) ?? "")); if (spec.hrefPath) next = set(next, spec.hrefPath, String(at(DEFAULT_RITMO_DANCE_STUDIO_CONTENT, spec.hrefPath) ?? "")); } const headingTypography = { ...next.headingTypography }; delete headingTypography[section]; return { ...next, headingTypography }; }
