import type { CSSProperties, ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import PublicCustomBlock from "@/components/public/PublicCustomBlock";
import PublicRichHeading from "@/components/public/PublicRichHeading";
import PublicRichText from "@/components/public/PublicRichText";
import { premiumNativeActionKey } from "@/lib/public-site/premium-action-style";
import { ALIGN_PILATES_TEMPLATE_KEY, resolveAlignPilatesContent } from "@/lib/public-site/align-pilates-premium-template-content";
import type { AlignPilatesNativeSectionId } from "@/lib/public-site/align-pilates-premium-template-contract";
import { isTemplateNativeSectionVisible } from "@/lib/public-site/template-native-section-state";
import { createPremiumTemplateRenderPlan } from "@/lib/public-site/premium-template-render-plan";
import { ALIGN_PILATES_PREMIUM_TEMPLATE_CONTRACT } from "@/lib/public-site/align-pilates-premium-template-contract";
import type { PublicSiteData } from "@/lib/public-site/types";
import { publicTypographyStyle } from "@/lib/public-site/typography";
import styles from "./AlignPilates.module.css";

const Arrow = () => <span aria-hidden="true">→</span>;

export default function AlignPilatesSite({ site, basePath }: { site: PublicSiteData; basePath: string }) {
  const content = resolveAlignPilatesContent(site.content);
  const locale = site.business.locale;
  const visible = (id: string) => isTemplateNativeSectionVisible(site.content, ALIGN_PILATES_TEMPLATE_KEY, id);
  const heading = (id: AlignPilatesNativeSectionId) => publicTypographyStyle(content.headingTypography[id]);
  const localizedRoot = locale !== site.business.primary_locale && basePath.endsWith(`/${locale}`) ? basePath.slice(0, -(locale.length + 1)) : basePath;
  const localeHref = (next: string) => next === site.business.primary_locale ? localizedRoot : `${localizedRoot.replace(/\/$/, "")}/${next}`;
  const sections: Record<string, ReactNode> = {
    hero: visible("hero") ? <>
      <section className={styles.hero} id="hero">
        <div className={styles.heroCopy}><p className={styles.eyebrow}>{content.hero.eyebrow}</p><h1 style={{ ...heading("hero"), whiteSpace: "pre-line" }}><PublicRichHeading value={content.hero.title} /></h1><div className={styles.heroText}><PublicRichText value={content.hero.text} /></div><div className={styles.heroActions}><a className={styles.primaryButton} data-premium-action={premiumNativeActionKey("align-pilates-studio", "hero", "primary-action")} href={content.hero.primaryUrl}>{content.hero.primaryLabel}</a><a className={styles.textLink} data-premium-action={premiumNativeActionKey("align-pilates-studio", "hero", "secondary-action")} href={content.hero.secondaryUrl}>{content.hero.secondaryLabel} <Arrow /></a></div><p className={styles.microcopy}>{content.hero.note}</p></div>
        <div className={styles.heroVisual}><Image src={content.hero.image} alt={content.hero.alt} fill priority sizes="(max-width: 820px) 100vw, 55vw" /><div className={styles.heroBadge}><strong>{content.hero.badgeNumber}</strong><span>{content.hero.badgeText}</span></div></div>
      </section>
    </> : null,
    formats: visible("formats") ? <section className={styles.section} id="classes"><div className={styles.sectionHead}><p style={heading("formats")}>{content.formatsPresentation.title}</p><span>{content.formatsPresentation.text}</span></div><div className={styles.formatGrid}>{content.formats.map((item) => <article className={styles.formatCard} key={item.title}><Image src={item.image} alt={item.alt} width={360} height={210} sizes="(max-width: 560px) 44vw, (max-width: 820px) 46vw, 25vw" /><div className={styles.cardBody}><h2>{item.title}</h2><PublicRichText value={item.text} /><span>{item.meta}</span><a href="#trial">{content.formatsPresentation.cta} <Arrow /></a></div></article>)}</div></section> : null,
    benefits: visible("benefits") ? <section className={styles.manifest} id="benefits"><h2 style={heading("benefits")}>{content.benefitsTitle}</h2><div className={styles.benefits}>{content.benefits.map((item) => <div className={styles.benefit} key={item.label}><span className={styles.benefitIcon}>{item.icon}</span><span>{item.label}</span></div>)}</div></section> : null,
    schedule: visible("schedule") ? <section className={styles.section} id="schedule"><div className={styles.schedulePane} style={{ borderRight: 0, paddingRight: 0 }}><p className={styles.kicker}>{content.schedulePresentation.eyebrow}</p><h2 style={heading("schedule")}>{content.schedulePresentation.title}</h2><div className={styles.filters}>{content.scheduleFilters.map((item, i) => <button className={i === 0 ? styles.activeFilter : undefined} type="button" key={item.label}>{item.label}</button>)}</div><div className={styles.scheduleTable}>{content.schedule.map((item) => <div className={styles.scheduleRow} key={`${item.time}-${item.className}`}><span>{item.time}</span><strong>{item.className}</strong><span>{item.trainer}</span><em data-state={item.state}>{item.availability}</em></div>)}</div><a className={styles.outlineButton} href="#trial">{content.schedulePresentation.cta}</a></div></section> : null,
    trainers: visible("trainers") ? <section className={styles.section} id="trainers"><div className={styles.trainersPane} style={{ paddingLeft: 0 }}><h2 style={heading("trainers")}>{content.trainersPresentation.title}</h2><div className={styles.trainerGrid}>{content.trainers.map((item) => <article className={styles.trainerCard} key={item.name}><Image src={item.image} alt={item.alt} width={300} height={410} sizes="(max-width: 560px) 31vw, 30vw" /><div><h3>{item.name}</h3><p>{item.role}</p></div></article>)}</div></div></section> : null,
    trial: visible("trial") ? <section className={styles.trialPane} id="trial"><p className={styles.kicker}>{content.trial.eyebrow}</p><h2 style={heading("trial")}>{content.trial.title}</h2><form className={styles.form}><label><span>{content.trial.formatLabel}</span><select defaultValue=""><option value="" disabled>{content.trial.formatPlaceholder}</option>{content.formats.map((item) => <option key={item.title}>{item.title}</option>)}</select></label><label><span>{content.trial.levelLabel}</span><select defaultValue=""><option value="" disabled>{content.trial.levelPlaceholder}</option><option>{locale === "en" ? "Beginner" : "Начинающий"}</option><option>{locale === "en" ? "Experienced" : "Продолжающий"}</option></select></label><label><span>{content.trial.dateLabel}</span><input type="date" /></label><label><span>{content.trial.timeLabel}</span><input type="time" /></label><button className={styles.primaryButton} type="button">{content.trial.submit}</button></form><p className={styles.formNote}>{content.trial.note}</p></section> : null,
    memberships: visible("memberships") ? <section className={styles.plansPane} id="plans"><h2 style={heading("memberships")}>{content.membershipsPresentation.title}</h2><div className={styles.planGrid}>{content.memberships.map((item, i) => <article className={styles.planCard} data-popular={i === 1 ? "true" : "false"} key={item.name}>{i === 1 ? <span className={styles.popular}>{content.membershipsPresentation.popular}</span> : null}<p>{item.name}</p><strong>{item.price}</strong><span>{content.membershipsPresentation.termPrefix} {item.term}</span><button type="button">{content.membershipsPresentation.cta}</button></article>)}</div></section> : null,
    studio: visible("studio") ? <section className={styles.studio} id="studio"><div className={styles.sectionHeadCentered}><p style={heading("studio")}>{content.studioPresentation.title}</p><span>{content.studioPresentation.text}</span></div><div className={styles.gallery}>{content.studio.map((item) => <Image src={item.image} alt={item.alt} width={320} height={210} sizes="(max-width: 560px) 46vw, 20vw" key={item.image} />)}</div></section> : null,
    testimonial: visible("testimonial") ? <section className={styles.section} id="testimonial"><div className={styles.review} style={{ borderRight: 0 }}><h2 style={heading("testimonial")}>{content.testimonial.title}</h2><blockquote>«{content.testimonial.quote}»</blockquote><p>{content.testimonial.author}</p><div className={styles.dots}><span /><span /><span /><span /></div></div></section> : null,
    faq: visible("faq") ? <section className={styles.section} id="faq"><div className={styles.faq} style={{ paddingLeft: 0 }}><h2 style={heading("faq")}>{content.faqPresentation.title}</h2>{content.faq.map((item) => <details key={item.question}><summary>{item.question}</summary><PublicRichText value={item.answer} /></details>)}</div></section> : null,
    contacts: visible("contacts") ? <section className={styles.contacts} id="contacts"><div className={styles.contactCopy}><p className={styles.kicker}>{content.contacts.eyebrow}</p><h2 style={heading("contacts")}>{content.contacts.title}</h2><p>{content.contacts.hours}</p><p>{content.contacts.address}</p><a className={styles.primaryButton} href="#hero">{content.contacts.cta}</a></div><div className={styles.map}><Image src={content.contacts.image} alt={content.contacts.alt} fill sizes="(max-width: 820px) 100vw, 60vw" /><div className={styles.pin}><span>●</span><strong>{content.brand}</strong><small>{content.brandNote}</small></div></div></section> : null,
    footer: visible("footer") ? <footer className={styles.footer} id="footer"><div className={styles.footerTop}><div className={styles.footerIntro}><a className={styles.footerBrand} href="#hero"><span>{content.brand}</span><small>{content.brandNote}</small></a><PublicRichText value={content.footer.text} /><a className={styles.footerCta} href="#trial">{content.footer.cta} <Arrow /></a></div><nav className={styles.footerNav}><p>{locale === "en" ? "Studio" : "Студия"}</p>{content.navigation.slice(0, 5).map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className={styles.footerContact}><p className={styles.footerLabel}>{content.footer.visit}</p><strong>{content.footer.address}</strong><span>{content.footer.hours}</span><a href={`mailto:${content.footer.email}`}>{content.footer.email}</a><a href={`tel:${content.footer.phone.replace(/\s/g, "")}`}>{content.footer.phone}</a></div><div className={styles.footerSocialBlock}><p className={styles.footerLabel}>{content.footer.social}</p><div className={styles.socials}><a href="#hero">Instagram</a><a href="#hero">Telegram</a><a href="#hero">WhatsApp</a></div></div></div><div className={styles.footerBottom}><span>{content.footer.copyright}</span><div><a href="#hero">{content.footer.privacy}</a><a href="#hero">{content.footer.rules}</a></div><p>{locale === "en" ? "Website and management system by" : "Сайт и система управления созданы на"} <strong>OneStudio OS</strong></p></div></footer> : null,
  };
  const plan = createPremiumTemplateRenderPlan(site.content, ALIGN_PILATES_PREMIUM_TEMPLATE_CONTRACT);
  return <main className={styles.page} lang={locale} style={{ "--ink": site.content.theme_dark ?? "#3D3A34", "--wine": site.content.theme_accent ?? "#6F2B2E", "--paper": site.content.theme_surface ?? "#F7F4ED" } as CSSProperties}>{visible("hero") ? <>
      <div className={styles.promo}>{content.promo}</div>
      <header className={styles.header} data-editor-anchor="hero" data-sticky-align-header="true">
        <Link className={styles.brand} href={basePath} aria-label="ALIGN Pilates Studio"><span>{content.brand}</span><small>{content.brandNote}</small></Link>
        <nav className={styles.nav} aria-label={locale === "en" ? "Main navigation" : "Основная навигация"}>{content.navigation.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}</nav>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div aria-label="Language" style={{ display: "flex", gap: 6, fontSize: 10 }}>{site.available_locales.map((item) => <Link key={item} href={localeHref(item)} aria-current={item === locale ? "page" : undefined}>{item.toUpperCase()}</Link>)}</div>
          <a className={styles.headerCta} data-premium-action={premiumNativeActionKey("align-pilates-studio", "hero", "header-cta")} href={content.headerCta.href}>{content.headerCta.label}</a>
        </div>
      </header>
    </> : null}{plan.map((item) => item.kind === "native" ? <div key={item.key} data-editor-anchor={item.sectionId}>{sections[item.sectionId]}</div> : <div key={item.key} data-editor-anchor={item.key}><PublicCustomBlock block={item.block} services={site.services} bookingHref="#trial" /></div>)}</main>;
}
