import { pricing as englishPricing } from "../en/pricing";

export const pricing = {
  ...englishPricing,
  hero: { eyebrow: "PREISE", title: ["Wähle den passenden Plan", "für deine Aufgaben"], lead: "Pläne für unterschiedliche Anforderungen und Budgets." }, plansHeading: "OneStudio-Pläne", plansSupporting: "14 Tage kostenlos in OneStudio-Plänen.", planLabels: { included: "Im Plan enthalten", storage: "Medien" },
  plans: {
    site: { ...englishPricing.plans.site, description: "Für Website, Portfolio und eine einfache Online-Präsenz deines Unternehmens.", features: ["Eigene Website", "Visueller Editor", "Kontaktformulare und Anfragen", "Portfolio / Galerien", "Grundlegende Analytics", "10 GB monatlicher Traffic"], cta: "Website erstellen" },
    business: { ...englishPricing.plans.business, description: "Alles aus Site plus Buchungen, Kunden, Zahlungen und Arbeitsabläufe.", features: ["Alles aus Site", "Online-Buchungen", "Zeitplan", "Leistungen und Preise", "Mitarbeitende / Ressourcen", "CRM / Kundenbasis", "Online-Zahlungen / Anzahlungen", "Benachrichtigungen / Erinnerungen", "100 GB monatlicher Traffic"], cta: "Jetzt starten", badge: "Am beliebtesten" },
    pro: { ...englishPricing.plans.pro, description: "Alles aus Business plus mehr Mitarbeitende / Ressourcen, Medien und Traffic.", features: ["Alles aus Business", "Mehr Mitarbeitende / Ressourcen", "Bis zu 3 Websites", "100 GB Medien", "500 GB monatlicher Traffic"], cta: "Pro wählen" },
  },
  comparison: { ...englishPricing.comparison, title: "Technische Spezifikationen", sectionTitles: { websiteDesign: "WEBSITE & DESIGN", storageTraffic: "SPEICHER & TRAFFIC", clientWork: "KUNDENARBEIT", teamResources: "TEAM & RESSOURCEN" }, rowLabels: { websiteCount: "Anzahl der Websites", ssl: "SSL / sichere Verbindung", hosting: "Website-Hosting", mobile: "Für Mobilgeräte optimiertes Layout", visualEditor: "Visueller Editor", basicTemplates: "Basisvorlagen", basicBlocks: "Basisblöcke", imageOptimization: "Bildoptimierung", media: "Medien", monthlyTraffic: "Monatlicher Traffic", contactForms: "Kontaktformulare und Anfragen", onlineBooking: "Online-Buchungen", schedule: "Zeitplan", services: "Leistungen und Preise", crm: "CRM / Kundenbasis", payments: "Online-Zahlungen / Anzahlungen", notifications: "Benachrichtigungen / Erinnerungen", staffResources: "Mitarbeitende / Ressourcen" }, valueLabels: { standard: "Standardumfang", more: "Mehr Mitarbeitende / Ressourcen" }, yesLabel: "Im Plan enthalten", noLabel: "Nicht enthalten", priceUnitLabel: "/ Monat", annualPriceLabel: "/ Monat bei jährlicher Zahlung" },
  billing: { monthly: "Monat", annual: "Jahr", priceUnit: "/ Monat", annualNote: "bis zu 68 % günstiger", annualTotal: "pro Jahr", ariaLabel: "Abrechnungszeitraum" },
  design: { eyebrow: "PREMIUM DESIGN LIBRARY", title: "Premium Design Library", body: "Schalte die vollständige Bibliothek mit Premium-Blöcken, interaktiven Effekten und OneStudio-Animationen frei.", priceSuffix: "einmalig", tagline: "Ein Kauf. Die ganze Bibliothek.", note: "Premium Design Library wird separat gekauft und ist nicht in den Plänen oder dem 14-tägigen Gratiszeitraum enthalten.", cta: "Bibliothek öffnen", items: [{ label: "Premium Blocks", description: "Premium-Bausteine für Seiten und ausdrucksstarke Abschnitte." }, { label: "Premium Effects", description: "Interaktive Effekte für den passenden visuellen Akzent." }, { label: "Premium animations", description: "Animationen und interaktive visuelle Komponenten von OneStudio." }] },
  faq: { eyebrow: "PLAN-FAQ", title: "Ein paar kurze Antworten zu den Plänen.", more: "Weitere Antworten →", compactAriaLabel: "Fragen zu den Plänen", items: [{ question: "Gibt es einen kostenlosen Testzeitraum?", answer: "Ja. OneStudio-Pläne können 14 Tage kostenlos getestet werden." }, { question: "Kann ich meine eigene Domain verbinden?", answer: "Ja. Eine eigene Domain ist in den kostenpflichtigen OneStudio-Plänen verfügbar." }, { question: "Was passiert bei einer Überschreitung des Traffic-Limits?", answer: "OneStudio schaltet eine Website nach einer einmaligen Überschreitung nicht sofort ab. Wenn der hohe Traffic dauerhaft wird, kannst du den Plan wechseln oder mehr Traffic hinzufügen." }, { question: "Kann ich den Plan später ändern?", answer: "Ja. Du kannst den Plan ändern, wenn sich die Anforderungen deines Unternehmens verändern." }] },
} as const;
