import { website as englishWebsite } from "../en/website";

export const website = {
  ...englishWebsite,
  hero: { eyebrow: "WEBSITE NACH MASS", title: "Website nach Maß", priceLabel: "ab €249", projectUnit: "Projekt", lead: "Du möchtest die Website nicht selbst bauen? Wir erstellen, konfigurieren und veröffentlichen sie für dich in OneStudio.", priceNote: "Der Preis hängt von Struktur, Design und gewünschten Funktionen ab. Vor Beginn erhältst du einen festen Projektpreis.", cta: "Projekt besprechen", ctaNote: "Wir schlagen den nächsten Schritt vor" },
  included: { eyebrow: "DAS IST ENTHALTEN", title: "Alles für den erfolgreichen Start", lead: "Wir kümmern uns um den Aufbau und die technische Veröffentlichung deiner Website in OneStudio.", items: [{ title: "Design", description: "Wir entwickeln eine visuelle Richtung passend zu deinem Ziel." }, { title: "Seitenaufbau", description: "Wir erstellen Struktur und benötigte Blöcke." }, { title: "Texte und Fotos", description: "Wir platzieren deine Inhalte auf den Seiten." }, { title: "Mobile Anpassung", description: "Wir prüfen die Website auf kleinen Bildschirmen." }, { title: "Domain verbinden", description: "Wir verbinden deine Domain vor dem Launch." }, { title: "Basis-SEO", description: "Wir richten die wichtigsten Seiten-Metadaten ein." }, { title: "Veröffentlichung", description: "Wir bringen die fertige Website in OneStudio online." }] },
  scope: { eyebrow: "WAS DEN PREIS BEEINFLUSST", title: "Ein fester Preis für deinen Umfang", lead: "Der Preis hängt von Struktur, Design und gewünschten Funktionen ab. Vor Beginn erhältst du einen festen Projektpreis.", items: ["Anzahl und Struktur der Seiten", "Individuelles Design", "Premium Effects", "Buchungen / Business-Funktionen", "CRM / Zahlungen / Integrationen", "Mehrere Sprachen", "Sonderfunktionen", "Inhaltsvorbereitung"] },
  process: { eyebrow: "ABLAUF", title: "Vom Gespräch bis zum Launch", steps: [{ number: "01", title: "Besprechen", description: "Wir definieren Ziel, Struktur und Funktionen." }, { number: "02", title: "Preis festlegen", description: "Wir vereinbaren vor Beginn einen Projektpreis." }, { number: "03", title: "Erstellen", description: "Wir bauen Seiten, Design und benötigte Funktionen." }, { number: "04", title: "Launch", description: "Wir verbinden die Domain und veröffentlichen die Website." }] },
  showcase: { eyebrow: "PORTFOLIO", title: "Unsere Arbeiten", lead: "Ausgewählte Websites und Projekte aus unserem Portfolio." },
  portfolio: { "sisters-studio": { projectType: "Kundenprojekt", cta: "Website öffnen", description: null, alt: null }, bembi: { projectType: "Kundenprojekt", cta: "Website öffnen", description: null, alt: null }, "noir-frame": { projectType: "OneStudio Original", cta: "Website öffnen", description: "Ein Premium-Fotostudio mit Portfolio-Ansicht, 3D-Tour und Before/After.", alt: "Helles Fotostudio NOIR FRAME" }, "velora-house": { projectType: "OneStudio Original", cta: "Website öffnen", description: "Hochzeiten, private Dinner und Firmenevents in drei besonderen Sälen.", alt: "VELORA HOUSE Veranstaltungssaal bei Nacht" }, cashpath: { projectType: "Kundenprojekt", cta: "Website öffnen", description: "Eine klare, verbraucherorientierte Website für Kreditoptionen.", alt: "CashPath-Website für persönliche Kreditoptionen" }, "cooking-kids": { projectType: "Website", cta: "Website öffnen", description: null, alt: null }, shuruqhost: { projectType: "Website", cta: "Website öffnen", description: null, alt: null } },
} as const;
