import { pricing as englishPricing } from "../en/pricing";

export const pricing = {
  ...englishPricing,
  hero: { eyebrow: "PREÇOS", title: ["Escolha um plano", "para as suas necessidades"], lead: "Planos para diferentes necessidades e orçamentos." }, plansHeading: "Planos OneStudio", plansSupporting: "14 dias grátis nos planos OneStudio.", planLabels: { included: "Incluído neste plano", storage: "Multimédia" },
  plans: {
    site: { ...englishPricing.plans.site, description: "Para um site, portefólio e uma presença simples do seu negócio online.", features: ["O seu próprio site", "Editor visual", "Formulários de contacto e pedidos", "Portefólio / galerias", "Análises básicas", "10 GB de tráfego mensal"], cta: "Criar um site" },
    business: { ...englishPricing.plans.business, description: "Tudo do Site, mais marcações, clientes, pagamentos e processos de trabalho.", features: ["Tudo do Site", "Marcações online", "Agenda", "Serviços e preços", "Equipa / recursos", "CRM / base de clientes", "Pagamentos online / depósitos", "Notificações / lembretes", "100 GB de tráfego mensal"], cta: "Começar", badge: "Mais popular" },
    pro: { ...englishPricing.plans.pro, description: "Tudo do Business, mais equipa / recursos, multimédia e tráfego adicionais.", features: ["Tudo do Business", "Mais equipa / recursos", "Até 3 sites", "100 GB de multimédia", "500 GB de tráfego mensal"], cta: "Escolher Pro" },
  },
  comparison: { ...englishPricing.comparison, title: "Especificações técnicas", sectionTitles: { websiteDesign: "SITE E DESIGN", storageTraffic: "ARMAZENAMENTO E TRÁFEGO", clientWork: "TRABALHO COM CLIENTES", teamResources: "EQUIPA E RECURSOS" }, rowLabels: { websiteCount: "Número de sites", ssl: "SSL / ligação segura", hosting: "Alojamento do site", mobile: "Layout adaptado a telemóveis", visualEditor: "Editor visual", basicTemplates: "Modelos básicos", basicBlocks: "Blocos básicos", imageOptimization: "Otimização de imagens", media: "Multimédia", monthlyTraffic: "Tráfego mensal", contactForms: "Formulários de contacto e pedidos", onlineBooking: "Marcações online", schedule: "Agenda", services: "Serviços e preços", crm: "CRM / base de clientes", payments: "Pagamentos online / depósitos", notifications: "Notificações / lembretes", staffResources: "Equipa / recursos" }, valueLabels: { standard: "Nível standard", more: "Mais equipa / recursos" }, yesLabel: "Incluído no plano", noLabel: "Não incluído no plano", priceUnitLabel: "/ mês", annualPriceLabel: "/ mês com faturação anual" },
  billing: { monthly: "Mês", annual: "Ano", priceUnit: "/ mês", annualNote: "até 68% menos", annualTotal: "por ano", ariaLabel: "Período de faturação" },
  design: { eyebrow: "PREMIUM DESIGN LIBRARY", title: "Premium Design Library", body: "Desbloqueie a biblioteca completa de blocos premium, efeitos interativos e animações OneStudio.", priceSuffix: "pagamento único", tagline: "Uma compra. Toda a biblioteca.", note: "A Premium Design Library é adquirida separadamente e não está incluída nos planos nem no período gratuito de 14 dias.", cta: "Abrir biblioteca", items: [{ label: "Premium Blocks", description: "Blocos premium para criar páginas e secções expressivas." }, { label: "Premium Effects", description: "Efeitos interativos para o destaque visual certo." }, { label: "Premium animations", description: "Animações e componentes visuais interativos da OneStudio." }] },
  faq: { eyebrow: "FAQ DOS PLANOS", title: "Algumas respostas rápidas sobre os planos.", more: "Mais respostas →", compactAriaLabel: "Perguntas sobre os planos", items: [{ question: "Existe um período experimental gratuito?", answer: "Sim. Pode experimentar os planos OneStudio gratuitamente durante 14 dias." }, { question: "Posso ligar o meu próprio domínio?", answer: "Sim. O seu próprio domínio está disponível nos planos pagos OneStudio." }, { question: "O que acontece se o site ultrapassar o limite de tráfego?", answer: "A OneStudio não desliga o site imediatamente após um excesso pontual. Se o tráfego elevado se tornar habitual, pode mudar de plano ou adicionar mais tráfego." }, { question: "Posso mudar de plano mais tarde?", answer: "Sim. Pode mudar de plano à medida que as necessidades do negócio mudam." }] },
} as const;
