import { website as englishWebsite } from "../en/website";

export const website = {
  ...englishWebsite,
  hero: { eyebrow: "SITE CHAVE NA MÃO", title: "Site chave na mão", priceLabel: "a partir de €249", projectUnit: "projeto", lead: "Não quer criar o site sozinho? Criamos, configuramos e lançamos o seu site no OneStudio por si.", priceNote: "O preço depende da estrutura, do design e das funcionalidades de que precisa. Antes de começar, recebe um preço fixo para o projeto.", cta: "Falar sobre o projeto", ctaNote: "Sugerimos o próximo passo" },
  included: { eyebrow: "O QUE ESTÁ INCLUÍDO", title: "Tudo o que precisa para lançar", lead: "Tratamos da criação do site e da parte técnica da publicação no OneStudio.", items: [{ title: "Design", description: "Criamos uma direção visual à volta do seu objetivo." }, { title: "Construção das páginas", description: "Montamos a estrutura e os blocos necessários." }, { title: "Textos e fotografias", description: "Colocamos os conteúdos fornecidos nas páginas." }, { title: "Adaptação para telemóvel", description: "Verificamos o site em ecrãs mais pequenos." }, { title: "Ligação do domínio", description: "Ligamos o seu domínio antes do lançamento." }, { title: "SEO básico", description: "Configuramos os metadados essenciais das páginas." }, { title: "Publicação", description: "Lançamos o site concluído no OneStudio." }] },
  scope: { eyebrow: "O QUE INFLUENCIA O PREÇO", title: "Um preço fixo para o seu projeto", lead: "O preço depende da estrutura, do design e das funcionalidades de que precisa. Antes de começar, recebe um preço fixo para o projeto.", items: ["Número e estrutura das páginas", "Design personalizado", "Premium Effects", "Marcações / funcionalidades de negócio", "CRM / pagamentos / integrações", "Vários idiomas", "Funcionalidades fora do padrão", "Preparação de conteúdos"] },
  process: { eyebrow: "PROCESSO", title: "Da conversa ao lançamento", steps: [{ number: "01", title: "Conversar", description: "Definimos o objetivo, a estrutura e as funcionalidades." }, { number: "02", title: "Fixar o preço", description: "Combinamos um preço de projeto antes de começar." }, { number: "03", title: "Criar", description: "Construímos as páginas, o design e as funções necessárias." }, { number: "04", title: "Lançar", description: "Ligamos o domínio e publicamos o site." }] },
  showcase: { eyebrow: "PORTEFÓLIO", title: "O nosso trabalho", lead: "Sites criados e lançados com o OneStudio." },
  portfolio: { "sisters-studio": { projectType: "Projeto de cliente", cta: "Abrir site", description: null, alt: null }, bembi: { projectType: "Projeto de cliente", cta: "Abrir site", description: null, alt: null }, "noir-frame": { projectType: "OneStudio Original", cta: "Abrir site", description: "Um estúdio fotográfico premium com portefólio, visita 3D e comparação before/after.", alt: "Estúdio fotográfico NOIR FRAME luminoso" }, "velora-house": { projectType: "OneStudio Original", cta: "Abrir site", description: "Casamentos, jantares privados e eventos empresariais em três salas distintas.", alt: "Sala de eventos VELORA HOUSE à noite" }, cashpath: { projectType: "Projeto de cliente", cta: "Abrir site", description: "Um site claro e orientado ao consumidor para explorar opções de empréstimos pessoais.", alt: "Site CashPath com opções de empréstimos pessoais" } },
} as const;
