import Image from "next/image";
import Link from "next/link";
import PublicCustomBlock from "@/components/public/PublicCustomBlock";
import { isTemplateNativeSectionVisible } from "@/lib/public-site/template-native-section-state";
import { resolveVeloraContent, VELORA_TEMPLATE_KEY } from "@/lib/public-site/velora-premium-template-content";
import type { PublicSiteData } from "@/lib/public-site/types";
import { VeloraAvailability, VeloraGallery } from "./VeloraInteractions";
import styles from "./Velora.module.css";

const title = (eyebrow: string, heading: string) => <div className={styles.sectionTitle}><span>{eyebrow}</span><h2>{heading}</h2></div>;
export default function VeloraSite({ site, basePath }: { site: PublicSiteData; basePath: string }) {
  const c = resolveVeloraContent(site.content); const visible = (id: string) => isTemplateNativeSectionVisible(site.content, VELORA_TEMPLATE_KEY, id);
  const pageHref = (slug: string) => basePath.startsWith("/demos/") ? `${basePath}/${slug}` : `${basePath}/p/${slug}`;
  const sections: Record<string, React.ReactNode> = {
    hero: visible("hero") ? <><header className={styles.header}><Link href={basePath} className={styles.logo}>{c.brand}</Link><nav>{c.navigation.map(item => <Link key={item.label} href={item.href.startsWith("#") ? `${basePath}${item.href}` : item.href}>{item.label}</Link>)}<Link href={pageHref("venues")}>Сравнить залы</Link></nav><Link className={styles.headerCta} href="#availability">Проверить дату</Link></header><section id="hero" className={styles.hero}><Image src={c.hero.image} alt={c.hero.alt} fill priority sizes="100vw" /><div className={styles.heroShade}/><div className={styles.heroContent}><span>{c.hero.eyebrow}</span><h1>{c.hero.title}</h1><p>{c.hero.text}</p><div className={styles.actions}><Link href={c.hero.primaryUrl}>{c.hero.primaryLabel}</Link><Link href={c.hero.secondaryUrl}>{c.hero.secondaryLabel}</Link></div><small>{c.hero.traits}</small></div></section></> : null,
    availability: visible("availability") ? <section id="availability" className={`${styles.section} ${styles.availability}`}>{title(c.availability.eyebrow, c.availability.title)}<p className={styles.lead}>{c.availability.text}</p><VeloraAvailability businessSlug={site.business.slug} venues={c.venues} label={c.availability.submit}/></section> : null,
    venues: visible("venues") ? <section id="venues" className={`${styles.section} ${styles.ivory}`}>{title("ПРОСТРАНСТВА", "Три зала. Три характера.")}<div className={styles.venueGrid}>{c.venues.map((venue, i) => <article key={venue.name}><div><Image src={venue.image} alt={venue.alt} width={1200} height={900} sizes="(max-width: 768px) 100vw, 42vw" /></div><span>0{i + 1} · {venue.area}</span><h3>{venue.name}</h3><p>{venue.capacity}</p><small>{venue.features}</small><a href="#availability">{venue.cta} →</a></article>)}</div><Link className={styles.textLink} href={pageHref("venues")}>Подробное сравнение залов →</Link></section> : null,
    formats: visible("formats") ? <section id="formats" className={`${styles.section} ${styles.navy}`}>{title("ФОРМАТЫ", "Сценарий начинается с вас")}<div className={styles.formatList}>{c.formats.map(item => <article key={item.title}><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section> : null,
    packages: visible("packages") ? <section id="packages" className={`${styles.section} ${styles.ivory}`}>{title("ПАКЕТЫ", "Основа, которую можно сделать личной")}<div className={styles.packageGrid}>{c.packages.map((item, i) => <article key={item.name} className={i === 1 ? styles.featured : ""}><span>{item.for}</span><h3>{item.name}</h3><strong>{item.price}</strong><p>{item.includes}</p><a href="#availability">{item.cta}</a></article>)}</div><Link className={styles.textLink} href={pageHref("packages")}>Сравнить всё включённое →</Link></section> : null,
    gallery: visible("gallery") ? <section id="gallery" className={`${styles.section} ${styles.gallery}`}>{title("ГАЛЕРЕЯ", "Свет, детали, движение")}<VeloraGallery items={c.gallery}/></section> : null,
    catering: visible("catering") ? <section id="catering" className={`${styles.section} ${styles.ivory}`}>{title("КУХНЯ", "Меню следует за настроением вечера")}<div className={styles.simpleGrid}>{c.catering.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><span>{item.meta}</span></article>)}</div></section> : null,
    planner: visible("planner") ? <section id="planner" className={`${styles.section} ${styles.plum}`}>{title("ПЛАНИРОВЩИК", "Спокойная подготовка, точный вечер")}<div className={styles.timeline}>{c.planner.map(item => <article key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><p className={styles.lead}>Личный координатор объединит декор, кейтеринг и техническое оснащение в один понятный план.</p></section> : null,
    facts: visible("facts") ? <section id="facts" className={`${styles.section} ${styles.facts}`}>{c.facts.map(item => <div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</section> : null,
    reviews: visible("reviews") ? <section id="reviews" className={`${styles.section} ${styles.ivory}`}>{title("ОТЗЫВЫ", "Что остаётся после вечера")}<div className={styles.reviewGrid}>{c.reviews.map(item => <blockquote key={item.author}><p>«{item.quote}»</p><footer>{item.author}<span>{item.meta}</span></footer></blockquote>)}</div></section> : null,
    faq: visible("faq") ? <section id="faq" className={`${styles.section} ${styles.navy}`}>{title("FAQ", "До первой встречи")}<div className={styles.faq}>{c.faq.map(item => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section> : null,
    contact: visible("contact") ? <section id="contact" className={`${styles.section} ${styles.contact}`}>{title(c.contact.eyebrow, c.contact.title)}<p className={styles.lead}>{c.contact.text}</p><div className={styles.contactGrid}><address><span>{c.contact.address}</span><a href={`tel:${c.contact.phone.replaceAll(" ", "")}`}>{c.contact.phone}</a><a href={`mailto:${c.contact.email}`}>{c.contact.email}</a><span>{c.contact.hours}</span></address><div className={styles.map} role="img" aria-label="Местоположение VELORA HOUSE"><i/><p>{c.contact.map}</p></div></div><a className={styles.goldButton} href="#availability">{c.contact.cta}</a></section> : null,
    footer: visible("footer") ? <footer className={styles.footer}><Link href={basePath}>{c.brand}</Link><span>{c.footer.note}</span><span>{c.footer.copyright}</span></footer> : null,
  };
  const custom = new Map((site.content.custom_blocks ?? []).map(block => [`custom:${block.id}`, block])); const order = site.content.layout_order?.length ? site.content.layout_order : Object.keys(sections).map(id => `native:${VELORA_TEMPLATE_KEY}:${id}`);
  return <main className={styles.site}>{order.map(token => { const prefix = `native:${VELORA_TEMPLATE_KEY}:`; if (token.startsWith(prefix)) return <div key={token}>{sections[token.slice(prefix.length)]}</div>; const block = custom.get(token); return block ? <PublicCustomBlock key={token} block={block} services={site.services} bookingHref="#availability"/> : null; })}</main>;
}
