import { pricing as englishPricing } from "../en/pricing";

export const pricing = {
  ...englishPricing,
  hero: { eyebrow: "CENNIK", title: ["Wybierz plan", "dla swoich potrzeb"], lead: "Plany dopasowane do różnych potrzeb i budżetów." }, plansHeading: "Plany OneStudio", plansSupporting: "14 dni bezpłatnie w planach OneStudio.", planLabels: { included: "W tym planie", storage: "Media" },
  plans: {
    site: { ...englishPricing.plans.site, description: "Dla strony, portfolio i prostej obecności firmy w internecie.", features: ["Własna strona", "Edytor wizualny", "Formularze kontaktowe i zapytania", "Portfolio / galerie", "Podstawowa analityka", "10 GB ruchu miesięcznie"], cta: "Utwórz stronę" },
    business: { ...englishPricing.plans.business, description: "Wszystko z Site oraz rezerwacje, klienci, płatności i procesy pracy.", features: ["Wszystko z Site", "Rezerwacje online", "Harmonogram", "Usługi i ceny", "Personel / zasoby", "CRM / baza klientów", "Płatności online / zaliczki", "Powiadomienia / przypomnienia", "100 GB ruchu miesięcznie"], cta: "Zacznij", badge: "Najpopularniejszy" },
    pro: { ...englishPricing.plans.pro, description: "Wszystko z Business oraz więcej personelu / zasobów, mediów i ruchu.", features: ["Wszystko z Business", "Więcej personelu / zasobów", "Do 3 stron", "100 GB mediów", "500 GB ruchu miesięcznie"], cta: "Wybierz Pro" },
  },
  comparison: { ...englishPricing.comparison, title: "Specyfikacja techniczna", sectionTitles: { websiteDesign: "STRONA I DESIGN", storageTraffic: "PAMIĘĆ I RUCH", clientWork: "OBSŁUGA KLIENTÓW", teamResources: "ZESPÓŁ I ZASOBY" }, rowLabels: { websiteCount: "Liczba stron", ssl: "SSL / bezpieczne połączenie", hosting: "Hosting strony", mobile: "Układ dostosowany do telefonu", visualEditor: "Edytor wizualny", basicTemplates: "Podstawowe szablony", basicBlocks: "Podstawowe bloki", imageOptimization: "Optymalizacja obrazów", media: "Media", monthlyTraffic: "Ruch miesięczny", contactForms: "Formularze kontaktowe i zapytania", onlineBooking: "Rezerwacje online", schedule: "Harmonogram", services: "Usługi i ceny", crm: "CRM / baza klientów", payments: "Płatności online / zaliczki", notifications: "Powiadomienia / przypomnienia", staffResources: "Personel / zasoby" }, valueLabels: { standard: "Poziom standardowy", more: "Więcej personelu / zasobów" }, yesLabel: "W planie", noLabel: "Poza planem", priceUnitLabel: "/ miesiąc", annualPriceLabel: "/ miesiąc przy płatności rocznej" },
  billing: { monthly: "Miesiąc", annual: "Rok", priceUnit: "/ miesiąc", annualNote: "do 68% taniej", annualTotal: "rocznie", ariaLabel: "Okres rozliczeniowy" },
  design: { eyebrow: "PREMIUM DESIGN LIBRARY", title: "Premium Design Library", body: "Odblokuj pełną bibliotekę premium bloków, interaktywnych efektów i animacji OneStudio.", priceSuffix: "jednorazowo", tagline: "Jeden zakup. Cała biblioteka.", note: "Premium Design Library kupuje się osobno i nie jest częścią planów ani 14-dniowego okresu próbnego.", cta: "Otwórz bibliotekę", items: [{ label: "Premium Blocks", description: "Premium bloki do budowania stron i wyrazistych sekcji." }, { label: "Premium Effects", description: "Interaktywne efekty dla odpowiedniego akcentu wizualnego." }, { label: "Premium animations", description: "Animacje i interaktywne komponenty wizualne OneStudio." }] },
  faq: { eyebrow: "FAQ O PLANACH", title: "Kilka szybkich odpowiedzi o planach.", more: "Więcej odpowiedzi →", compactAriaLabel: "Pytania o plany", items: [{ question: "Czy jest bezpłatny okres próbny?", answer: "Tak. Planów OneStudio możesz bezpłatnie próbować przez 14 dni." }, { question: "Czy mogę podłączyć własną domenę?", answer: "Tak. Własna domena jest dostępna w płatnych planach OneStudio." }, { question: "Co się stanie po przekroczeniu limitu ruchu?", answer: "OneStudio nie wyłącza strony od razu po jednorazowym przekroczeniu limitu. Jeśli duży ruch stanie się stały, możesz zmienić plan lub dodać więcej ruchu." }, { question: "Czy mogę później zmienić plan?", answer: "Tak. Plan możesz zmienić, gdy zmienią się potrzeby Twojej firmy." }] },
} as const;
