import { website as englishWebsite } from "../en/website";

export const website = {
  ...englishWebsite,
  hero: { eyebrow: "STRONA POD KLUCZ", title: "Strona pod klucz", priceLabel: "od €249", projectUnit: "projekt", lead: "Nie chcesz tworzyć strony samodzielnie? Stworzymy, skonfigurujemy i uruchomimy ją dla Ciebie w OneStudio.", priceNote: "Cena zależy od struktury strony, designu i potrzebnych funkcji. Przed rozpoczęciem pracy otrzymasz stałą cenę projektu.", cta: "Porozmawiajmy o projekcie", ctaNote: "Zaproponujemy kolejny krok" },
  included: { eyebrow: "CO OBEJMUJE USŁUGA", title: "Wszystko potrzebne do startu", lead: "Zajmujemy się budową strony i techniczną stroną publikacji w OneStudio.", items: [{ title: "Design", description: "Tworzymy kierunek wizualny wokół Twojego celu." }, { title: "Budowa stron", description: "Układamy strukturę i potrzebne bloki." }, { title: "Tekst i zdjęcia", description: "Umieszczamy dostarczone materiały na stronach." }, { title: "Wersja mobilna", description: "Sprawdzamy stronę na mniejszych ekranach." }, { title: "Podłączenie domeny", description: "Podłączamy Twoją domenę przed startem." }, { title: "Podstawowe SEO", description: "Ustawiamy podstawowe metadane stron." }, { title: "Publikacja", description: "Uruchamiamy gotową stronę w OneStudio." }] },
  scope: { eyebrow: "CO WPŁYWA NA CENĘ", title: "Stała cena dopasowana do zakresu", lead: "Cena zależy od struktury strony, designu i potrzebnych funkcji. Przed rozpoczęciem pracy otrzymasz stałą cenę projektu.", items: ["Liczba i struktura stron", "Indywidualny design", "Premium Effects", "Rezerwacje / funkcje biznesowe", "CRM / płatności / integracje", "Wiele języków", "Niestandardowe funkcje", "Przygotowanie treści"] },
  process: { eyebrow: "PROCES", title: "Od rozmowy do uruchomienia", steps: [{ number: "01", title: "Rozmawiamy", description: "Określamy cel, strukturę i funkcje." }, { number: "02", title: "Ustalamy cenę", description: "Przed pracą uzgadniamy jedną cenę projektu." }, { number: "03", title: "Tworzymy", description: "Budujemy strony, design i potrzebne funkcje." }, { number: "04", title: "Uruchamiamy", description: "Podłączamy domenę i publikujemy stronę." }] },
  showcase: { eyebrow: "PORTFOLIO", title: "Nasze realizacje", lead: "Wybrane strony i projekty z naszego portfolio." },
  portfolio: { "sisters-studio": { projectType: "Projekt klienta", cta: "Otwórz stronę", description: null, alt: null }, bembi: { projectType: "Projekt klienta", cta: "Otwórz stronę", description: null, alt: null }, "noir-frame": { projectType: "OneStudio Original", cta: "Otwórz stronę", description: "Ekskluzywne studio fotograficzne z przeglądarką portfolio, wycieczką 3D i porównaniem before/after.", alt: "Jasne studio fotograficzne NOIR FRAME" }, "velora-house": { projectType: "OneStudio Original", cta: "Otwórz stronę", description: "Wesela, prywatne kolacje i wydarzenia firmowe w trzech wyjątkowych salach.", alt: "Wieczorna sala VELORA HOUSE" }, cashpath: { projectType: "Projekt klienta", cta: "Otwórz stronę", description: "Przejrzysty serwis z opcjami pożyczek konsumenckich.", alt: "Serwis CashPath z opcjami pożyczek konsumenckich" }, "cooking-kids": { projectType: "Projekt klienta", cta: "Otwórz stronę", description: null, alt: null }, shuruqhost: { projectType: "Projekt klienta", cta: "Otwórz stronę", description: null, alt: null } },
} as const;
