import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import PublicCustomPageRuntime from "@/components/public/PublicCustomPageRuntime";
import PublicSiteTemplateRuntime from "@/components/public/PublicSiteTemplateRuntime";
import { newSitePathForTemplate } from "@/lib/public-site/template-catalog";
import { createCanonicalVeloraDemoSite, VELORA_DEMO_BASE_PATH } from "@/lib/public-site/velora-demo";
const description = "Премиальная площадка VELORA HOUSE для свадеб, частных ужинов, дней рождения и корпоративных событий.";
export const metadata: Metadata = { title: "VELORA HOUSE — премиальная event-площадка", description, alternates: { canonical: VELORA_DEMO_BASE_PATH }, robots: { index: true, follow: true }, openGraph: { type: "website", locale: "ru_UA", url: VELORA_DEMO_BASE_PATH, siteName: "OneStudio OS", title: "VELORA HOUSE — Private Event Venue", description, images: [{ url: "/templates/velora/hero.svg", width: 1600, height: 1000, alt: "VELORA HOUSE — вечерний event hall" }] }, twitter: { card: "summary_large_image", title: "VELORA HOUSE", description, images: ["/templates/velora/hero.svg"] } };
export default async function VeloraDemoPage({ params }: { params: Promise<{ templatePath?: string[] }> }) { const { templatePath = [] } = await params; const site = createCanonicalVeloraDemoSite(); let view: React.ReactNode; const customSlug = templatePath[0] === "p" ? templatePath[1] : templatePath.length === 1 ? templatePath[0] : undefined; if (customSlug) { const page = site.content.pages?.find(item => item.type === "custom" && item.slug === customSlug && item.is_visible !== false); if (!page) notFound(); view = <PublicCustomPageRuntime site={site} page={page} basePath={VELORA_DEMO_BASE_PATH}/>; } else if (templatePath.length) notFound(); else view = <PublicSiteTemplateRuntime site={site} basePath={VELORA_DEMO_BASE_PATH}/>; return <><div className="fixed bottom-5 right-5 z-[90]"><Link className="rounded-full bg-[#C6A66B] px-5 py-3 text-sm font-semibold text-[#101827] shadow-2xl" href={newSitePathForTemplate("velora-event-venue")}>Использовать шаблон</Link></div>{view}</>; }
